"""migration

Revision ID: 0001
Revises: 
Create Date: 2026-06-03 14:18:24.900543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mt_14002912f31b47e7a303f1cd1109d0cb',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('unique_identifier', sa.String(length=255), nullable=False),
    sa.Column('asset_type', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.Asset', 'mainsequence_storage_hash': 'mt_mainsequence_examples_c40c07b1f990cebb3a26a511798f83a6', 'mainsequence_logical_fullname': 'public.mt_mainsequence_examples_c40c07b1f990cebb3a26a511798f83a6'}
    )
    op.create_index('mainsequence_markets_asset_asset_type_684c5bc6a660_idx', 'mt_14002912f31b47e7a303f1cd1109d0cb', ['asset_type'], unique=False, schema='public')
    op.create_index('mainsequence_markets_asset_unique_identifier_d5f133ca601c_uidx', 'mt_14002912f31b47e7a303f1cd1109d0cb', ['unique_identifier'], unique=True, schema='public')
    op.create_table('mt_1ed1bc78d9694d1295b7d8992f451b98',
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.Column('asset_identifier', sa.String(), nullable=False),
    sa.Column('open_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('trade_count', sa.Float(), nullable=True),
    sa.Column('vwap', sa.Float(), nullable=True),
    sa.Column('interpolated', sa.Boolean(), nullable=True),
    schema='public',
    info={'mainsequence_storage_hash': 'mt_mainsequence_examples_5ecd981770585499c17cf0fc85f1fd08', 'mainsequence_logical_fullname': 'public.mt_mainsequence_examples_5ecd981770585499c17cf0fc85f1fd08'}
    )
    op.create_table('mt_21cf6aa7e4de453dada68396752fb7e7',
    sa.Column('order_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('order_identifier', sa.String(), nullable=False),
    sa.Column('account_identifier', sa.String(), nullable=False),
    sa.Column('fund_identifier', sa.String(), nullable=True),
    sa.Column('order_manager_identifier', sa.String(), nullable=True),
    sa.Column('asset_identifier', sa.String(), nullable=False),
    sa.Column('order_remote_id', sa.String(), nullable=True),
    sa.Column('client_order_id', sa.String(), nullable=True),
    sa.Column('order_type', sa.String(), nullable=True),
    sa.Column('order_side', sa.BigInteger(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('filled_quantity', sa.Float(), nullable=True),
    sa.Column('filled_price', sa.Float(), nullable=True),
    sa.Column('expires_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('limit_price', sa.Float(), nullable=True),
    sa.Column('time_in_force', sa.String(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('venue_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    schema='public',
    info={'mainsequence_storage_hash': 'mt_mainsequence_examples_a5890841df3ed93a0898fb22502b4854', 'mainsequence_logical_fullname': 'public.mt_mainsequence_examples_a5890841df3ed93a0898fb22502b4854'}
    )
    op.create_table('mt_294010131ab64cb4a2b33c1ca20773e1',
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('order_identifier', sa.String(), nullable=False),
    sa.Column('order_status', sa.String(), nullable=True),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    schema='public',
    info={'mainsequence_storage_hash': 'mt_mainsequence_examples_339c1cfe8c93387af933788c3a3256ea', 'mainsequence_logical_fullname': 'public.mt_mainsequence_examples_339c1cfe8c93387af933788c3a3256ea'}
    )
    op.create_table('mt_3b152b46b8ff4f8bb8314f01406771a2',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('unique_identifier', sa.String(length=255), nullable=False),
    sa.Column('index_type', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.Index', 'mainsequence_storage_hash': 'mt_mainsequence_examples_130a2346289b61c30409ee815c7ae971', 'mainsequence_logical_fullname': 'public.mt_mainsequence_examples_130a2346289b61c30409ee815c7ae971'}
    )
    op.create_index('mainsequence_markets_index_display_name_9579f6318f55_idx', 'mt_3b152b46b8ff4f8bb8314f01406771a2', ['display_name'], unique=False, schema='public')
    op.create_index('mainsequence_markets_index_index_type_8311e1de21c6_idx', 'mt_3b152b46b8ff4f8bb8314f01406771a2', ['index_type'], unique=False, schema='public')
    op.create_index('mainsequence_markets_index_provider_bf4f42641d5c_idx', 'mt_3b152b46b8ff4f8bb8314f01406771a2', ['provider'], unique=False, schema='public')
    op.create_index('mainsequence_markets_index_unique_identifier_120a08bbe6fc_uidx', 'mt_3b152b46b8ff4f8bb8314f01406771a2', ['unique_identifier'], unique=True, schema='public')
    op.create_table('mt_74818467794947c0ae0c7f4bd8d2c27a',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('rebalance_strategy_uid', sa.String(length=255), nullable=False),
    sa.Column('rebalance_strategy_description', sa.Text(), nullable=True),
    sa.Column('configuration_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.RebalanceStrategyMetadata', 'mainsequence_storage_hash': 'mt_mainsequence_examples_7ec83eaa6be794e07c95acd468a6a2b5', 'mainsequence_logical_fullname': 'public.mt_mainsequence_examples_7ec83eaa6be794e07c95acd468a6a2b5'}
    )
    op.create_index('mainsequence_markets_rebalancestrategymetadat_241d24df1f1b_uidx', 'mt_74818467794947c0ae0c7f4bd8d2c27a', ['rebalance_strategy_uid'], unique=True, schema='public')
    op.create_table('mt_77efee4601ef4c2d8c21f9044df8c7e9',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('calendar_dates', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.Calendar', 'mainsequence_storage_hash': 'mt_mainsequence_examples_596004cc8805cf3c80c37b148ce2ef04', 'mainsequence_logical_fullname': 'public.mt_mainsequence_examples_596004cc8805cf3c80c37b148ce2ef04'}
    )
    op.create_index('mainsequence_markets_calendar_name_9ea45889c249_uidx', 'mt_77efee4601ef4c2d8c21f9044df8c7e9', ['name'], unique=True, schema='public')
    op.create_table('mt_79060f5b22ce467abb10612bda54d548',
    sa.Column('trade_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trade_identifier', sa.String(), nullable=False),
    sa.Column('account_identifier', sa.String(), nullable=False),
    sa.Column('fund_identifier', sa.String(), nullable=True),
    sa.Column('order_identifier', sa.String(), nullable=True),
    sa.Column('asset_identifier', sa.String(), nullable=False),
    sa.Column('trade_side', sa.BigInteger(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('commission_asset_identifier', sa.String(), nullable=True),
    sa.Column('settlement_cost', sa.Float(), nullable=True),
    sa.Column('settlement_asset_identifier', sa.String(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('venue_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    schema='public',
    info={'mainsequence_storage_hash': 'mt_mainsequence_examples_24b29bcc9d0e2f3bc405adae091e66bc', 'mainsequence_logical_fullname': 'public.mt_mainsequence_examples_24b29bcc9d0e2f3bc405adae091e66bc'}
    )
    op.create_table('mt_79a458eb5ba6489d879b518bee94308b',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('unique_identifier', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.Issuer', 'mainsequence_storage_hash': 'mt_mainsequence_examples_9a92fdd6ac2593ce7eec45deb69e3734', 'mainsequence_logical_fullname': 'public.mt_mainsequence_examples_9a92fdd6ac2593ce7eec45deb69e3734'}
    )
    op.create_index('mainsequence_markets_issuer_display_name_51a8cff56856_idx', 'mt_79a458eb5ba6489d879b518bee94308b', ['display_name'], unique=False, schema='public')
    op.create_index('mainsequence_markets_issuer_unique_identifier_30d32ed3e3cf_uidx', 'mt_79a458eb5ba6489d879b518bee94308b', ['unique_identifier'], unique=True, schema='public')
    op.create_table('mt_7d68a5e0801c4f19b374c68ed5e0d357',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('asset_type', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.AssetType', 'mainsequence_storage_hash': 'mt_mainsequence_examples_25e393d52975f2b5f6412fb9c1f7ab5f', 'mainsequence_logical_fullname': 'public.mt_mainsequence_examples_25e393d52975f2b5f6412fb9c1f7ab5f'}
    )
    op.create_index('mainsequence_markets_assettype_asset_type_731d1b0f09e0_uidx', 'mt_7d68a5e0801c4f19b374c68ed5e0d357', ['asset_type'], unique=True, schema='public')
    op.create_index('mainsequence_markets_assettype_display_name_b40eb3745423_idx', 'mt_7d68a5e0801c4f19b374c68ed5e0d357', ['display_name'], unique=False, schema='public')
    op.create_table('mt_80600ce04a6244dfb17c3d5cf91ac8bc',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('unique_identifier', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.AssetCategory', 'mainsequence_storage_hash': 'mt_mainsequence_examples_a7208de496a4b6151386a6155fbef772', 'mainsequence_logical_fullname': 'public.mt_mainsequence_examples_a7208de496a4b6151386a6155fbef772'}
    )
    op.create_index('mainsequence_markets_assetcategory_display_nam_77c0d81c54c3_idx', 'mt_80600ce04a6244dfb17c3d5cf91ac8bc', ['display_name'], unique=False, schema='public')
    op.create_index('mainsequence_markets_assetcategory_unique_ide_dddb40d0bb7f_uidx', 'mt_80600ce04a6244dfb17c3d5cf91ac8bc', ['unique_identifier'], unique=True, schema='public')
    op.create_table('mt_8ab497ed69b3436692f4f3dc28afa4e5',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('index_type', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.IndexType', 'mainsequence_storage_hash': 'mt_mainsequence_examples_070512a7d0520e2979a16b7ff9886a53', 'mainsequence_logical_fullname': 'public.mt_mainsequence_examples_070512a7d0520e2979a16b7ff9886a53'}
    )
    op.create_index('mainsequence_markets_indextype_display_name_99dbb0273fca_idx', 'mt_8ab497ed69b3436692f4f3dc28afa4e5', ['display_name'], unique=False, schema='public')
    op.create_index('mainsequence_markets_indextype_index_type_2bb910756bb5_uidx', 'mt_8ab497ed69b3436692f4f3dc28afa4e5', ['index_type'], unique=True, schema='public')
    op.create_table('mt_8b295571395b43258e1f584bb4901bd8',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('group_name', sa.String(length=100), nullable=True),
    sa.Column('group_description', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.AccountGroup', 'mainsequence_storage_hash': 'mt_mainsequence_examples_088962091e5ba9c63d94e9a2b9d1bb82', 'mainsequence_logical_fullname': 'public.mt_mainsequence_examples_088962091e5ba9c63d94e9a2b9d1bb82'}
    )
    op.create_index('mainsequence_markets_accountgroup_group_name_e1ca0e2e9d5c_uidx', 'mt_8b295571395b43258e1f584bb4901bd8', ['group_name'], unique=True, schema='public')
    op.create_table('mt_8b543e69562a4034a771ae20485c900c',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('context_key', sa.String(length=64), nullable=False),
    sa.Column('concept_key', sa.String(length=128), nullable=False),
    sa.Column('data_node_identifier', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.PricingMarketDataBinding', 'mainsequence_storage_hash': 'mt_mainsequence_examples_16c62f095ac9cc74ac3f84c6ed895369', 'mainsequence_logical_fullname': 'public.mt_mainsequence_examples_16c62f095ac9cc74ac3f84c6ed895369'}
    )
    op.create_index('mainsequence_markets_pricingmarketdatabinding_44f925bee7e9_uidx', 'mt_8b543e69562a4034a771ae20485c900c', ['context_key', 'concept_key'], unique=True, schema='public')
    op.create_index('mainsequence_markets_pricingmarketdatabinding_a274af579c0a_idx', 'mt_8b543e69562a4034a771ae20485c900c', ['context_key'], unique=False, schema='public')
    op.create_index('mainsequence_markets_pricingmarketdatabinding_f3efd96b076c_idx', 'mt_8b543e69562a4034a771ae20485c900c', ['concept_key'], unique=False, schema='public')
    op.create_table('mt_a4f2919a0a1c44b684a74858ea9f10f7',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('unique_identifier', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.PortfolioMetadata', 'mainsequence_storage_hash': 'mt_mainsequence_examples_b0e68bc533007e5c8d0b05a3c140c6c9', 'mainsequence_logical_fullname': 'public.mt_mainsequence_examples_b0e68bc533007e5c8d0b05a3c140c6c9'}
    )
    op.create_index('mainsequence_markets_portfoliometadata_unique_b2ec62679586_uidx', 'mt_a4f2919a0a1c44b684a74858ea9f10f7', ['unique_identifier'], unique=True, schema='public')
    op.create_table('mt_aa110877fa6a4b4d9d289aa82ce8d818',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('model_portfolio_name', sa.String(length=100), nullable=False),
    sa.Column('model_portfolio_description', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.AccountModelPortfolio', 'mainsequence_storage_hash': 'mt_mainsequence_examples_ce5539f25ac7e74ce7bf2fa57fcfbc20', 'mainsequence_logical_fullname': 'public.mt_mainsequence_examples_ce5539f25ac7e74ce7bf2fa57fcfbc20'}
    )
    op.create_index('mainsequence_markets_accountmodelportfolio_mo_f3712daf1e44_uidx', 'mt_aa110877fa6a4b4d9d289aa82ce8d818', ['model_portfolio_name'], unique=True, schema='public')
    op.create_table('mt_aa8bd61f07bb49bbb873b45443ee6925',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('signal_uid', sa.String(length=255), nullable=False),
    sa.Column('signal_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.SignalMetadata', 'mainsequence_storage_hash': 'mt_mainsequence_examples_2887ed761366476b7edd1f106d054c34', 'mainsequence_logical_fullname': 'public.mt_mainsequence_examples_2887ed761366476b7edd1f106d054c34'}
    )
    op.create_index('mainsequence_markets_signalmetadata_signal_ui_549a26971d9f_uidx', 'mt_aa8bd61f07bb49bbb873b45443ee6925', ['signal_uid'], unique=True, schema='public')
    op.create_table('mt_eadf9318c6574bf6bd837c6004cf84bb',
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.Column('portfolio_identifier', sa.String(), nullable=False),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('return', sa.Float(), nullable=True),
    sa.Column('calculated_close', sa.Float(), nullable=True),
    sa.Column('close_time', sa.DateTime(timezone=True), nullable=True),
    schema='public',
    info={'mainsequence_storage_hash': 'mt_mainsequence_examples_8648e3d9e36b2e926ab1257350e7cffd', 'mainsequence_logical_fullname': 'public.mt_mainsequence_examples_8648e3d9e36b2e926ab1257350e7cffd'}
    )
    op.create_table('mt_ecd56882aa99452ea1e1409ec0021a1d',
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.Column('portfolio_index_identifier', sa.String(), nullable=False),
    sa.Column('asset_identifier', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('weight_before', sa.Float(), nullable=True),
    sa.Column('price_current', sa.Float(), nullable=True),
    sa.Column('price_before', sa.Float(), nullable=True),
    sa.Column('volume_current', sa.Float(), nullable=True),
    sa.Column('volume_before', sa.Float(), nullable=True),
    schema='public',
    info={'mainsequence_storage_hash': 'mt_mainsequence_examples_f18a95b8fea75532d4db5d04e6f939f0', 'mainsequence_logical_fullname': 'public.mt_mainsequence_examples_f18a95b8fea75532d4db5d04e6f939f0'}
    )
    op.create_table('mt_ee7aa658a6c647ccba01db68ef999e8c',
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signal_uid', sa.String(), nullable=False),
    sa.Column('asset_identifier', sa.String(), nullable=False),
    sa.Column('signal_weight', sa.Float(), nullable=True),
    schema='public',
    info={'mainsequence_storage_hash': 'mt_mainsequence_examples_2f45861ae5e5b966c72472c87b00259a', 'mainsequence_logical_fullname': 'public.mt_mainsequence_examples_2f45861ae5e5b966c72472c87b00259a'}
    )
    op.create_table('mt_f275cc1268034d31ad0d8b585fcaf794',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('namespace', sa.String(length=255), nullable=False),
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('meta_table_uid', sa.String(length=64), nullable=False),
    sa.Column('contract_hash', sa.String(length=64), nullable=False),
    sa.Column('sdk_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.MarketsMetaTableCatalog', 'mainsequence_storage_hash': 'mt_mainsequence_examples_b28d7244fff72fa5b8c166ee4c1a5272', 'mainsequence_logical_fullname': 'public.mt_mainsequence_examples_b28d7244fff72fa5b8c166ee4c1a5272'}
    )
    op.create_index('mainsequence_markets_marketsmetatablecatalog_22914510666e_uidx', 'mt_f275cc1268034d31ad0d8b585fcaf794', ['meta_table_uid'], unique=True, schema='public')
    op.create_index('mainsequence_markets_marketsmetatablecatalog_ab388359ccb8_uidx', 'mt_f275cc1268034d31ad0d8b585fcaf794', ['identifier'], unique=True, schema='public')
    op.create_table('mt_02d5a3353dc247a1a2e94ab22dabfde6',
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.Column('index_identifier', sa.String(length=255), nullable=False),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['index_identifier'], ['public.mt_3b152b46b8ff4f8bb8314f01406771a2.unique_identifier'], ondelete='RESTRICT'),
    schema='public',
    info={'mainsequence_storage_hash': 'mt_mainsequence_examples_e98c7cb3b4df1f3a9a242b802c9c60bf', 'mainsequence_logical_fullname': 'public.mt_mainsequence_examples_e98c7cb3b4df1f3a9a242b802c9c60bf'}
    )
    op.create_table('mt_3e4c46a3f4264224b973a8248adb97c0',
    sa.Column('asset_uid', sa.Uuid(), nullable=False),
    sa.Column('figi', sa.String(length=12), nullable=True),
    sa.Column('composite', sa.String(length=12), nullable=True),
    sa.Column('share_class', sa.String(length=12), nullable=True),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('ticker', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('exchange_code', sa.String(length=50), nullable=True),
    sa.Column('security_type', sa.String(length=50), nullable=True),
    sa.Column('security_type_2', sa.String(length=50), nullable=True),
    sa.Column('security_market_sector', sa.String(length=50), nullable=True),
    sa.Column('security_description', sa.String(length=255), nullable=True),
    sa.Column('unique_id', sa.String(length=255), nullable=True),
    sa.Column('unique_id_fut_opt', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['asset_uid'], ['public.mt_14002912f31b47e7a303f1cd1109d0cb.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.OpenFigiAssetDetails', 'mainsequence_storage_hash': 'mt_mainsequence_examples_7cf6ea0f56f592d9caf5686a4a62bc91', 'mainsequence_logical_fullname': 'public.mt_mainsequence_examples_7cf6ea0f56f592d9caf5686a4a62bc91'}
    )
    op.create_index('mainsequence_markets_openfigiassetdetails_figi_d89cb43a3d26_idx', 'mt_3e4c46a3f4264224b973a8248adb97c0', ['figi'], unique=False, schema='public')
    op.create_index('mainsequence_markets_openfigiassetdetails_isin_d5a68ba5375d_idx', 'mt_3e4c46a3f4264224b973a8248adb97c0', ['isin'], unique=False, schema='public')
    op.create_index('mainsequence_markets_openfigiassetdetails_tick_7fecd72d69d4_idx', 'mt_3e4c46a3f4264224b973a8248adb97c0', ['ticker'], unique=False, schema='public')
    op.create_table('mt_557ec35c90754a60884eed1a3c05c9cc',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('unique_identifier', sa.String(length=255), nullable=False),
    sa.Column('calendar_name', sa.String(length=255), nullable=True),
    sa.Column('portfolio_index_uid', sa.Uuid(), nullable=True),
    sa.Column('portfolio_weights_data_node_uid', sa.Uuid(), nullable=True),
    sa.Column('signal_weights_data_node_uid', sa.Uuid(), nullable=True),
    sa.Column('portfolio_data_node_uid', sa.Uuid(), nullable=True),
    sa.Column('backtest_table_price_column_name', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_index_uid'], ['public.mt_3b152b46b8ff4f8bb8314f01406771a2.uid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.Portfolio', 'mainsequence_storage_hash': 'mt_mainsequence_examples_3bb24b5200c4086e9bf8567ae0f996d8', 'mainsequence_logical_fullname': 'public.mt_mainsequence_examples_3bb24b5200c4086e9bf8567ae0f996d8'}
    )
    op.create_index('mainsequence_markets_portfolio_calendar_name_d913666549aa_idx', 'mt_557ec35c90754a60884eed1a3c05c9cc', ['calendar_name'], unique=False, schema='public')
    op.create_index('mainsequence_markets_portfolio_portfolio_index_3c67a6ed89bd_idx', 'mt_557ec35c90754a60884eed1a3c05c9cc', ['portfolio_index_uid'], unique=False, schema='public')
    op.create_index('mainsequence_markets_portfolio_unique_identif_fe802aa8a17c_uidx', 'mt_557ec35c90754a60884eed1a3c05c9cc', ['unique_identifier'], unique=True, schema='public')
    op.create_table('mt_795e3251a2b14ec385ad62351df7a629',
    sa.Column('asset_uid', sa.Uuid(), nullable=False),
    sa.Column('issuer_uid', sa.Uuid(), nullable=False),
    sa.Column('currency_asset_uid', sa.Uuid(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['asset_uid'], ['public.mt_14002912f31b47e7a303f1cd1109d0cb.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['currency_asset_uid'], ['public.mt_14002912f31b47e7a303f1cd1109d0cb.uid'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['issuer_uid'], ['public.mt_79a458eb5ba6489d879b518bee94308b.uid'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('asset_uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.BondAssetDetails', 'mainsequence_storage_hash': 'mt_mainsequence_examples_238078e18fcbc62601af976f5d994b9c', 'mainsequence_logical_fullname': 'public.mt_mainsequence_examples_238078e18fcbc62601af976f5d994b9c'}
    )
    op.create_index('mainsequence_markets_bondassetdetails_currency_353c9c596e3d_idx', 'mt_795e3251a2b14ec385ad62351df7a629', ['currency_asset_uid'], unique=False, schema='public')
    op.create_index('mainsequence_markets_bondassetdetails_issuer_u_f9a3e2bb287d_idx', 'mt_795e3251a2b14ec385ad62351df7a629', ['issuer_uid'], unique=False, schema='public')
    op.create_index('mainsequence_markets_bondassetdetails_maturity_1b3594abaeae_idx', 'mt_795e3251a2b14ec385ad62351df7a629', ['maturity_date'], unique=False, schema='public')
    op.create_index('mainsequence_markets_bondassetdetails_status_15d1ff1dc071_idx', 'mt_795e3251a2b14ec385ad62351df7a629', ['status'], unique=False, schema='public')
    op.create_table('mt_a21caf90a6844e6483c8d4afbce5da14',
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.Column('asset_identifier', sa.String(length=255), nullable=False),
    sa.Column('instrument_dump', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['asset_identifier'], ['public.mt_14002912f31b47e7a303f1cd1109d0cb.unique_identifier'], ondelete='RESTRICT'),
    schema='public',
    info={'mainsequence_storage_hash': 'mt_mainsequence_examples_41c665336a3a5360b22c5fd1483cb858', 'mainsequence_logical_fullname': 'public.mt_mainsequence_examples_41c665336a3a5360b22c5fd1483cb858'}
    )
    op.create_table('mt_b744298b10414385bc8d646a8e6c2d02',
    sa.Column('asset_uid', sa.Uuid(), nullable=False),
    sa.Column('base_currency_uid', sa.Uuid(), nullable=False),
    sa.Column('quote_currency_uid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['asset_uid'], ['public.mt_14002912f31b47e7a303f1cd1109d0cb.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['base_currency_uid'], ['public.mt_14002912f31b47e7a303f1cd1109d0cb.uid'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['quote_currency_uid'], ['public.mt_14002912f31b47e7a303f1cd1109d0cb.uid'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('asset_uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.CurrencySpotAssetDetails', 'mainsequence_storage_hash': 'mt_mainsequence_examples_a60cbfc891bbc3db76b9bef33b50c729', 'mainsequence_logical_fullname': 'public.mt_mainsequence_examples_a60cbfc891bbc3db76b9bef33b50c729'}
    )
    op.create_index('mainsequence_markets_currencyspotassetdetails_7b5b579c2629_idx', 'mt_b744298b10414385bc8d646a8e6c2d02', ['quote_currency_uid'], unique=False, schema='public')
    op.create_index('mainsequence_markets_currencyspotassetdetails_94457ff301ee_idx', 'mt_b744298b10414385bc8d646a8e6c2d02', ['base_currency_uid'], unique=False, schema='public')
    op.create_index('mainsequence_markets_currencyspotassetdetails_9cf63880c07c_uidx', 'mt_b744298b10414385bc8d646a8e6c2d02', ['base_currency_uid', 'quote_currency_uid'], unique=True, schema='public')
    op.create_table('mt_be93811e3458480189f1c7257f2fd8f2',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('unique_identifier', sa.String(length=255), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('is_paper', sa.Boolean(), nullable=False),
    sa.Column('account_is_active', sa.Boolean(), nullable=False),
    sa.Column('account_group_uid', sa.Uuid(), nullable=True),
    sa.Column('holdings_data_node_uid', sa.Uuid(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['account_group_uid'], ['public.mt_8b295571395b43258e1f584bb4901bd8.uid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.Account', 'mainsequence_storage_hash': 'mt_mainsequence_examples_8e3837af05e69b7cc532d7bae397ea94', 'mainsequence_logical_fullname': 'public.mt_mainsequence_examples_8e3837af05e69b7cc532d7bae397ea94'}
    )
    op.create_index('mainsequence_markets_account_account_group_uid_ad0cf18059d8_idx', 'mt_be93811e3458480189f1c7257f2fd8f2', ['account_group_uid'], unique=False, schema='public')
    op.create_index('mainsequence_markets_account_account_is_active_c71a4fc46ef7_idx', 'mt_be93811e3458480189f1c7257f2fd8f2', ['account_is_active'], unique=False, schema='public')
    op.create_index('mainsequence_markets_account_account_name_c13dad2efec0_idx', 'mt_be93811e3458480189f1c7257f2fd8f2', ['account_name'], unique=False, schema='public')
    op.create_index('mainsequence_markets_account_unique_identifie_2b66a4111f93_uidx', 'mt_be93811e3458480189f1c7257f2fd8f2', ['unique_identifier'], unique=True, schema='public')
    op.create_table('mt_c33871b6f74d4084b97980d91c39522a',
    sa.Column('index_uid', sa.Uuid(), nullable=False),
    sa.Column('index_family', sa.String(length=64), nullable=False),
    sa.Column('convention_dump', sa.JSON(), nullable=False),
    sa.Column('serialization_format', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['index_uid'], ['public.mt_3b152b46b8ff4f8bb8314f01406771a2.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('index_uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.IndexConventionDetails', 'mainsequence_storage_hash': 'mt_mainsequence_examples_89aa8ed8818988fcb00e3f6c271e1d65', 'mainsequence_logical_fullname': 'public.mt_mainsequence_examples_89aa8ed8818988fcb00e3f6c271e1d65'}
    )
    op.create_index('mainsequence_markets_indexconventiondetails_in_f9242e15a176_idx', 'mt_c33871b6f74d4084b97980d91c39522a', ['index_family'], unique=False, schema='public')
    op.create_index('mainsequence_markets_indexconventiondetails_so_0199939d9106_idx', 'mt_c33871b6f74d4084b97980d91c39522a', ['source'], unique=False, schema='public')
    op.create_table('mt_da500bedbbb64b5dbc14f07769911ea4',
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.Column('asset_identifier', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('exchange_code', sa.String(), nullable=True),
    sa.Column('asset_ticker_group_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['asset_identifier'], ['public.mt_14002912f31b47e7a303f1cd1109d0cb.unique_identifier'], ondelete='RESTRICT'),
    schema='public',
    info={'mainsequence_storage_hash': 'mt_mainsequence_examples_08ca6160d9b8eadc6fec71726eab41e4', 'mainsequence_logical_fullname': 'public.mt_mainsequence_examples_08ca6160d9b8eadc6fec71726eab41e4'}
    )
    op.create_table('mt_dc1e819a482a410686718ce3a35e183a',
    sa.Column('asset_uid', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('underlying_index_uid', sa.Uuid(), nullable=False),
    sa.Column('quote_unit', sa.String(length=64), nullable=False),
    sa.Column('settlement_asset', sa.Uuid(), nullable=False),
    sa.Column('margin_asset', sa.Uuid(), nullable=False),
    sa.Column('settlement_model', sa.String(length=32), nullable=False),
    sa.Column('settlement_method', sa.String(length=32), nullable=False),
    sa.Column('contract_size', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('contract_unit', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settles_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['asset_uid'], ['public.mt_14002912f31b47e7a303f1cd1109d0cb.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['margin_asset'], ['public.mt_14002912f31b47e7a303f1cd1109d0cb.uid'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['settlement_asset'], ['public.mt_14002912f31b47e7a303f1cd1109d0cb.uid'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['underlying_index_uid'], ['public.mt_3b152b46b8ff4f8bb8314f01406771a2.uid'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('asset_uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.FutureAssetDetails', 'mainsequence_storage_hash': 'mt_mainsequence_examples_f23dc91d2851c7d7c63b7fdcd3eb6c86', 'mainsequence_logical_fullname': 'public.mt_mainsequence_examples_f23dc91d2851c7d7c63b7fdcd3eb6c86'}
    )
    op.create_index('mainsequence_markets_futureassetdetails_expire_65ca9d5e687f_idx', 'mt_dc1e819a482a410686718ce3a35e183a', ['expires_at'], unique=False, schema='public')
    op.create_index('mainsequence_markets_futureassetdetails_margin_ae85056e76be_idx', 'mt_dc1e819a482a410686718ce3a35e183a', ['margin_asset'], unique=False, schema='public')
    op.create_index('mainsequence_markets_futureassetdetails_settle_1c5aae3036c0_idx', 'mt_dc1e819a482a410686718ce3a35e183a', ['settlement_asset'], unique=False, schema='public')
    op.create_index('mainsequence_markets_futureassetdetails_underl_34d349a490f1_idx', 'mt_dc1e819a482a410686718ce3a35e183a', ['underlying_index_uid'], unique=False, schema='public')
    op.create_table('mt_dca2ed44cae541a6880d7e9e2866dfe4',
    sa.Column('asset_uid', sa.Uuid(), nullable=False),
    sa.Column('instrument_type', sa.String(length=128), nullable=False),
    sa.Column('instrument_dump', sa.JSON(), nullable=False),
    sa.Column('pricing_details_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('serialization_format', sa.String(length=128), nullable=False),
    sa.Column('pricing_package_version', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['asset_uid'], ['public.mt_14002912f31b47e7a303f1cd1109d0cb.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.AssetCurrentPricingDetails', 'mainsequence_storage_hash': 'mt_mainsequence_examples_8aed6c4ca7bbc7917e2a2966fcc714f7', 'mainsequence_logical_fullname': 'public.mt_mainsequence_examples_8aed6c4ca7bbc7917e2a2966fcc714f7'}
    )
    op.create_index('mainsequence_markets_assetcurrentpricingdetail_2284f555148b_idx', 'mt_dca2ed44cae541a6880d7e9e2866dfe4', ['instrument_type'], unique=False, schema='public')
    op.create_index('mainsequence_markets_assetcurrentpricingdetail_88814219e287_idx', 'mt_dca2ed44cae541a6880d7e9e2866dfe4', ['pricing_details_date'], unique=False, schema='public')
    op.create_table('mt_f81a09f6c9be482e921cf0e280a25d58',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('category_uid', sa.Uuid(), nullable=False),
    sa.Column('asset_uid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['asset_uid'], ['public.mt_14002912f31b47e7a303f1cd1109d0cb.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_uid'], ['public.mt_80600ce04a6244dfb17c3d5cf91ac8bc.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.AssetCategoryMembership', 'mainsequence_storage_hash': 'mt_mainsequence_examples_52d521f6823dac71895a02b901f65991', 'mainsequence_logical_fullname': 'public.mt_mainsequence_examples_52d521f6823dac71895a02b901f65991'}
    )
    op.create_index('mainsequence_markets_assetcategorymembership_598eb8470799_uidx', 'mt_f81a09f6c9be482e921cf0e280a25d58', ['category_uid', 'asset_uid'], unique=True, schema='public')
    op.create_index('mainsequence_markets_assetcategorymembership_a_3cb052aeb282_idx', 'mt_f81a09f6c9be482e921cf0e280a25d58', ['asset_uid'], unique=False, schema='public')
    op.create_table('mt_0b71934a2b78437f9ef72733987ab46b',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('unique_identifier', sa.String(length=255), nullable=False),
    sa.Column('account_uid', sa.Uuid(), nullable=False),
    sa.Column('target_portfolio_uid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['account_uid'], ['public.mt_be93811e3458480189f1c7257f2fd8f2.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_portfolio_uid'], ['public.mt_557ec35c90754a60884eed1a3c05c9cc.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.VirtualFund', 'mainsequence_storage_hash': 'mt_mainsequence_examples_0edecaeae57ad76a95145fb50a5ae229', 'mainsequence_logical_fullname': 'public.mt_mainsequence_examples_0edecaeae57ad76a95145fb50a5ae229'}
    )
    op.create_index('mainsequence_markets_virtualfund_account_uid_3aff03fdd331_idx', 'mt_0b71934a2b78437f9ef72733987ab46b', ['account_uid'], unique=False, schema='public')
    op.create_index('mainsequence_markets_virtualfund_target_portfo_9388efa3e017_idx', 'mt_0b71934a2b78437f9ef72733987ab46b', ['target_portfolio_uid'], unique=False, schema='public')
    op.create_index('mainsequence_markets_virtualfund_unique_ident_992c1b584486_uidx', 'mt_0b71934a2b78437f9ef72733987ab46b', ['unique_identifier'], unique=True, schema='public')
    op.create_table('mt_3b3990a0b7b540419d7b38c292aaa5de',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('unique_identifier', sa.String(length=255), nullable=False),
    sa.Column('account_uid', sa.Uuid(), nullable=False),
    sa.Column('account_model_portfolio_uid', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['account_model_portfolio_uid'], ['public.mt_aa110877fa6a4b4d9d289aa82ce8d818.uid'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['account_uid'], ['public.mt_be93811e3458480189f1c7257f2fd8f2.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.AccountTargetPortfolio', 'mainsequence_storage_hash': 'mt_mainsequence_examples_b26a78c0f633f3cfae147e7e6aee558c', 'mainsequence_logical_fullname': 'public.mt_mainsequence_examples_b26a78c0f633f3cfae147e7e6aee558c'}
    )
    op.create_index('mainsequence_markets_accounttargetportfolio_ac_2e2d71d32399_idx', 'mt_3b3990a0b7b540419d7b38c292aaa5de', ['account_uid'], unique=False, schema='public')
    op.create_index('mainsequence_markets_accounttargetportfolio_ac_5c78e3b77b7a_idx', 'mt_3b3990a0b7b540419d7b38c292aaa5de', ['account_model_portfolio_uid'], unique=False, schema='public')
    op.create_index('mainsequence_markets_accounttargetportfolio_is_2296e36b784f_idx', 'mt_3b3990a0b7b540419d7b38c292aaa5de', ['is_active'], unique=False, schema='public')
    op.create_index('mainsequence_markets_accounttargetportfolio_u_c99890b9966b_uidx', 'mt_3b3990a0b7b540419d7b38c292aaa5de', ['unique_identifier'], unique=True, schema='public')
    op.create_table('mt_55f3c12a219a4cdda0530e0be6380c18',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('account_uid', sa.Uuid(), nullable=False),
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_data_node_uid', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['account_uid'], ['public.mt_be93811e3458480189f1c7257f2fd8f2.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.AccountHoldingsSet', 'mainsequence_storage_hash': 'mt_mainsequence_examples_91419aacc2b4b38f036c4f1cff3f1de8', 'mainsequence_logical_fullname': 'public.mt_mainsequence_examples_91419aacc2b4b38f036c4f1cff3f1de8'}
    )
    op.create_index('mainsequence_markets_accountholdingsset_accou_6223c5e2529f_uidx', 'mt_55f3c12a219a4cdda0530e0be6380c18', ['account_uid', 'time_index'], unique=True, schema='public')
    op.create_index('mainsequence_markets_accountholdingsset_accoun_7d56f1117a13_idx', 'mt_55f3c12a219a4cdda0530e0be6380c18', ['account_uid'], unique=False, schema='public')
    op.create_index('mainsequence_markets_accountholdingsset_time_i_620100c08dfb_idx', 'mt_55f3c12a219a4cdda0530e0be6380c18', ['time_index'], unique=False, schema='public')
    op.create_table('mt_7fbd7b692050434bbcbf4773aa77a119',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('unique_identifier', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('curve_type', sa.String(length=64), nullable=False),
    sa.Column('index_uid', sa.Uuid(), nullable=False),
    sa.Column('interpolation_method', sa.String(length=64), nullable=True),
    sa.Column('compounding', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['index_uid'], ['public.mt_c33871b6f74d4084b97980d91c39522a.index_uid'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.Curve', 'mainsequence_storage_hash': 'mt_mainsequence_examples_598a642dbc8d07a754ca9d99bcb13a4f', 'mainsequence_logical_fullname': 'public.mt_mainsequence_examples_598a642dbc8d07a754ca9d99bcb13a4f'}
    )
    op.create_index('mainsequence_markets_curve_curve_type_a782179014d2_idx', 'mt_7fbd7b692050434bbcbf4773aa77a119', ['curve_type'], unique=False, schema='public')
    op.create_index('mainsequence_markets_curve_index_uid_72b6b940da59_idx', 'mt_7fbd7b692050434bbcbf4773aa77a119', ['index_uid'], unique=False, schema='public')
    op.create_index('mainsequence_markets_curve_source_340195c5e17b_idx', 'mt_7fbd7b692050434bbcbf4773aa77a119', ['source'], unique=False, schema='public')
    op.create_index('mainsequence_markets_curve_unique_identifier_41f0a21bd7bd_uidx', 'mt_7fbd7b692050434bbcbf4773aa77a119', ['unique_identifier'], unique=True, schema='public')
    op.create_table('mt_a2bd3f4067f34df5967629228f36b4b4',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('unique_identifier', sa.String(length=255), nullable=False),
    sa.Column('target_account_uid', sa.Uuid(), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('order_received_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['target_account_uid'], ['public.mt_be93811e3458480189f1c7257f2fd8f2.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.OrderManager', 'mainsequence_storage_hash': 'mt_mainsequence_examples_37d3a94ac5d70645c8bc94ae74065b1c', 'mainsequence_logical_fullname': 'public.mt_mainsequence_examples_37d3a94ac5d70645c8bc94ae74065b1c'}
    )
    op.create_index('mainsequence_markets_ordermanager_status_6084fa71dc55_idx', 'mt_a2bd3f4067f34df5967629228f36b4b4', ['status'], unique=False, schema='public')
    op.create_index('mainsequence_markets_ordermanager_target_accou_09d760f6b6e7_idx', 'mt_a2bd3f4067f34df5967629228f36b4b4', ['target_account_uid'], unique=False, schema='public')
    op.create_index('mainsequence_markets_ordermanager_unique_iden_10c12424f694_uidx', 'mt_a2bd3f4067f34df5967629228f36b4b4', ['unique_identifier'], unique=True, schema='public')
    op.create_table('mt_033bee86849649f887a4df1e6c30f1eb',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('account_target_portfolio_uid', sa.Uuid(), nullable=False),
    sa.Column('position_set_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['account_target_portfolio_uid'], ['public.mt_3b3990a0b7b540419d7b38c292aaa5de.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.PositionSet', 'mainsequence_storage_hash': 'mt_mainsequence_examples_c98cd73d6dcee29c87e26242cf4e4f78', 'mainsequence_logical_fullname': 'public.mt_mainsequence_examples_c98cd73d6dcee29c87e26242cf4e4f78'}
    )
    op.create_index('mainsequence_markets_positionset_account_targ_4d4d735f97d5_uidx', 'mt_033bee86849649f887a4df1e6c30f1eb', ['account_target_portfolio_uid', 'position_set_time'], unique=True, schema='public')
    op.create_index('mainsequence_markets_positionset_account_targe_3dca59123e7a_idx', 'mt_033bee86849649f887a4df1e6c30f1eb', ['account_target_portfolio_uid'], unique=False, schema='public')
    op.create_index('mainsequence_markets_positionset_position_set_d440f173de16_idx', 'mt_033bee86849649f887a4df1e6c30f1eb', ['position_set_time'], unique=False, schema='public')
    op.create_table('mt_23348db1defd4387b89e280c5ab3261b',
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.Column('account_uid', sa.Uuid(), nullable=False),
    sa.Column('asset_identifier', sa.String(length=255), nullable=False),
    sa.Column('holdings_set_uid', sa.Uuid(), nullable=False),
    sa.Column('is_trade_snapshot', sa.Boolean(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('direction', sa.SmallInteger(), nullable=False),
    sa.Column('target_trade_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint('direction IN (1, -1)', name='ck_account_holdings_direction'),
    sa.ForeignKeyConstraint(['account_uid'], ['public.mt_be93811e3458480189f1c7257f2fd8f2.uid'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['asset_identifier'], ['public.mt_14002912f31b47e7a303f1cd1109d0cb.unique_identifier'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['holdings_set_uid'], ['public.mt_55f3c12a219a4cdda0530e0be6380c18.uid'], ondelete='CASCADE'),
    schema='public',
    info={'mainsequence_storage_hash': 'mt_mainsequence_examples_32e10edb5c49f4ad0d3f6d1c87f4c7f0', 'mainsequence_logical_fullname': 'public.mt_mainsequence_examples_32e10edb5c49f4ad0d3f6d1c87f4c7f0'}
    )
    op.create_table('mt_508eda3f32974f398d30446e95e98c82',
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.Column('curve_identifier', sa.String(length=255), nullable=False),
    sa.Column('curve', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['curve_identifier'], ['public.mt_7fbd7b692050434bbcbf4773aa77a119.unique_identifier'], ondelete='RESTRICT'),
    schema='public',
    info={'mainsequence_storage_hash': 'mt_mainsequence_examples_a45b9fd38ac6dd882de6afe82f329125', 'mainsequence_logical_fullname': 'public.mt_mainsequence_examples_a45b9fd38ac6dd882de6afe82f329125'}
    )
    op.create_table('mt_bc5eb36d9fc94853a7b7016fd4e88b3b',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('virtual_fund_uid', sa.Uuid(), nullable=False),
    sa.Column('source_account_holdings_set_uid', sa.Uuid(), nullable=False),
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_account_holdings_set_uid'], ['public.mt_55f3c12a219a4cdda0530e0be6380c18.uid'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['virtual_fund_uid'], ['public.mt_0b71934a2b78437f9ef72733987ab46b.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.VirtualFundHoldingsSet', 'mainsequence_storage_hash': 'mt_mainsequence_examples_23ce80783d1adbdb7bcbf4c62a56e6f7', 'mainsequence_logical_fullname': 'public.mt_mainsequence_examples_23ce80783d1adbdb7bcbf4c62a56e6f7'}
    )
    op.create_index('mainsequence_markets_virtualfundholdingsset_so_74636a7f9c1f_idx', 'mt_bc5eb36d9fc94853a7b7016fd4e88b3b', ['source_account_holdings_set_uid'], unique=False, schema='public')
    op.create_index('mainsequence_markets_virtualfundholdingsset_v_c55b6e8d8b87_uidx', 'mt_bc5eb36d9fc94853a7b7016fd4e88b3b', ['virtual_fund_uid', 'source_account_holdings_set_uid'], unique=True, schema='public')
    op.create_index('mainsequence_markets_virtualfundholdingsset_vi_29503ff2ad1b_idx', 'mt_bc5eb36d9fc94853a7b7016fd4e88b3b', ['virtual_fund_uid'], unique=False, schema='public')
    op.create_table('mt_d2d4edee3c064ac9ac6a6bafea51a6da',
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.Column('virtual_fund_uid', sa.Uuid(), nullable=False),
    sa.Column('asset_identifier', sa.String(length=255), nullable=False),
    sa.Column('virtual_fund_holdings_set_uid', sa.Uuid(), nullable=False),
    sa.Column('source_account_holdings_set_uid', sa.Uuid(), nullable=False),
    sa.Column('allocated_quantity', sa.Float(), nullable=False),
    sa.Column('direction', sa.SmallInteger(), nullable=False),
    sa.Column('target_trade_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint('direction IN (1, -1)', name='ck_virtual_fund_holdings_direction'),
    sa.ForeignKeyConstraint(['asset_identifier'], ['public.mt_14002912f31b47e7a303f1cd1109d0cb.unique_identifier'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_account_holdings_set_uid'], ['public.mt_55f3c12a219a4cdda0530e0be6380c18.uid'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['virtual_fund_holdings_set_uid'], ['public.mt_bc5eb36d9fc94853a7b7016fd4e88b3b.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['virtual_fund_uid'], ['public.mt_0b71934a2b78437f9ef72733987ab46b.uid'], ondelete='CASCADE'),
    schema='public',
    info={'mainsequence_storage_hash': 'mt_mainsequence_examples_8610c72fa969b72270515709a07a6465', 'mainsequence_logical_fullname': 'public.mt_mainsequence_examples_8610c72fa969b72270515709a07a6465'}
    )
    op.create_table('mt_ff6589d1f2064d4fb3e71b755e71e9a4',
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.Column('position_set_uid', sa.Uuid(), nullable=False),
    sa.Column('asset_identifier', sa.String(), nullable=False),
    sa.Column('weight_notional_exposure', sa.Float(), nullable=True),
    sa.Column('constant_notional_exposure', sa.Float(), nullable=True),
    sa.Column('single_asset_quantity', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['asset_identifier'], ['public.mt_14002912f31b47e7a303f1cd1109d0cb.unique_identifier'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['position_set_uid'], ['public.mt_033bee86849649f887a4df1e6c30f1eb.uid'], ondelete='CASCADE'),
    schema='public',
    info={'mainsequence_storage_hash': 'mt_mainsequence_examples_64eb4cf9b5a50c05e5da107caaeb17e0', 'mainsequence_logical_fullname': 'public.mt_mainsequence_examples_64eb4cf9b5a50c05e5da107caaeb17e0'}
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mt_ff6589d1f2064d4fb3e71b755e71e9a4', schema='public')
    op.drop_table('mt_d2d4edee3c064ac9ac6a6bafea51a6da', schema='public')
    op.drop_index('mainsequence_markets_virtualfundholdingsset_vi_29503ff2ad1b_idx', table_name='mt_bc5eb36d9fc94853a7b7016fd4e88b3b', schema='public')
    op.drop_index('mainsequence_markets_virtualfundholdingsset_v_c55b6e8d8b87_uidx', table_name='mt_bc5eb36d9fc94853a7b7016fd4e88b3b', schema='public')
    op.drop_index('mainsequence_markets_virtualfundholdingsset_so_74636a7f9c1f_idx', table_name='mt_bc5eb36d9fc94853a7b7016fd4e88b3b', schema='public')
    op.drop_table('mt_bc5eb36d9fc94853a7b7016fd4e88b3b', schema='public')
    op.drop_table('mt_508eda3f32974f398d30446e95e98c82', schema='public')
    op.drop_table('mt_23348db1defd4387b89e280c5ab3261b', schema='public')
    op.drop_index('mainsequence_markets_positionset_position_set_d440f173de16_idx', table_name='mt_033bee86849649f887a4df1e6c30f1eb', schema='public')
    op.drop_index('mainsequence_markets_positionset_account_targe_3dca59123e7a_idx', table_name='mt_033bee86849649f887a4df1e6c30f1eb', schema='public')
    op.drop_index('mainsequence_markets_positionset_account_targ_4d4d735f97d5_uidx', table_name='mt_033bee86849649f887a4df1e6c30f1eb', schema='public')
    op.drop_table('mt_033bee86849649f887a4df1e6c30f1eb', schema='public')
    op.drop_index('mainsequence_markets_ordermanager_unique_iden_10c12424f694_uidx', table_name='mt_a2bd3f4067f34df5967629228f36b4b4', schema='public')
    op.drop_index('mainsequence_markets_ordermanager_target_accou_09d760f6b6e7_idx', table_name='mt_a2bd3f4067f34df5967629228f36b4b4', schema='public')
    op.drop_index('mainsequence_markets_ordermanager_status_6084fa71dc55_idx', table_name='mt_a2bd3f4067f34df5967629228f36b4b4', schema='public')
    op.drop_table('mt_a2bd3f4067f34df5967629228f36b4b4', schema='public')
    op.drop_index('mainsequence_markets_curve_unique_identifier_41f0a21bd7bd_uidx', table_name='mt_7fbd7b692050434bbcbf4773aa77a119', schema='public')
    op.drop_index('mainsequence_markets_curve_source_340195c5e17b_idx', table_name='mt_7fbd7b692050434bbcbf4773aa77a119', schema='public')
    op.drop_index('mainsequence_markets_curve_index_uid_72b6b940da59_idx', table_name='mt_7fbd7b692050434bbcbf4773aa77a119', schema='public')
    op.drop_index('mainsequence_markets_curve_curve_type_a782179014d2_idx', table_name='mt_7fbd7b692050434bbcbf4773aa77a119', schema='public')
    op.drop_table('mt_7fbd7b692050434bbcbf4773aa77a119', schema='public')
    op.drop_index('mainsequence_markets_accountholdingsset_time_i_620100c08dfb_idx', table_name='mt_55f3c12a219a4cdda0530e0be6380c18', schema='public')
    op.drop_index('mainsequence_markets_accountholdingsset_accoun_7d56f1117a13_idx', table_name='mt_55f3c12a219a4cdda0530e0be6380c18', schema='public')
    op.drop_index('mainsequence_markets_accountholdingsset_accou_6223c5e2529f_uidx', table_name='mt_55f3c12a219a4cdda0530e0be6380c18', schema='public')
    op.drop_table('mt_55f3c12a219a4cdda0530e0be6380c18', schema='public')
    op.drop_index('mainsequence_markets_accounttargetportfolio_u_c99890b9966b_uidx', table_name='mt_3b3990a0b7b540419d7b38c292aaa5de', schema='public')
    op.drop_index('mainsequence_markets_accounttargetportfolio_is_2296e36b784f_idx', table_name='mt_3b3990a0b7b540419d7b38c292aaa5de', schema='public')
    op.drop_index('mainsequence_markets_accounttargetportfolio_ac_5c78e3b77b7a_idx', table_name='mt_3b3990a0b7b540419d7b38c292aaa5de', schema='public')
    op.drop_index('mainsequence_markets_accounttargetportfolio_ac_2e2d71d32399_idx', table_name='mt_3b3990a0b7b540419d7b38c292aaa5de', schema='public')
    op.drop_table('mt_3b3990a0b7b540419d7b38c292aaa5de', schema='public')
    op.drop_index('mainsequence_markets_virtualfund_unique_ident_992c1b584486_uidx', table_name='mt_0b71934a2b78437f9ef72733987ab46b', schema='public')
    op.drop_index('mainsequence_markets_virtualfund_target_portfo_9388efa3e017_idx', table_name='mt_0b71934a2b78437f9ef72733987ab46b', schema='public')
    op.drop_index('mainsequence_markets_virtualfund_account_uid_3aff03fdd331_idx', table_name='mt_0b71934a2b78437f9ef72733987ab46b', schema='public')
    op.drop_table('mt_0b71934a2b78437f9ef72733987ab46b', schema='public')
    op.drop_index('mainsequence_markets_assetcategorymembership_a_3cb052aeb282_idx', table_name='mt_f81a09f6c9be482e921cf0e280a25d58', schema='public')
    op.drop_index('mainsequence_markets_assetcategorymembership_598eb8470799_uidx', table_name='mt_f81a09f6c9be482e921cf0e280a25d58', schema='public')
    op.drop_table('mt_f81a09f6c9be482e921cf0e280a25d58', schema='public')
    op.drop_index('mainsequence_markets_assetcurrentpricingdetail_88814219e287_idx', table_name='mt_dca2ed44cae541a6880d7e9e2866dfe4', schema='public')
    op.drop_index('mainsequence_markets_assetcurrentpricingdetail_2284f555148b_idx', table_name='mt_dca2ed44cae541a6880d7e9e2866dfe4', schema='public')
    op.drop_table('mt_dca2ed44cae541a6880d7e9e2866dfe4', schema='public')
    op.drop_index('mainsequence_markets_futureassetdetails_underl_34d349a490f1_idx', table_name='mt_dc1e819a482a410686718ce3a35e183a', schema='public')
    op.drop_index('mainsequence_markets_futureassetdetails_settle_1c5aae3036c0_idx', table_name='mt_dc1e819a482a410686718ce3a35e183a', schema='public')
    op.drop_index('mainsequence_markets_futureassetdetails_margin_ae85056e76be_idx', table_name='mt_dc1e819a482a410686718ce3a35e183a', schema='public')
    op.drop_index('mainsequence_markets_futureassetdetails_expire_65ca9d5e687f_idx', table_name='mt_dc1e819a482a410686718ce3a35e183a', schema='public')
    op.drop_table('mt_dc1e819a482a410686718ce3a35e183a', schema='public')
    op.drop_table('mt_da500bedbbb64b5dbc14f07769911ea4', schema='public')
    op.drop_index('mainsequence_markets_indexconventiondetails_so_0199939d9106_idx', table_name='mt_c33871b6f74d4084b97980d91c39522a', schema='public')
    op.drop_index('mainsequence_markets_indexconventiondetails_in_f9242e15a176_idx', table_name='mt_c33871b6f74d4084b97980d91c39522a', schema='public')
    op.drop_table('mt_c33871b6f74d4084b97980d91c39522a', schema='public')
    op.drop_index('mainsequence_markets_account_unique_identifie_2b66a4111f93_uidx', table_name='mt_be93811e3458480189f1c7257f2fd8f2', schema='public')
    op.drop_index('mainsequence_markets_account_account_name_c13dad2efec0_idx', table_name='mt_be93811e3458480189f1c7257f2fd8f2', schema='public')
    op.drop_index('mainsequence_markets_account_account_is_active_c71a4fc46ef7_idx', table_name='mt_be93811e3458480189f1c7257f2fd8f2', schema='public')
    op.drop_index('mainsequence_markets_account_account_group_uid_ad0cf18059d8_idx', table_name='mt_be93811e3458480189f1c7257f2fd8f2', schema='public')
    op.drop_table('mt_be93811e3458480189f1c7257f2fd8f2', schema='public')
    op.drop_index('mainsequence_markets_currencyspotassetdetails_9cf63880c07c_uidx', table_name='mt_b744298b10414385bc8d646a8e6c2d02', schema='public')
    op.drop_index('mainsequence_markets_currencyspotassetdetails_94457ff301ee_idx', table_name='mt_b744298b10414385bc8d646a8e6c2d02', schema='public')
    op.drop_index('mainsequence_markets_currencyspotassetdetails_7b5b579c2629_idx', table_name='mt_b744298b10414385bc8d646a8e6c2d02', schema='public')
    op.drop_table('mt_b744298b10414385bc8d646a8e6c2d02', schema='public')
    op.drop_table('mt_a21caf90a6844e6483c8d4afbce5da14', schema='public')
    op.drop_index('mainsequence_markets_bondassetdetails_status_15d1ff1dc071_idx', table_name='mt_795e3251a2b14ec385ad62351df7a629', schema='public')
    op.drop_index('mainsequence_markets_bondassetdetails_maturity_1b3594abaeae_idx', table_name='mt_795e3251a2b14ec385ad62351df7a629', schema='public')
    op.drop_index('mainsequence_markets_bondassetdetails_issuer_u_f9a3e2bb287d_idx', table_name='mt_795e3251a2b14ec385ad62351df7a629', schema='public')
    op.drop_index('mainsequence_markets_bondassetdetails_currency_353c9c596e3d_idx', table_name='mt_795e3251a2b14ec385ad62351df7a629', schema='public')
    op.drop_table('mt_795e3251a2b14ec385ad62351df7a629', schema='public')
    op.drop_index('mainsequence_markets_portfolio_unique_identif_fe802aa8a17c_uidx', table_name='mt_557ec35c90754a60884eed1a3c05c9cc', schema='public')
    op.drop_index('mainsequence_markets_portfolio_portfolio_index_3c67a6ed89bd_idx', table_name='mt_557ec35c90754a60884eed1a3c05c9cc', schema='public')
    op.drop_index('mainsequence_markets_portfolio_calendar_name_d913666549aa_idx', table_name='mt_557ec35c90754a60884eed1a3c05c9cc', schema='public')
    op.drop_table('mt_557ec35c90754a60884eed1a3c05c9cc', schema='public')
    op.drop_index('mainsequence_markets_openfigiassetdetails_tick_7fecd72d69d4_idx', table_name='mt_3e4c46a3f4264224b973a8248adb97c0', schema='public')
    op.drop_index('mainsequence_markets_openfigiassetdetails_isin_d5a68ba5375d_idx', table_name='mt_3e4c46a3f4264224b973a8248adb97c0', schema='public')
    op.drop_index('mainsequence_markets_openfigiassetdetails_figi_d89cb43a3d26_idx', table_name='mt_3e4c46a3f4264224b973a8248adb97c0', schema='public')
    op.drop_table('mt_3e4c46a3f4264224b973a8248adb97c0', schema='public')
    op.drop_table('mt_02d5a3353dc247a1a2e94ab22dabfde6', schema='public')
    op.drop_index('mainsequence_markets_marketsmetatablecatalog_ab388359ccb8_uidx', table_name='mt_f275cc1268034d31ad0d8b585fcaf794', schema='public')
    op.drop_index('mainsequence_markets_marketsmetatablecatalog_22914510666e_uidx', table_name='mt_f275cc1268034d31ad0d8b585fcaf794', schema='public')
    op.drop_table('mt_f275cc1268034d31ad0d8b585fcaf794', schema='public')
    op.drop_table('mt_ee7aa658a6c647ccba01db68ef999e8c', schema='public')
    op.drop_table('mt_ecd56882aa99452ea1e1409ec0021a1d', schema='public')
    op.drop_table('mt_eadf9318c6574bf6bd837c6004cf84bb', schema='public')
    op.drop_index('mainsequence_markets_signalmetadata_signal_ui_549a26971d9f_uidx', table_name='mt_aa8bd61f07bb49bbb873b45443ee6925', schema='public')
    op.drop_table('mt_aa8bd61f07bb49bbb873b45443ee6925', schema='public')
    op.drop_index('mainsequence_markets_accountmodelportfolio_mo_f3712daf1e44_uidx', table_name='mt_aa110877fa6a4b4d9d289aa82ce8d818', schema='public')
    op.drop_table('mt_aa110877fa6a4b4d9d289aa82ce8d818', schema='public')
    op.drop_index('mainsequence_markets_portfoliometadata_unique_b2ec62679586_uidx', table_name='mt_a4f2919a0a1c44b684a74858ea9f10f7', schema='public')
    op.drop_table('mt_a4f2919a0a1c44b684a74858ea9f10f7', schema='public')
    op.drop_index('mainsequence_markets_pricingmarketdatabinding_f3efd96b076c_idx', table_name='mt_8b543e69562a4034a771ae20485c900c', schema='public')
    op.drop_index('mainsequence_markets_pricingmarketdatabinding_a274af579c0a_idx', table_name='mt_8b543e69562a4034a771ae20485c900c', schema='public')
    op.drop_index('mainsequence_markets_pricingmarketdatabinding_44f925bee7e9_uidx', table_name='mt_8b543e69562a4034a771ae20485c900c', schema='public')
    op.drop_table('mt_8b543e69562a4034a771ae20485c900c', schema='public')
    op.drop_index('mainsequence_markets_accountgroup_group_name_e1ca0e2e9d5c_uidx', table_name='mt_8b295571395b43258e1f584bb4901bd8', schema='public')
    op.drop_table('mt_8b295571395b43258e1f584bb4901bd8', schema='public')
    op.drop_index('mainsequence_markets_indextype_index_type_2bb910756bb5_uidx', table_name='mt_8ab497ed69b3436692f4f3dc28afa4e5', schema='public')
    op.drop_index('mainsequence_markets_indextype_display_name_99dbb0273fca_idx', table_name='mt_8ab497ed69b3436692f4f3dc28afa4e5', schema='public')
    op.drop_table('mt_8ab497ed69b3436692f4f3dc28afa4e5', schema='public')
    op.drop_index('mainsequence_markets_assetcategory_unique_ide_dddb40d0bb7f_uidx', table_name='mt_80600ce04a6244dfb17c3d5cf91ac8bc', schema='public')
    op.drop_index('mainsequence_markets_assetcategory_display_nam_77c0d81c54c3_idx', table_name='mt_80600ce04a6244dfb17c3d5cf91ac8bc', schema='public')
    op.drop_table('mt_80600ce04a6244dfb17c3d5cf91ac8bc', schema='public')
    op.drop_index('mainsequence_markets_assettype_display_name_b40eb3745423_idx', table_name='mt_7d68a5e0801c4f19b374c68ed5e0d357', schema='public')
    op.drop_index('mainsequence_markets_assettype_asset_type_731d1b0f09e0_uidx', table_name='mt_7d68a5e0801c4f19b374c68ed5e0d357', schema='public')
    op.drop_table('mt_7d68a5e0801c4f19b374c68ed5e0d357', schema='public')
    op.drop_index('mainsequence_markets_issuer_unique_identifier_30d32ed3e3cf_uidx', table_name='mt_79a458eb5ba6489d879b518bee94308b', schema='public')
    op.drop_index('mainsequence_markets_issuer_display_name_51a8cff56856_idx', table_name='mt_79a458eb5ba6489d879b518bee94308b', schema='public')
    op.drop_table('mt_79a458eb5ba6489d879b518bee94308b', schema='public')
    op.drop_table('mt_79060f5b22ce467abb10612bda54d548', schema='public')
    op.drop_index('mainsequence_markets_calendar_name_9ea45889c249_uidx', table_name='mt_77efee4601ef4c2d8c21f9044df8c7e9', schema='public')
    op.drop_table('mt_77efee4601ef4c2d8c21f9044df8c7e9', schema='public')
    op.drop_index('mainsequence_markets_rebalancestrategymetadat_241d24df1f1b_uidx', table_name='mt_74818467794947c0ae0c7f4bd8d2c27a', schema='public')
    op.drop_table('mt_74818467794947c0ae0c7f4bd8d2c27a', schema='public')
    op.drop_index('mainsequence_markets_index_unique_identifier_120a08bbe6fc_uidx', table_name='mt_3b152b46b8ff4f8bb8314f01406771a2', schema='public')
    op.drop_index('mainsequence_markets_index_provider_bf4f42641d5c_idx', table_name='mt_3b152b46b8ff4f8bb8314f01406771a2', schema='public')
    op.drop_index('mainsequence_markets_index_index_type_8311e1de21c6_idx', table_name='mt_3b152b46b8ff4f8bb8314f01406771a2', schema='public')
    op.drop_index('mainsequence_markets_index_display_name_9579f6318f55_idx', table_name='mt_3b152b46b8ff4f8bb8314f01406771a2', schema='public')
    op.drop_table('mt_3b152b46b8ff4f8bb8314f01406771a2', schema='public')
    op.drop_table('mt_294010131ab64cb4a2b33c1ca20773e1', schema='public')
    op.drop_table('mt_21cf6aa7e4de453dada68396752fb7e7', schema='public')
    op.drop_table('mt_1ed1bc78d9694d1295b7d8992f451b98', schema='public')
    op.drop_index('mainsequence_markets_asset_unique_identifier_d5f133ca601c_uidx', table_name='mt_14002912f31b47e7a303f1cd1109d0cb', schema='public')
    op.drop_index('mainsequence_markets_asset_asset_type_684c5bc6a660_idx', table_name='mt_14002912f31b47e7a303f1cd1109d0cb', schema='public')
    op.drop_table('mt_14002912f31b47e7a303f1cd1109d0cb', schema='public')
    # ### end Alembic commands ###
