"""migration

Revision ID: 0001
Revises: 
Create Date: 2026-06-04 10:18:55.650008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ms_markets__accountgroup__mainsequence_examples',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('group_name', sa.String(length=100), nullable=True),
    sa.Column('group_description', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.AccountGroup'}
    )
    op.create_index(op.f('ix_public_ms_markets__accountgroup__mainsequence_examples_group_name'), 'ms_markets__accountgroup__mainsequence_examples', ['group_name'], unique=True, schema='public')
    op.create_table('ms_markets__accountmodelportfolio__mainsequence_examples',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('model_portfolio_name', sa.String(length=100), nullable=False),
    sa.Column('model_portfolio_description', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.AccountModelPortfolio'}
    )
    op.create_index(op.f('ix_public_ms_markets__accountmodelportfolio__mainsequence_examples_model_portfolio_name'), 'ms_markets__accountmodelportfolio__mainsequence_examples', ['model_portfolio_name'], unique=True, schema='public')
    op.create_table('ms_markets__asset__mainsequence_examples',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('unique_identifier', sa.String(length=255), nullable=False),
    sa.Column('asset_type', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.Asset'}
    )
    op.create_index(op.f('ix_public_ms_markets__asset__mainsequence_examples_asset_type'), 'ms_markets__asset__mainsequence_examples', ['asset_type'], unique=False, schema='public')
    op.create_index(op.f('ix_public_ms_markets__asset__mainsequence_examples_unique_identifier'), 'ms_markets__asset__mainsequence_examples', ['unique_identifier'], unique=True, schema='public')
    op.create_table('ms_markets__assetcategory__mainsequence_examples',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('unique_identifier', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.AssetCategory'}
    )
    op.create_index(op.f('ix_public_ms_markets__assetcategory__mainsequence_examples_display_name'), 'ms_markets__assetcategory__mainsequence_examples', ['display_name'], unique=False, schema='public')
    op.create_index(op.f('ix_public_ms_markets__assetcategory__mainsequence_examples_unique_identifier'), 'ms_markets__assetcategory__mainsequence_examples', ['unique_identifier'], unique=True, schema='public')
    op.create_table('ms_markets__assettype__mainsequence_examples',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('asset_type', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.AssetType'}
    )
    op.create_index(op.f('ix_public_ms_markets__assettype__mainsequence_examples_display_name'), 'ms_markets__assettype__mainsequence_examples', ['display_name'], unique=False, schema='public')
    op.create_index(op.f('ix_public_ms_markets__assettype__mainsequence_examples_asset_type'), 'ms_markets__assettype__mainsequence_examples', ['asset_type'], unique=True, schema='public')
    op.create_table('ms_markets__calendar__mainsequence_examples',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('calendar_dates', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.Calendar'}
    )
    op.create_index(op.f('ix_public_ms_markets__calendar__mainsequence_examples_name'), 'ms_markets__calendar__mainsequence_examples', ['name'], unique=True, schema='public')
    op.create_table('ms_markets__index__mainsequence_examples',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('unique_identifier', sa.String(length=255), nullable=False),
    sa.Column('index_type', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.Index'}
    )
    op.create_index(op.f('ix_public_ms_markets__index__mainsequence_examples_display_name'), 'ms_markets__index__mainsequence_examples', ['display_name'], unique=False, schema='public')
    op.create_index(op.f('ix_public_ms_markets__index__mainsequence_examples_index_type'), 'ms_markets__index__mainsequence_examples', ['index_type'], unique=False, schema='public')
    op.create_index(op.f('ix_public_ms_markets__index__mainsequence_examples_provider'), 'ms_markets__index__mainsequence_examples', ['provider'], unique=False, schema='public')
    op.create_index(op.f('ix_public_ms_markets__index__mainsequence_examples_unique_identifier'), 'ms_markets__index__mainsequence_examples', ['unique_identifier'], unique=True, schema='public')
    op.create_table('ms_markets__indextype__mainsequence_examples',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('index_type', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.IndexType'}
    )
    op.create_index(op.f('ix_public_ms_markets__indextype__mainsequence_examples_index_type'), 'ms_markets__indextype__mainsequence_examples', ['index_type'], unique=True, schema='public')
    op.create_index(op.f('ix_public_ms_markets__indextype__mainsequence_examples_display_name'), 'ms_markets__indextype__mainsequence_examples', ['display_name'], unique=False, schema='public')
    op.create_table('ms_markets__interpolatedpricests__mainsequence_examples',
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.Column('asset_identifier', sa.String(), nullable=False),
    sa.Column('open_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('trade_count', sa.Float(), nullable=True),
    sa.Column('vwap', sa.Float(), nullable=True),
    sa.Column('interpolated', sa.Boolean(), nullable=True),
    schema='public'
    )
    op.create_table('ms_markets__issuer__mainsequence_examples',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('unique_identifier', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.Issuer'}
    )
    op.create_index(op.f('ix_public_ms_markets__issuer__mainsequence_examples_display_name'), 'ms_markets__issuer__mainsequence_examples', ['display_name'], unique=False, schema='public')
    op.create_index(op.f('ix_public_ms_markets__issuer__mainsequence_examples_unique_identifier'), 'ms_markets__issuer__mainsequence_examples', ['unique_identifier'], unique=True, schema='public')
    op.create_table('ms_markets__marketsmetatablecatalog__mainsequence_examples',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('namespace', sa.String(length=255), nullable=False),
    sa.Column('table_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('meta_table_uid', sa.String(length=64), nullable=False),
    sa.Column('contract_hash', sa.String(length=64), nullable=False),
    sa.Column('sdk_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.MarketsMetaTableCatalog'}
    )
    op.create_index(op.f('ix_public_ms_markets__marketsmetatablecatalog__mainsequence_examples_meta_table_uid'), 'ms_markets__marketsmetatablecatalog__mainsequence_examples', ['meta_table_uid'], unique=True, schema='public')
    op.create_index(op.f('ix_public_ms_markets__marketsmetatablecatalog__mainsequence_examples_table_name'), 'ms_markets__marketsmetatablecatalog__mainsequence_examples', ['table_name'], unique=True, schema='public')
    op.create_table('ms_markets__ordereventsts__mainsequence_examples',
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('order_identifier', sa.String(), nullable=False),
    sa.Column('order_status', sa.String(), nullable=True),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    schema='public'
    )
    op.create_table('ms_markets__ordersts__mainsequence_examples',
    sa.Column('order_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('order_identifier', sa.String(), nullable=False),
    sa.Column('account_identifier', sa.String(), nullable=False),
    sa.Column('fund_identifier', sa.String(), nullable=True),
    sa.Column('order_manager_identifier', sa.String(), nullable=True),
    sa.Column('asset_identifier', sa.String(), nullable=False),
    sa.Column('order_remote_id', sa.String(), nullable=True),
    sa.Column('client_order_id', sa.String(), nullable=True),
    sa.Column('order_type', sa.String(), nullable=True),
    sa.Column('order_side', sa.BigInteger(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('filled_quantity', sa.Float(), nullable=True),
    sa.Column('filled_price', sa.Float(), nullable=True),
    sa.Column('expires_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('limit_price', sa.Float(), nullable=True),
    sa.Column('time_in_force', sa.String(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('venue_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    schema='public'
    )
    op.create_table('ms_markets__portfoliometadata__mainsequence_examples',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('unique_identifier', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.PortfolioMetadata'}
    )
    op.create_index(op.f('ix_public_ms_markets__portfoliometadata__mainsequence_examples_unique_identifier'), 'ms_markets__portfoliometadata__mainsequence_examples', ['unique_identifier'], unique=True, schema='public')
    op.create_table('ms_markets__portfoliosts__mainsequence_examples',
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.Column('portfolio_identifier', sa.String(), nullable=False),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('return', sa.Float(), nullable=True),
    sa.Column('calculated_close', sa.Float(), nullable=True),
    sa.Column('close_time', sa.DateTime(timezone=True), nullable=True),
    schema='public'
    )
    op.create_table('ms_markets__portfolioweightsts__mainsequence_examples',
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.Column('portfolio_index_identifier', sa.String(), nullable=False),
    sa.Column('asset_identifier', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('weight_before', sa.Float(), nullable=True),
    sa.Column('price_current', sa.Float(), nullable=True),
    sa.Column('price_before', sa.Float(), nullable=True),
    sa.Column('volume_current', sa.Float(), nullable=True),
    sa.Column('volume_before', sa.Float(), nullable=True),
    schema='public'
    )
    op.create_table('ms_markets__pricingmarketdatabinding__mainsequence_examples',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('context_key', sa.String(length=64), nullable=False),
    sa.Column('concept_key', sa.String(length=128), nullable=False),
    sa.Column('data_node_identifier', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.PricingMarketDataBinding'}
    )
    op.create_index(op.f('ix_public_ms_markets__pricingmarketdatabinding__mainsequence_examples_context_key'), 'ms_markets__pricingmarketdatabinding__mainsequence_examples', ['context_key', 'concept_key'], unique=True, schema='public')
    op.create_index(op.f('ix_public_ms_markets__pricingmarketdatabinding__mainsequence_examples_concept_key'), 'ms_markets__pricingmarketdatabinding__mainsequence_examples', ['concept_key'], unique=False, schema='public')
    op.create_table('ms_markets__rebalancestrategymetadata__mainsequence_examples',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('rebalance_strategy_uid', sa.String(length=255), nullable=False),
    sa.Column('rebalance_strategy_description', sa.Text(), nullable=True),
    sa.Column('configuration_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.RebalanceStrategyMetadata'}
    )
    op.create_index(op.f('ix_public_ms_markets__rebalancestrategymetadata__mainsequence_examples_rebalance_strategy_uid'), 'ms_markets__rebalancestrategymetadata__mainsequence_examples', ['rebalance_strategy_uid'], unique=True, schema='public')
    op.create_table('ms_markets__signalmetadata__mainsequence_examples',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('signal_uid', sa.String(length=255), nullable=False),
    sa.Column('signal_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.SignalMetadata'}
    )
    op.create_index(op.f('ix_public_ms_markets__signalmetadata__mainsequence_examples_signal_uid'), 'ms_markets__signalmetadata__mainsequence_examples', ['signal_uid'], unique=True, schema='public')
    op.create_table('ms_markets__signalweightsts__mainsequence_examples',
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signal_uid', sa.String(), nullable=False),
    sa.Column('asset_identifier', sa.String(), nullable=False),
    sa.Column('signal_weight', sa.Float(), nullable=True),
    schema='public'
    )
    op.create_table('ms_markets__tradests__mainsequence_examples',
    sa.Column('trade_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trade_identifier', sa.String(), nullable=False),
    sa.Column('account_identifier', sa.String(), nullable=False),
    sa.Column('fund_identifier', sa.String(), nullable=True),
    sa.Column('order_identifier', sa.String(), nullable=True),
    sa.Column('asset_identifier', sa.String(), nullable=False),
    sa.Column('trade_side', sa.BigInteger(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('commission_asset_identifier', sa.String(), nullable=True),
    sa.Column('settlement_cost', sa.Float(), nullable=True),
    sa.Column('settlement_asset_identifier', sa.String(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('venue_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    schema='public'
    )
    op.create_table('ms_markets__account__mainsequence_examples',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('unique_identifier', sa.String(length=255), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('is_paper', sa.Boolean(), nullable=False),
    sa.Column('account_is_active', sa.Boolean(), nullable=False),
    sa.Column('account_group_uid', sa.Uuid(), nullable=True),
    sa.Column('holdings_data_node_uid', sa.Uuid(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['account_group_uid'], ['public.ms_markets__accountgroup__mainsequence_examples.uid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.Account'}
    )
    op.create_index(op.f('ix_public_ms_markets__account__mainsequence_examples_account_is_active'), 'ms_markets__account__mainsequence_examples', ['account_is_active'], unique=False, schema='public')
    op.create_index(op.f('ix_public_ms_markets__account__mainsequence_examples_account_group_uid'), 'ms_markets__account__mainsequence_examples', ['account_group_uid'], unique=False, schema='public')
    op.create_index(op.f('ix_public_ms_markets__account__mainsequence_examples_account_name'), 'ms_markets__account__mainsequence_examples', ['account_name'], unique=False, schema='public')
    op.create_index(op.f('ix_public_ms_markets__account__mainsequence_examples_unique_identifier'), 'ms_markets__account__mainsequence_examples', ['unique_identifier'], unique=True, schema='public')
    op.create_table('ms_markets__assetcategorymembership__mainsequence_examples',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('category_uid', sa.Uuid(), nullable=False),
    sa.Column('asset_uid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['asset_uid'], ['public.ms_markets__asset__mainsequence_examples.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_uid'], ['public.ms_markets__assetcategory__mainsequence_examples.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.AssetCategoryMembership'}
    )
    op.create_index(op.f('ix_public_ms_markets__assetcategorymembership__mainsequence_examples_category_uid'), 'ms_markets__assetcategorymembership__mainsequence_examples', ['category_uid', 'asset_uid'], unique=True, schema='public')
    op.create_index(op.f('ix_public_ms_markets__assetcategorymembership__mainsequence_examples_asset_uid'), 'ms_markets__assetcategorymembership__mainsequence_examples', ['asset_uid'], unique=False, schema='public')
    op.create_table('ms_markets__assetcurrentpricingdetails__mainsequence_examples',
    sa.Column('asset_uid', sa.Uuid(), nullable=False),
    sa.Column('instrument_type', sa.String(length=128), nullable=False),
    sa.Column('instrument_dump', sa.JSON(), nullable=False),
    sa.Column('pricing_details_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('serialization_format', sa.String(length=128), nullable=False),
    sa.Column('pricing_package_version', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['asset_uid'], ['public.ms_markets__asset__mainsequence_examples.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.AssetCurrentPricingDetails'}
    )
    op.create_index(op.f('ix_public_ms_markets__assetcurrentpricingdetails__mainsequence_examples_instrument_type'), 'ms_markets__assetcurrentpricingdetails__mainsequence_examples', ['instrument_type'], unique=False, schema='public')
    op.create_index(op.f('ix_public_ms_markets__assetcurrentpricingdetails__mainsequence_examples_pricing_details_date'), 'ms_markets__assetcurrentpricingdetails__mainsequence_examples', ['pricing_details_date'], unique=False, schema='public')
    op.create_table('ms_markets__assetpricingdetailsts__mainsequence_examples',
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.Column('asset_identifier', sa.String(length=255), nullable=False),
    sa.Column('instrument_dump', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['asset_identifier'], ['public.ms_markets__asset__mainsequence_examples.unique_identifier'], ondelete='RESTRICT'),
    schema='public'
    )
    op.create_table('ms_markets__assetsnapshotsts__mainsequence_examples',
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.Column('asset_identifier', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('exchange_code', sa.String(), nullable=True),
    sa.Column('asset_ticker_group_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['asset_identifier'], ['public.ms_markets__asset__mainsequence_examples.unique_identifier'], ondelete='RESTRICT'),
    schema='public'
    )
    op.create_table('ms_markets__bondassetdetails__mainsequence_examples',
    sa.Column('asset_uid', sa.Uuid(), nullable=False),
    sa.Column('issuer_uid', sa.Uuid(), nullable=False),
    sa.Column('currency_asset_uid', sa.Uuid(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['asset_uid'], ['public.ms_markets__asset__mainsequence_examples.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['currency_asset_uid'], ['public.ms_markets__asset__mainsequence_examples.uid'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['issuer_uid'], ['public.ms_markets__issuer__mainsequence_examples.uid'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('asset_uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.BondAssetDetails'}
    )
    op.create_index(op.f('ix_public_ms_markets__bondassetdetails__mainsequence_examples_maturity_date'), 'ms_markets__bondassetdetails__mainsequence_examples', ['maturity_date'], unique=False, schema='public')
    op.create_index(op.f('ix_public_ms_markets__bondassetdetails__mainsequence_examples_status'), 'ms_markets__bondassetdetails__mainsequence_examples', ['status'], unique=False, schema='public')
    op.create_index(op.f('ix_public_ms_markets__bondassetdetails__mainsequence_examples_issuer_uid'), 'ms_markets__bondassetdetails__mainsequence_examples', ['issuer_uid'], unique=False, schema='public')
    op.create_index(op.f('ix_public_ms_markets__bondassetdetails__mainsequence_examples_currency_asset_uid'), 'ms_markets__bondassetdetails__mainsequence_examples', ['currency_asset_uid'], unique=False, schema='public')
    op.create_table('ms_markets__currencyspotassetdetails__mainsequence_examples',
    sa.Column('asset_uid', sa.Uuid(), nullable=False),
    sa.Column('base_currency_uid', sa.Uuid(), nullable=False),
    sa.Column('quote_currency_uid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['asset_uid'], ['public.ms_markets__asset__mainsequence_examples.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['base_currency_uid'], ['public.ms_markets__asset__mainsequence_examples.uid'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['quote_currency_uid'], ['public.ms_markets__asset__mainsequence_examples.uid'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('asset_uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.CurrencySpotAssetDetails'}
    )
    op.create_index(op.f('ix_public_ms_markets__currencyspotassetdetails__mainsequence_examples_quote_currency_uid'), 'ms_markets__currencyspotassetdetails__mainsequence_examples', ['quote_currency_uid'], unique=False, schema='public')
    op.create_index(op.f('ix_public_ms_markets__currencyspotassetdetails__mainsequence_examples_base_currency_uid'), 'ms_markets__currencyspotassetdetails__mainsequence_examples', ['base_currency_uid'], unique=False, schema='public')
    op.create_table('ms_markets__futureassetdetails__mainsequence_examples',
    sa.Column('asset_uid', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('underlying_index_uid', sa.Uuid(), nullable=False),
    sa.Column('quote_unit', sa.String(length=64), nullable=False),
    sa.Column('settlement_asset', sa.Uuid(), nullable=False),
    sa.Column('margin_asset', sa.Uuid(), nullable=False),
    sa.Column('settlement_model', sa.String(length=32), nullable=False),
    sa.Column('settlement_method', sa.String(length=32), nullable=False),
    sa.Column('contract_size', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('contract_unit', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settles_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['asset_uid'], ['public.ms_markets__asset__mainsequence_examples.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['margin_asset'], ['public.ms_markets__asset__mainsequence_examples.uid'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['settlement_asset'], ['public.ms_markets__asset__mainsequence_examples.uid'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['underlying_index_uid'], ['public.ms_markets__index__mainsequence_examples.uid'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('asset_uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.FutureAssetDetails'}
    )
    op.create_index(op.f('ix_public_ms_markets__futureassetdetails__mainsequence_examples_settlement_asset'), 'ms_markets__futureassetdetails__mainsequence_examples', ['settlement_asset'], unique=False, schema='public')
    op.create_index(op.f('ix_public_ms_markets__futureassetdetails__mainsequence_examples_underlying_index_uid'), 'ms_markets__futureassetdetails__mainsequence_examples', ['underlying_index_uid'], unique=False, schema='public')
    op.create_index(op.f('ix_public_ms_markets__futureassetdetails__mainsequence_examples_margin_asset'), 'ms_markets__futureassetdetails__mainsequence_examples', ['margin_asset'], unique=False, schema='public')
    op.create_index(op.f('ix_public_ms_markets__futureassetdetails__mainsequence_examples_expires_at'), 'ms_markets__futureassetdetails__mainsequence_examples', ['expires_at'], unique=False, schema='public')
    op.create_table('ms_markets__indexconventiondetails__mainsequence_examples',
    sa.Column('index_uid', sa.Uuid(), nullable=False),
    sa.Column('index_family', sa.String(length=64), nullable=False),
    sa.Column('convention_dump', sa.JSON(), nullable=False),
    sa.Column('serialization_format', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['index_uid'], ['public.ms_markets__index__mainsequence_examples.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('index_uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.IndexConventionDetails'}
    )
    op.create_index(op.f('ix_public_ms_markets__indexconventiondetails__mainsequence_examples_source'), 'ms_markets__indexconventiondetails__mainsequence_examples', ['source'], unique=False, schema='public')
    op.create_index(op.f('ix_public_ms_markets__indexconventiondetails__mainsequence_examples_index_family'), 'ms_markets__indexconventiondetails__mainsequence_examples', ['index_family'], unique=False, schema='public')
    op.create_table('ms_markets__indexfixingsts__mainsequence_examples',
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.Column('index_identifier', sa.String(length=255), nullable=False),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['index_identifier'], ['public.ms_markets__index__mainsequence_examples.unique_identifier'], ondelete='RESTRICT'),
    schema='public'
    )
    op.create_table('ms_markets__openfigiassetdetails__mainsequence_examples',
    sa.Column('asset_uid', sa.Uuid(), nullable=False),
    sa.Column('figi', sa.String(length=12), nullable=True),
    sa.Column('composite', sa.String(length=12), nullable=True),
    sa.Column('share_class', sa.String(length=12), nullable=True),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('ticker', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('exchange_code', sa.String(length=50), nullable=True),
    sa.Column('security_type', sa.String(length=50), nullable=True),
    sa.Column('security_type_2', sa.String(length=50), nullable=True),
    sa.Column('security_market_sector', sa.String(length=50), nullable=True),
    sa.Column('security_description', sa.String(length=255), nullable=True),
    sa.Column('unique_id', sa.String(length=255), nullable=True),
    sa.Column('unique_id_fut_opt', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['asset_uid'], ['public.ms_markets__asset__mainsequence_examples.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.OpenFigiAssetDetails'}
    )
    op.create_index(op.f('ix_public_ms_markets__openfigiassetdetails__mainsequence_examples_figi'), 'ms_markets__openfigiassetdetails__mainsequence_examples', ['figi'], unique=False, schema='public')
    op.create_index(op.f('ix_public_ms_markets__openfigiassetdetails__mainsequence_examples_ticker'), 'ms_markets__openfigiassetdetails__mainsequence_examples', ['ticker'], unique=False, schema='public')
    op.create_index(op.f('ix_public_ms_markets__openfigiassetdetails__mainsequence_examples_isin'), 'ms_markets__openfigiassetdetails__mainsequence_examples', ['isin'], unique=False, schema='public')
    op.create_table('ms_markets__portfolio__mainsequence_examples',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('unique_identifier', sa.String(length=255), nullable=False),
    sa.Column('calendar_name', sa.String(length=255), nullable=True),
    sa.Column('portfolio_index_uid', sa.Uuid(), nullable=True),
    sa.Column('portfolio_weights_data_node_uid', sa.Uuid(), nullable=True),
    sa.Column('signal_weights_data_node_uid', sa.Uuid(), nullable=True),
    sa.Column('portfolio_data_node_uid', sa.Uuid(), nullable=True),
    sa.Column('backtest_table_price_column_name', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_index_uid'], ['public.ms_markets__index__mainsequence_examples.uid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.Portfolio'}
    )
    op.create_index(op.f('ix_public_ms_markets__portfolio__mainsequence_examples_unique_identifier'), 'ms_markets__portfolio__mainsequence_examples', ['unique_identifier'], unique=True, schema='public')
    op.create_index(op.f('ix_public_ms_markets__portfolio__mainsequence_examples_portfolio_index_uid'), 'ms_markets__portfolio__mainsequence_examples', ['portfolio_index_uid'], unique=False, schema='public')
    op.create_index(op.f('ix_public_ms_markets__portfolio__mainsequence_examples_calendar_name'), 'ms_markets__portfolio__mainsequence_examples', ['calendar_name'], unique=False, schema='public')
    op.create_table('ms_markets__accountholdingsset__mainsequence_examples',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('account_uid', sa.Uuid(), nullable=False),
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_data_node_uid', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['account_uid'], ['public.ms_markets__account__mainsequence_examples.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.AccountHoldingsSet'}
    )
    op.create_index(op.f('ix_public_ms_markets__accountholdingsset__mainsequence_examples_account_uid'), 'ms_markets__accountholdingsset__mainsequence_examples', ['account_uid'], unique=False, schema='public')
    op.create_index(op.f('ix_public_ms_markets__accountholdingsset__mainsequence_examples_time_index'), 'ms_markets__accountholdingsset__mainsequence_examples', ['time_index'], unique=False, schema='public')
    op.create_table('ms_markets__accounttargetportfolio__mainsequence_examples',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('unique_identifier', sa.String(length=255), nullable=False),
    sa.Column('account_uid', sa.Uuid(), nullable=False),
    sa.Column('account_model_portfolio_uid', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['account_model_portfolio_uid'], ['public.ms_markets__accountmodelportfolio__mainsequence_examples.uid'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['account_uid'], ['public.ms_markets__account__mainsequence_examples.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.AccountTargetPortfolio'}
    )
    op.create_index(op.f('ix_public_ms_markets__accounttargetportfolio__mainsequence_examples_account_uid'), 'ms_markets__accounttargetportfolio__mainsequence_examples', ['account_uid'], unique=False, schema='public')
    op.create_index(op.f('ix_public_ms_markets__accounttargetportfolio__mainsequence_examples_is_active'), 'ms_markets__accounttargetportfolio__mainsequence_examples', ['is_active'], unique=False, schema='public')
    op.create_index(op.f('ix_public_ms_markets__accounttargetportfolio__mainsequence_examples_unique_identifier'), 'ms_markets__accounttargetportfolio__mainsequence_examples', ['unique_identifier'], unique=True, schema='public')
    op.create_index(op.f('ix_public_ms_markets__accounttargetportfolio__mainsequence_examples_account_model_portfolio_uid'), 'ms_markets__accounttargetportfolio__mainsequence_examples', ['account_model_portfolio_uid'], unique=False, schema='public')
    op.create_table('ms_markets__curve__mainsequence_examples',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('unique_identifier', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('curve_type', sa.String(length=64), nullable=False),
    sa.Column('index_uid', sa.Uuid(), nullable=False),
    sa.Column('interpolation_method', sa.String(length=64), nullable=True),
    sa.Column('compounding', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['index_uid'], ['public.ms_markets__indexconventiondetails__mainsequence_examples.index_uid'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.Curve'}
    )
    op.create_index(op.f('ix_public_ms_markets__curve__mainsequence_examples_curve_type'), 'ms_markets__curve__mainsequence_examples', ['curve_type'], unique=False, schema='public')
    op.create_index(op.f('ix_public_ms_markets__curve__mainsequence_examples_index_uid'), 'ms_markets__curve__mainsequence_examples', ['index_uid'], unique=False, schema='public')
    op.create_index(op.f('ix_public_ms_markets__curve__mainsequence_examples_source'), 'ms_markets__curve__mainsequence_examples', ['source'], unique=False, schema='public')
    op.create_index(op.f('ix_public_ms_markets__curve__mainsequence_examples_unique_identifier'), 'ms_markets__curve__mainsequence_examples', ['unique_identifier'], unique=True, schema='public')
    op.create_table('ms_markets__ordermanager__mainsequence_examples',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('unique_identifier', sa.String(length=255), nullable=False),
    sa.Column('target_account_uid', sa.Uuid(), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('order_received_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['target_account_uid'], ['public.ms_markets__account__mainsequence_examples.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.OrderManager'}
    )
    op.create_index(op.f('ix_public_ms_markets__ordermanager__mainsequence_examples_target_account_uid'), 'ms_markets__ordermanager__mainsequence_examples', ['target_account_uid'], unique=False, schema='public')
    op.create_index(op.f('ix_public_ms_markets__ordermanager__mainsequence_examples_status'), 'ms_markets__ordermanager__mainsequence_examples', ['status'], unique=False, schema='public')
    op.create_index(op.f('ix_public_ms_markets__ordermanager__mainsequence_examples_unique_identifier'), 'ms_markets__ordermanager__mainsequence_examples', ['unique_identifier'], unique=True, schema='public')
    op.create_table('ms_markets__virtualfund__mainsequence_examples',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('unique_identifier', sa.String(length=255), nullable=False),
    sa.Column('account_uid', sa.Uuid(), nullable=False),
    sa.Column('target_portfolio_uid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['account_uid'], ['public.ms_markets__account__mainsequence_examples.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_portfolio_uid'], ['public.ms_markets__portfolio__mainsequence_examples.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.VirtualFund'}
    )
    op.create_index(op.f('ix_public_ms_markets__virtualfund__mainsequence_examples_unique_identifier'), 'ms_markets__virtualfund__mainsequence_examples', ['unique_identifier'], unique=True, schema='public')
    op.create_index(op.f('ix_public_ms_markets__virtualfund__mainsequence_examples_account_uid'), 'ms_markets__virtualfund__mainsequence_examples', ['account_uid'], unique=False, schema='public')
    op.create_index(op.f('ix_public_ms_markets__virtualfund__mainsequence_examples_target_portfolio_uid'), 'ms_markets__virtualfund__mainsequence_examples', ['target_portfolio_uid'], unique=False, schema='public')
    op.create_table('ms_markets__accountholdingsts__mainsequence_examples',
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.Column('account_uid', sa.Uuid(), nullable=False),
    sa.Column('asset_identifier', sa.String(length=255), nullable=False),
    sa.Column('holdings_set_uid', sa.Uuid(), nullable=False),
    sa.Column('is_trade_snapshot', sa.Boolean(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('direction', sa.SmallInteger(), nullable=False),
    sa.Column('target_trade_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint('direction IN (1, -1)', name='ck_account_holdings_direction'),
    sa.ForeignKeyConstraint(['account_uid'], ['public.ms_markets__account__mainsequence_examples.uid'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['asset_identifier'], ['public.ms_markets__asset__mainsequence_examples.unique_identifier'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['holdings_set_uid'], ['public.ms_markets__accountholdingsset__mainsequence_examples.uid'], ondelete='CASCADE'),
    schema='public'
    )
    op.create_table('ms_markets__discountcurvests__mainsequence_examples',
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.Column('curve_identifier', sa.String(length=255), nullable=False),
    sa.Column('curve', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['curve_identifier'], ['public.ms_markets__curve__mainsequence_examples.unique_identifier'], ondelete='RESTRICT'),
    schema='public'
    )
    op.create_table('ms_markets__positionset__mainsequence_examples',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('account_target_portfolio_uid', sa.Uuid(), nullable=False),
    sa.Column('position_set_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['account_target_portfolio_uid'], ['public.ms_markets__accounttargetportfolio__mainsequence_examples.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.PositionSet'}
    )
    op.create_index(op.f('ix_public_ms_markets__positionset__mainsequence_examples_account_target_portfolio_uid'), 'ms_markets__positionset__mainsequence_examples', ['account_target_portfolio_uid'], unique=False, schema='public')
    op.create_index(op.f('ix_public_ms_markets__positionset__mainsequence_examples_position_set_time'), 'ms_markets__positionset__mainsequence_examples', ['position_set_time'], unique=False, schema='public')
    op.create_table('ms_markets__virtualfundholdingsset__mainsequence_examples',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('virtual_fund_uid', sa.Uuid(), nullable=False),
    sa.Column('source_account_holdings_set_uid', sa.Uuid(), nullable=False),
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_account_holdings_set_uid'], ['public.ms_markets__accountholdingsset__mainsequence_examples.uid'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['virtual_fund_uid'], ['public.ms_markets__virtualfund__mainsequence_examples.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid'),
    schema='public',
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.VirtualFundHoldingsSet'}
    )
    op.create_index(op.f('ix_public_ms_markets__virtualfundholdingsset__mainsequence_examples_virtual_fund_uid'), 'ms_markets__virtualfundholdingsset__mainsequence_examples', ['virtual_fund_uid'], unique=False, schema='public')
    op.create_index(op.f('ix_public_ms_markets__virtualfundholdingsset__mainsequence_examples_source_account_holdings_set_uid'), 'ms_markets__virtualfundholdingsset__mainsequence_examples', ['source_account_holdings_set_uid'], unique=False, schema='public')
    op.create_table('ms_markets__targetpositionsts__mainsequence_examples',
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.Column('position_set_uid', sa.Uuid(), nullable=False),
    sa.Column('asset_identifier', sa.String(), nullable=False),
    sa.Column('weight_notional_exposure', sa.Float(), nullable=True),
    sa.Column('constant_notional_exposure', sa.Float(), nullable=True),
    sa.Column('single_asset_quantity', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['asset_identifier'], ['public.ms_markets__asset__mainsequence_examples.unique_identifier'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['position_set_uid'], ['public.ms_markets__positionset__mainsequence_examples.uid'], ondelete='CASCADE'),
    schema='public'
    )
    op.create_table('ms_markets__virtualfundholdingsts__mainsequence_examples',
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.Column('virtual_fund_uid', sa.Uuid(), nullable=False),
    sa.Column('asset_identifier', sa.String(length=255), nullable=False),
    sa.Column('virtual_fund_holdings_set_uid', sa.Uuid(), nullable=False),
    sa.Column('source_account_holdings_set_uid', sa.Uuid(), nullable=False),
    sa.Column('allocated_quantity', sa.Float(), nullable=False),
    sa.Column('direction', sa.SmallInteger(), nullable=False),
    sa.Column('target_trade_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint('direction IN (1, -1)', name='ck_virtual_fund_holdings_direction'),
    sa.ForeignKeyConstraint(['asset_identifier'], ['public.ms_markets__asset__mainsequence_examples.unique_identifier'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_account_holdings_set_uid'], ['public.ms_markets__accountholdingsset__mainsequence_examples.uid'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['virtual_fund_holdings_set_uid'], ['public.ms_markets__virtualfundholdingsset__mainsequence_examples.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['virtual_fund_uid'], ['public.ms_markets__virtualfund__mainsequence_examples.uid'], ondelete='CASCADE'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ms_markets__virtualfundholdingsts__mainsequence_examples', schema='public')
    op.drop_table('ms_markets__targetpositionsts__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__virtualfundholdingsset__mainsequence_examples_source_account_holdings_set_uid'), table_name='ms_markets__virtualfundholdingsset__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__virtualfundholdingsset__mainsequence_examples_virtual_fund_uid'), table_name='ms_markets__virtualfundholdingsset__mainsequence_examples', schema='public')
    op.drop_table('ms_markets__virtualfundholdingsset__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__positionset__mainsequence_examples_position_set_time'), table_name='ms_markets__positionset__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__positionset__mainsequence_examples_account_target_portfolio_uid'), table_name='ms_markets__positionset__mainsequence_examples', schema='public')
    op.drop_table('ms_markets__positionset__mainsequence_examples', schema='public')
    op.drop_table('ms_markets__discountcurvests__mainsequence_examples', schema='public')
    op.drop_table('ms_markets__accountholdingsts__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__virtualfund__mainsequence_examples_target_portfolio_uid'), table_name='ms_markets__virtualfund__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__virtualfund__mainsequence_examples_account_uid'), table_name='ms_markets__virtualfund__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__virtualfund__mainsequence_examples_unique_identifier'), table_name='ms_markets__virtualfund__mainsequence_examples', schema='public')
    op.drop_table('ms_markets__virtualfund__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__ordermanager__mainsequence_examples_unique_identifier'), table_name='ms_markets__ordermanager__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__ordermanager__mainsequence_examples_status'), table_name='ms_markets__ordermanager__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__ordermanager__mainsequence_examples_target_account_uid'), table_name='ms_markets__ordermanager__mainsequence_examples', schema='public')
    op.drop_table('ms_markets__ordermanager__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__curve__mainsequence_examples_unique_identifier'), table_name='ms_markets__curve__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__curve__mainsequence_examples_source'), table_name='ms_markets__curve__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__curve__mainsequence_examples_index_uid'), table_name='ms_markets__curve__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__curve__mainsequence_examples_curve_type'), table_name='ms_markets__curve__mainsequence_examples', schema='public')
    op.drop_table('ms_markets__curve__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__accounttargetportfolio__mainsequence_examples_account_model_portfolio_uid'), table_name='ms_markets__accounttargetportfolio__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__accounttargetportfolio__mainsequence_examples_unique_identifier'), table_name='ms_markets__accounttargetportfolio__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__accounttargetportfolio__mainsequence_examples_is_active'), table_name='ms_markets__accounttargetportfolio__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__accounttargetportfolio__mainsequence_examples_account_uid'), table_name='ms_markets__accounttargetportfolio__mainsequence_examples', schema='public')
    op.drop_table('ms_markets__accounttargetportfolio__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__accountholdingsset__mainsequence_examples_time_index'), table_name='ms_markets__accountholdingsset__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__accountholdingsset__mainsequence_examples_account_uid'), table_name='ms_markets__accountholdingsset__mainsequence_examples', schema='public')
    op.drop_table('ms_markets__accountholdingsset__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__portfolio__mainsequence_examples_calendar_name'), table_name='ms_markets__portfolio__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__portfolio__mainsequence_examples_portfolio_index_uid'), table_name='ms_markets__portfolio__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__portfolio__mainsequence_examples_unique_identifier'), table_name='ms_markets__portfolio__mainsequence_examples', schema='public')
    op.drop_table('ms_markets__portfolio__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__openfigiassetdetails__mainsequence_examples_isin'), table_name='ms_markets__openfigiassetdetails__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__openfigiassetdetails__mainsequence_examples_ticker'), table_name='ms_markets__openfigiassetdetails__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__openfigiassetdetails__mainsequence_examples_figi'), table_name='ms_markets__openfigiassetdetails__mainsequence_examples', schema='public')
    op.drop_table('ms_markets__openfigiassetdetails__mainsequence_examples', schema='public')
    op.drop_table('ms_markets__indexfixingsts__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__indexconventiondetails__mainsequence_examples_index_family'), table_name='ms_markets__indexconventiondetails__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__indexconventiondetails__mainsequence_examples_source'), table_name='ms_markets__indexconventiondetails__mainsequence_examples', schema='public')
    op.drop_table('ms_markets__indexconventiondetails__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__futureassetdetails__mainsequence_examples_expires_at'), table_name='ms_markets__futureassetdetails__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__futureassetdetails__mainsequence_examples_margin_asset'), table_name='ms_markets__futureassetdetails__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__futureassetdetails__mainsequence_examples_underlying_index_uid'), table_name='ms_markets__futureassetdetails__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__futureassetdetails__mainsequence_examples_settlement_asset'), table_name='ms_markets__futureassetdetails__mainsequence_examples', schema='public')
    op.drop_table('ms_markets__futureassetdetails__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__currencyspotassetdetails__mainsequence_examples_base_currency_uid'), table_name='ms_markets__currencyspotassetdetails__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__currencyspotassetdetails__mainsequence_examples_quote_currency_uid'), table_name='ms_markets__currencyspotassetdetails__mainsequence_examples', schema='public')
    op.drop_table('ms_markets__currencyspotassetdetails__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__bondassetdetails__mainsequence_examples_currency_asset_uid'), table_name='ms_markets__bondassetdetails__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__bondassetdetails__mainsequence_examples_issuer_uid'), table_name='ms_markets__bondassetdetails__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__bondassetdetails__mainsequence_examples_status'), table_name='ms_markets__bondassetdetails__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__bondassetdetails__mainsequence_examples_maturity_date'), table_name='ms_markets__bondassetdetails__mainsequence_examples', schema='public')
    op.drop_table('ms_markets__bondassetdetails__mainsequence_examples', schema='public')
    op.drop_table('ms_markets__assetsnapshotsts__mainsequence_examples', schema='public')
    op.drop_table('ms_markets__assetpricingdetailsts__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__assetcurrentpricingdetails__mainsequence_examples_pricing_details_date'), table_name='ms_markets__assetcurrentpricingdetails__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__assetcurrentpricingdetails__mainsequence_examples_instrument_type'), table_name='ms_markets__assetcurrentpricingdetails__mainsequence_examples', schema='public')
    op.drop_table('ms_markets__assetcurrentpricingdetails__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__assetcategorymembership__mainsequence_examples_asset_uid'), table_name='ms_markets__assetcategorymembership__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__assetcategorymembership__mainsequence_examples_category_uid'), table_name='ms_markets__assetcategorymembership__mainsequence_examples', schema='public')
    op.drop_table('ms_markets__assetcategorymembership__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__account__mainsequence_examples_unique_identifier'), table_name='ms_markets__account__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__account__mainsequence_examples_account_name'), table_name='ms_markets__account__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__account__mainsequence_examples_account_group_uid'), table_name='ms_markets__account__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__account__mainsequence_examples_account_is_active'), table_name='ms_markets__account__mainsequence_examples', schema='public')
    op.drop_table('ms_markets__account__mainsequence_examples', schema='public')
    op.drop_table('ms_markets__tradests__mainsequence_examples', schema='public')
    op.drop_table('ms_markets__signalweightsts__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__signalmetadata__mainsequence_examples_signal_uid'), table_name='ms_markets__signalmetadata__mainsequence_examples', schema='public')
    op.drop_table('ms_markets__signalmetadata__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__rebalancestrategymetadata__mainsequence_examples_rebalance_strategy_uid'), table_name='ms_markets__rebalancestrategymetadata__mainsequence_examples', schema='public')
    op.drop_table('ms_markets__rebalancestrategymetadata__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__pricingmarketdatabinding__mainsequence_examples_concept_key'), table_name='ms_markets__pricingmarketdatabinding__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__pricingmarketdatabinding__mainsequence_examples_context_key'), table_name='ms_markets__pricingmarketdatabinding__mainsequence_examples', schema='public')
    op.drop_table('ms_markets__pricingmarketdatabinding__mainsequence_examples', schema='public')
    op.drop_table('ms_markets__portfolioweightsts__mainsequence_examples', schema='public')
    op.drop_table('ms_markets__portfoliosts__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__portfoliometadata__mainsequence_examples_unique_identifier'), table_name='ms_markets__portfoliometadata__mainsequence_examples', schema='public')
    op.drop_table('ms_markets__portfoliometadata__mainsequence_examples', schema='public')
    op.drop_table('ms_markets__ordersts__mainsequence_examples', schema='public')
    op.drop_table('ms_markets__ordereventsts__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__marketsmetatablecatalog__mainsequence_examples_table_name'), table_name='ms_markets__marketsmetatablecatalog__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__marketsmetatablecatalog__mainsequence_examples_meta_table_uid'), table_name='ms_markets__marketsmetatablecatalog__mainsequence_examples', schema='public')
    op.drop_table('ms_markets__marketsmetatablecatalog__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__issuer__mainsequence_examples_unique_identifier'), table_name='ms_markets__issuer__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__issuer__mainsequence_examples_display_name'), table_name='ms_markets__issuer__mainsequence_examples', schema='public')
    op.drop_table('ms_markets__issuer__mainsequence_examples', schema='public')
    op.drop_table('ms_markets__interpolatedpricests__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__indextype__mainsequence_examples_display_name'), table_name='ms_markets__indextype__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__indextype__mainsequence_examples_index_type'), table_name='ms_markets__indextype__mainsequence_examples', schema='public')
    op.drop_table('ms_markets__indextype__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__index__mainsequence_examples_unique_identifier'), table_name='ms_markets__index__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__index__mainsequence_examples_provider'), table_name='ms_markets__index__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__index__mainsequence_examples_index_type'), table_name='ms_markets__index__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__index__mainsequence_examples_display_name'), table_name='ms_markets__index__mainsequence_examples', schema='public')
    op.drop_table('ms_markets__index__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__calendar__mainsequence_examples_name'), table_name='ms_markets__calendar__mainsequence_examples', schema='public')
    op.drop_table('ms_markets__calendar__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__assettype__mainsequence_examples_asset_type'), table_name='ms_markets__assettype__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__assettype__mainsequence_examples_display_name'), table_name='ms_markets__assettype__mainsequence_examples', schema='public')
    op.drop_table('ms_markets__assettype__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__assetcategory__mainsequence_examples_unique_identifier'), table_name='ms_markets__assetcategory__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__assetcategory__mainsequence_examples_display_name'), table_name='ms_markets__assetcategory__mainsequence_examples', schema='public')
    op.drop_table('ms_markets__assetcategory__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__asset__mainsequence_examples_unique_identifier'), table_name='ms_markets__asset__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__asset__mainsequence_examples_asset_type'), table_name='ms_markets__asset__mainsequence_examples', schema='public')
    op.drop_table('ms_markets__asset__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__accountmodelportfolio__mainsequence_examples_model_portfolio_name'), table_name='ms_markets__accountmodelportfolio__mainsequence_examples', schema='public')
    op.drop_table('ms_markets__accountmodelportfolio__mainsequence_examples', schema='public')
    op.drop_index(op.f('ix_public_ms_markets__accountgroup__mainsequence_examples_group_name'), table_name='ms_markets__accountgroup__mainsequence_examples', schema='public')
    op.drop_table('ms_markets__accountgroup__mainsequence_examples', schema='public')
    # ### end Alembic commands ###
