from __future__ import annotations

from importlib import import_module
from typing import Any

_EXPORTS = {
    "AccountHoldingsSnapshotExistsError": ".accounts",
    "add_account_holdings_snapshot_response": ".accounts",
    "append_asset_category_membership": ".asset_categories",
    "build_always_open_calendar_materialization": ".calendars",
    "bulk_delete_asset_category_records": ".asset_master_lists",
    "build_account_holdings_frame": ".holdings",
    "build_virtual_fund_holdings_frame": ".accounts",
    "build_pandas_market_calendar_materialization": ".calendars",
    "build_target_positions_frame": ".target_positions",
    "build_holdings_frame": ".holdings",
    "bulk_upsert_calendar_date_records": ".calendars",
    "bulk_upsert_calendar_event_records": ".calendars",
    "bulk_upsert_calendar_session_records": ".calendars",
    "create_account": ".accounts",
    "create_account_group": ".reference_data",
    "create_account_allocation_model": ".accounts",
    "create_account_target_allocation": ".accounts",
    "create_position_set": ".accounts",
    "create_asset": ".assets",
    "create_asset_category": ".asset_categories",
    "create_asset_category_record": ".asset_master_lists",
    "create_calendar": ".reference_data",
    "create_calendar_date_record": ".calendars",
    "create_calendar_event_record": ".calendars",
    "create_calendar_record": ".calendars",
    "create_calendar_session_record": ".calendars",
    "create_openfigi_details": ".provider_details",
    "create_order_manager": ".execution",
    "create_portfolio": ".portfolios",
    "create_virtual_fund": ".accounts",
    "delete_account": ".accounts",
    "delete_account_group": ".reference_data",
    "delete_account_target_allocation": ".accounts",
    "delete_position_set": ".accounts",
    "delete_asset": ".assets",
    "delete_asset_category": ".asset_categories",
    "delete_asset_category_record": ".asset_master_lists",
    "delete_index_record": ".asset_master_lists",
    "delete_calendar": ".reference_data",
    "delete_calendar_date_record": ".calendars",
    "delete_calendar_event_record": ".calendars",
    "delete_calendar_record": ".calendars",
    "delete_calendar_session_record": ".calendars",
    "delete_openfigi_details": ".provider_details",
    "delete_portfolio": ".portfolios",
    "delete_virtual_fund": ".accounts",
    "get_account_by_unique_identifier": ".accounts",
    "get_account_by_uid": ".accounts",
    "get_account_frontend_detail_summary": ".accounts",
    "get_account_holdings_snapshot_response": ".accounts",
    "get_account_target_positions_snapshot_response": ".target_positions",
    "get_asset_frontend_detail_summary": ".asset_master_lists",
    "get_asset_record": ".asset_master_lists",
    "get_asset_by_uid": ".assets",
    "get_asset_by_unique_identifier": ".assets",
    "get_asset_category_by_uid": ".asset_categories",
    "get_asset_category_by_unique_identifier": ".asset_categories",
    "get_asset_category_frontend_detail": ".asset_master_lists",
    "get_asset_category_row": ".asset_master_lists",
    "get_asset_category_record": ".asset_master_lists",
    "get_index_record": ".asset_master_lists",
    "get_calendar_by_uid": ".reference_data",
    "get_calendar_date_record": ".calendars",
    "get_calendar_event_record": ".calendars",
    "get_calendar_frontend_detail_summary": ".calendars",
    "get_calendar_record": ".calendars",
    "get_calendar_session_record": ".calendars",
    "get_openfigi_details_by_uid": ".provider_details",
    "get_portfolio_by_unique_identifier": ".portfolios",
    "get_virtual_fund_by_unique_identifier": ".accounts",
    "get_virtual_funds_by_account": ".accounts",
    "get_virtual_funds_by_portfolio": ".accounts",
    "list_asset_category_memberships": ".asset_categories",
    "list_account_rows_response": ".accounts",
    "list_asset_catalog_rows": ".asset_master_lists",
    "list_asset_rows": ".asset_master_lists",
    "list_asset_category_rows": ".asset_master_lists",
    "list_asset_category_rows_response": ".asset_master_lists",
    "list_calendar_date_records": ".calendars",
    "list_calendar_event_records": ".calendars",
    "list_calendar_records": ".calendars",
    "list_calendar_session_records": ".calendars",
    "list_index_catalog_rows": ".asset_master_lists",
    "materialize_calendar_rows": ".calendars",
    "plan_account_virtual_fund_allocations": ".accounts",
    "register_index_from_figi": ".assets.openfigi",
    "register_index_future_from_figis": ".assets.openfigi",
    "remove_asset_category_membership": ".asset_categories",
    "remove_asset_category_membership_by_pair": ".asset_categories",
    "replace_asset_category_memberships": ".asset_categories",
    "search_account_groups": ".reference_data",
    "search_account_allocation_models": ".accounts",
    "search_account_target_allocations": ".accounts",
    "search_accounts": ".accounts",
    "search_position_sets": ".accounts",
    "search_asset_categories": ".asset_categories",
    "search_assets": ".assets",
    "search_calendars": ".reference_data",
    "search_openfigi_details": ".provider_details",
    "search_order_managers": ".execution",
    "search_portfolios": ".portfolios",
    "expand_portfolio_target_positions": ".target_positions",
    "update_account": ".accounts",
    "update_account_group": ".reference_data",
    "update_asset": ".assets",
    "update_asset_category": ".asset_categories",
    "update_asset_category_record": ".asset_master_lists",
    "update_calendar": ".reference_data",
    "update_calendar_date_record": ".calendars",
    "update_calendar_event_record": ".calendars",
    "update_calendar_record": ".calendars",
    "update_calendar_session_record": ".calendars",
    "update_openfigi_details": ".provider_details",
    "update_order_manager": ".execution",
    "update_portfolio": ".portfolios",
    "update_virtual_fund": ".accounts",
    "upsert_asset": ".assets",
    "validate_target_position_payload": ".target_positions",
    "validate_target_positions_frame": ".target_positions",
    "validate_holdings_frame": ".holdings",
    "validate_virtual_fund_allocation_bounds": ".accounts",
    "apply_account_virtual_fund_allocation_plan": ".accounts",
    "AllocationPolicy": ".accounts",
    "AllocationValuation": ".accounts",
    "HoldingValuationInput": ".accounts",
    "HoldingsSelectionPolicy": ".accounts",
    "PortfolioTargetExpander": ".accounts",
    "TargetNotionalDemand": ".accounts",
    "TargetQuantityDemand": ".accounts",
    "ValuationPolicy": ".accounts",
    "ValuationResolver": ".accounts",
}


def __getattr__(name: str) -> Any:
    if name not in _EXPORTS:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = import_module(_EXPORTS[name], __name__)
    value = getattr(module, name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))


__all__ = sorted(_EXPORTS)
