from __future__ import annotations

PRICING_MARKET_DATA_SET_DEFAULT = "default"
PRICING_MARKET_DATA_SET_EOD = "eod"
PRICING_MARKET_DATA_SET_LIVE = "live"
PRICING_MARKET_DATA_SET_RISK_MANAGER = "risk_manager"

PRICING_CONCEPT_DISCOUNT_CURVES = "discount_curves"
PRICING_CONCEPT_INTEREST_RATE_INDEX_FIXINGS = "interest_rate_index_fixings"
PRICING_CONCEPT_EQUITY_VOL_CURVES = "equity_vol_curves"


__all__ = [
    "PRICING_CONCEPT_DISCOUNT_CURVES",
    "PRICING_CONCEPT_EQUITY_VOL_CURVES",
    "PRICING_CONCEPT_INTEREST_RATE_INDEX_FIXINGS",
    "PRICING_MARKET_DATA_SET_DEFAULT",
    "PRICING_MARKET_DATA_SET_EOD",
    "PRICING_MARKET_DATA_SET_LIVE",
    "PRICING_MARKET_DATA_SET_RISK_MANAGER",
]
