from __future__ import annotations

PRICING_CONTEXT_DEFAULT = "default"
PRICING_CONTEXT_EOD = "eod"
PRICING_CONTEXT_LIVE = "live"
PRICING_CONTEXT_RISK_MANAGER = "risk_manager"

PRICING_CONCEPT_DISCOUNT_CURVES = "discount_curves"
PRICING_CONCEPT_INTEREST_RATE_INDEX_FIXINGS = "interest_rate_index_fixings"
PRICING_CONCEPT_EQUITY_VOL_CURVES = "equity_vol_curves"


__all__ = [
    "PRICING_CONCEPT_DISCOUNT_CURVES",
    "PRICING_CONCEPT_EQUITY_VOL_CURVES",
    "PRICING_CONCEPT_INTEREST_RATE_INDEX_FIXINGS",
    "PRICING_CONTEXT_DEFAULT",
    "PRICING_CONTEXT_EOD",
    "PRICING_CONTEXT_LIVE",
    "PRICING_CONTEXT_RISK_MANAGER",
]
