"""migration

Revision ID: 0003
Revises: 0002
Create Date: 2026-06-10 21:26:36.561184

"""
import datetime as dt
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_MIGRATION_CALENDAR_NAMESPACE = uuid.UUID("e1100f22-0f2c-4d31-88ff-3d1ac97116bb")
_FALLBACK_CALENDAR_IDENTIFIER = "MS_MARKETS_MIGRATION_DEFAULT_CALENDAR"
_MIGRATION_VALID_FROM = dt.date(1970, 1, 1)
_MIGRATION_VALID_TO = dt.date(2100, 12, 31)


def _calendar_table():
    return sa.table(
        "ms_markets__calendar",
        sa.column("uid", sa.Uuid()),
        sa.column("unique_identifier", sa.String(length=255)),
        sa.column("display_name", sa.String(length=255)),
        sa.column("calendar_type", sa.String(length=64)),
        sa.column("timezone", sa.String(length=64)),
        sa.column("source", sa.String(length=128)),
        sa.column("source_identifier", sa.String(length=255)),
        sa.column("valid_from", sa.Date()),
        sa.column("valid_to", sa.Date()),
        sa.column("metadata_json", sa.JSON()),
    )


def _portfolio_table():
    return sa.table(
        "ms_markets__portfolio",
        sa.column("uid", sa.Uuid()),
        sa.column("unique_identifier", sa.String(length=255)),
        sa.column("calendar_name", sa.String(length=255)),
        sa.column("calendar_uid", sa.Uuid()),
    )


def _calendar_uid_for_identifier(connection, unique_identifier: str) -> uuid.UUID:
    calendar = _calendar_table()
    existing_uid = connection.execute(
        sa.select(calendar.c.uid).where(calendar.c.unique_identifier == unique_identifier)
    ).scalar_one_or_none()
    if existing_uid is not None:
        return existing_uid

    calendar_uid = uuid.uuid5(_MIGRATION_CALENDAR_NAMESPACE, unique_identifier)
    connection.execute(
        calendar.insert().values(
            uid=calendar_uid,
            unique_identifier=unique_identifier,
            display_name=unique_identifier,
            calendar_type="CUSTOM",
            timezone="UTC",
            source="ms_markets_migration",
            source_identifier="0003_portfolio_calendar_name_backfill",
            valid_from=_MIGRATION_VALID_FROM,
            valid_to=_MIGRATION_VALID_TO,
            metadata_json={
                "migration": "0003",
                "reason": "Backfilled from PortfolioTable.calendar_name before removing the column.",
            },
        )
    )
    return calendar_uid


def _backfill_portfolio_calendar_uid() -> None:
    connection = op.get_bind()
    portfolio = _portfolio_table()

    calendar_names = list(
        connection.execute(
            sa.select(sa.distinct(portfolio.c.calendar_name))
            .where(portfolio.c.calendar_uid.is_(None))
            .where(portfolio.c.calendar_name.is_not(None))
            .where(portfolio.c.calendar_name != "")
        ).scalars()
    )
    for calendar_name in calendar_names:
        calendar_uid = _calendar_uid_for_identifier(connection, str(calendar_name))
        connection.execute(
            portfolio.update()
            .where(portfolio.c.calendar_uid.is_(None))
            .where(portfolio.c.calendar_name == str(calendar_name))
            .values(calendar_uid=calendar_uid)
        )

    remaining_null_count = connection.execute(
        sa.select(sa.func.count())
        .select_from(portfolio)
        .where(portfolio.c.calendar_uid.is_(None))
    ).scalar_one()
    if remaining_null_count:
        fallback_uid = _calendar_uid_for_identifier(connection, _FALLBACK_CALENDAR_IDENTIFIER)
        connection.execute(
            portfolio.update()
            .where(portfolio.c.calendar_uid.is_(None))
            .values(calendar_uid=fallback_uid)
        )


def _restore_portfolio_calendar_name() -> None:
    connection = op.get_bind()
    calendar = _calendar_table()
    portfolio = _portfolio_table()
    calendar_identifier = (
        sa.select(calendar.c.unique_identifier)
        .where(calendar.c.uid == portfolio.c.calendar_uid)
        .scalar_subquery()
    )
    connection.execute(
        portfolio.update()
        .where(portfolio.c.calendar_uid.is_not(None))
        .values(calendar_name=calendar_identifier)
    )


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    _backfill_portfolio_calendar_uid()
    op.alter_column('ms_markets__portfolio', 'calendar_uid',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix__ms_markets__portfolio__calendar_name'), table_name='ms_markets__portfolio')
    op.drop_constraint(op.f('fk__ms_markets__portfolio__calendar_uid__ms_markets_38b74ba255'), 'ms_markets__portfolio', type_='foreignkey')
    op.create_foreign_key(op.f('fk__ms_markets__portfolio__calendar_uid__ms_markets_38b74ba255'), 'ms_markets__portfolio', 'ms_markets__calendar', ['calendar_uid'], ['uid'], ondelete='RESTRICT')
    op.drop_column('ms_markets__portfolio', 'calendar_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ms_markets__portfolio', sa.Column('calendar_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    _restore_portfolio_calendar_name()
    op.drop_constraint(op.f('fk__ms_markets__portfolio__calendar_uid__ms_markets_38b74ba255'), 'ms_markets__portfolio', type_='foreignkey')
    op.create_foreign_key(op.f('fk__ms_markets__portfolio__calendar_uid__ms_markets_38b74ba255'), 'ms_markets__portfolio', 'ms_markets__calendar', ['calendar_uid'], ['uid'], ondelete='SET NULL')
    op.create_index(op.f('ix__ms_markets__portfolio__calendar_name'), 'ms_markets__portfolio', ['calendar_name'], unique=False)
    op.alter_column('ms_markets__portfolio', 'calendar_uid',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
