"""migration

Revision ID: 0003
Revises: 0002
Create Date: 2026-06-10 21:26:36.561184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ms_markets__portfolio', 'calendar_uid',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix__ms_markets__portfolio__calendar_name'), table_name='ms_markets__portfolio')
    op.drop_constraint(op.f('fk__ms_markets__portfolio__calendar_uid__ms_markets_38b74ba255'), 'ms_markets__portfolio', type_='foreignkey')
    op.create_foreign_key(op.f('fk__ms_markets__portfolio__calendar_uid__ms_markets_38b74ba255'), 'ms_markets__portfolio', 'ms_markets__calendar', ['calendar_uid'], ['uid'], ondelete='RESTRICT')
    op.drop_column('ms_markets__portfolio', 'calendar_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ms_markets__portfolio', sa.Column('calendar_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk__ms_markets__portfolio__calendar_uid__ms_markets_38b74ba255'), 'ms_markets__portfolio', type_='foreignkey')
    op.create_foreign_key(op.f('fk__ms_markets__portfolio__calendar_uid__ms_markets_38b74ba255'), 'ms_markets__portfolio', 'ms_markets__calendar', ['calendar_uid'], ['uid'], ondelete='SET NULL')
    op.create_index(op.f('ix__ms_markets__portfolio__calendar_name'), 'ms_markets__portfolio', ['calendar_name'], unique=False)
    op.alter_column('ms_markets__portfolio', 'calendar_uid',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
