"""migration

Revision ID: 0006
Revises: 0005
Create Date: 2026-06-13 15:45:16.913667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0006'
down_revision: Union[str, Sequence[str], None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ms_markets__portfoliogroup',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('unique_identifier', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__portfoliogroup')),
    info={'namespace': 'mainsequence.markets', 'identifier': 'PortfolioGroup', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__portfoliogroup__display_name'), 'ms_markets__portfoliogroup', ['display_name'], unique=False)
    op.create_index(op.f('uix__ms_markets__portfoliogroup__unique_identifier'), 'ms_markets__portfoliogroup', ['unique_identifier'], unique=True)
    op.create_table('ms_markets__portfoliogroupmembership',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('portfolio_group_uid', sa.Uuid(), nullable=False),
    sa.Column('portfolio_uid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_group_uid'], ['ms_markets__portfoliogroup.uid'], name=op.f('fk__ms_markets__portfoliogroupmembership__portfolio_21b0da4ce6'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['portfolio_uid'], ['ms_markets__portfolio.uid'], name=op.f('fk__ms_markets__portfoliogroupmembership__portfolio_4016df5ffb'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__portfoliogroupmembership')),
    info={'namespace': 'mainsequence.markets', 'identifier': 'PortfolioGroupMembership', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__portfoliogroupmembership__portfolio_group_uid'), 'ms_markets__portfoliogroupmembership', ['portfolio_group_uid'], unique=False)
    op.create_index(op.f('ix__ms_markets__portfoliogroupmembership__portfolio_uid'), 'ms_markets__portfoliogroupmembership', ['portfolio_uid'], unique=False)
    op.create_index(op.f('uix__ms_markets__portfoliogroupmembership__portfolio_68dd4661b0'), 'ms_markets__portfoliogroupmembership', ['portfolio_group_uid', 'portfolio_uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uix__ms_markets__portfoliogroupmembership__portfolio_68dd4661b0'), table_name='ms_markets__portfoliogroupmembership')
    op.drop_index(op.f('ix__ms_markets__portfoliogroupmembership__portfolio_uid'), table_name='ms_markets__portfoliogroupmembership')
    op.drop_index(op.f('ix__ms_markets__portfoliogroupmembership__portfolio_group_uid'), table_name='ms_markets__portfoliogroupmembership')
    op.drop_table('ms_markets__portfoliogroupmembership')
    op.drop_index(op.f('uix__ms_markets__portfoliogroup__unique_identifier'), table_name='ms_markets__portfoliogroup')
    op.drop_index(op.f('ix__ms_markets__portfoliogroup__display_name'), table_name='ms_markets__portfoliogroup')
    op.drop_table('ms_markets__portfoliogroup')
    # ### end Alembic commands ###
