"""pricing curve building details and curve bindings

Revision ID: 0007
Revises: 0006
Create Date: 2026-06-30 12:47:31.813628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0007'
down_revision: Union[str, Sequence[str], None] = '0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ms_markets__curvebuildingdetails',
    sa.Column('curve_uid', sa.Uuid(), nullable=False),
    sa.Column('builder_type', sa.String(length=64), nullable=False),
    sa.Column('quote_convention', sa.String(length=64), nullable=False),
    sa.Column('rate_unit', sa.String(length=32), nullable=False),
    sa.Column('day_counter_code', sa.String(length=64), nullable=False),
    sa.Column('calendar_code', sa.String(length=64), nullable=False),
    sa.Column('interpolation_method', sa.String(length=64), nullable=False),
    sa.Column('compounding', sa.String(length=64), nullable=False),
    sa.Column('compounding_frequency', sa.String(length=64), nullable=True),
    sa.Column('extrapolation_policy', sa.String(length=64), nullable=False),
    sa.Column('bootstrap_method', sa.String(length=64), nullable=True),
    sa.Column('builder_payload', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['curve_uid'], ['ms_markets__curve.uid'], name=op.f('fk__ms_markets__curvebuildingdetails__curve_uid__ms_8b16d2f8b7'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('curve_uid', name=op.f('pk__ms_markets__curvebuildingdetails')),
    info={'namespace': 'mainsequence.markets', 'identifier': 'CurveBuildingDetails', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__curvebuildingdetails__builder_type'), 'ms_markets__curvebuildingdetails', ['builder_type'], unique=False)
    op.create_index(op.f('ix__ms_markets__curvebuildingdetails__quote_convention'), 'ms_markets__curvebuildingdetails', ['quote_convention'], unique=False)
    op.create_index(op.f('ix__ms_markets__curvebuildingdetails__source'), 'ms_markets__curvebuildingdetails', ['source'], unique=False)
    op.create_table('ms_markets__pricingmarketdatasetcurvebinding',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('market_data_set_uid', sa.Uuid(), nullable=False),
    sa.Column('binding_key', sa.String(length=255), nullable=False),
    sa.Column('role_key', sa.String(length=64), nullable=False),
    sa.Column('selector_type', sa.String(length=64), nullable=False),
    sa.Column('selector_key', sa.String(length=255), nullable=False),
    sa.Column('quote_side', sa.String(length=32), nullable=True),
    sa.Column('curve_uid', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['curve_uid'], ['ms_markets__curve.uid'], name=op.f('fk__ms_markets__pricingmarketdatasetcurvebinding__cu_5fe237c524'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['market_data_set_uid'], ['ms_markets__pricingmarketdataset.uid'], name=op.f('fk__ms_markets__pricingmarketdatasetcurvebinding__ma_3e1d491d04'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__pricingmarketdatasetcurvebinding')),
    info={'namespace': 'mainsequence.markets', 'identifier': 'PricingMarketDataSetCurveBinding', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__pricingmarketdatasetcurvebinding__curve_uid'), 'ms_markets__pricingmarketdatasetcurvebinding', ['curve_uid'], unique=False)
    op.create_index(op.f('ix__ms_markets__pricingmarketdatasetcurvebinding__quote_side'), 'ms_markets__pricingmarketdatasetcurvebinding', ['quote_side'], unique=False)
    op.create_index(op.f('ix__ms_markets__pricingmarketdatasetcurvebinding__role_key'), 'ms_markets__pricingmarketdatasetcurvebinding', ['role_key'], unique=False)
    op.create_index(op.f('ix__ms_markets__pricingmarketdatasetcurvebinding__se_c122951238'), 'ms_markets__pricingmarketdatasetcurvebinding', ['selector_type', 'selector_key'], unique=False)
    op.create_index(op.f('ix__ms_markets__pricingmarketdatasetcurvebinding__status'), 'ms_markets__pricingmarketdatasetcurvebinding', ['status'], unique=False)
    op.create_index(op.f('uix__ms_markets__pricingmarketdatasetcurvebinding__m_a4fd2dc807'), 'ms_markets__pricingmarketdatasetcurvebinding', ['market_data_set_uid', 'binding_key'], unique=True)
    op.add_column('ms_markets__curve', sa.Column('currency_code', sa.String(length=16), nullable=True))
    op.add_column('ms_markets__curve', sa.Column('quote_side', sa.String(length=32), nullable=True))
    op.add_column('ms_markets__curve', sa.Column('status', sa.String(length=32), server_default='ACTIVE', nullable=False))
    op.alter_column('ms_markets__curve', 'status',
               existing_type=sa.String(length=32),
               server_default=None)
    op.drop_index(op.f('ix__ms_markets__curve__index_uid'), table_name='ms_markets__curve')
    op.drop_constraint(
        op.f('fk__ms_markets__curve__index_uid__ms_markets__indexc_c0f6b81568'),
        'ms_markets__curve',
        type_='foreignkey',
    )
    op.drop_column('ms_markets__curve', 'index_uid')
    op.create_index(op.f('ix__ms_markets__curve__currency_code'), 'ms_markets__curve', ['currency_code'], unique=False)
    op.create_index(op.f('ix__ms_markets__curve__quote_side'), 'ms_markets__curve', ['quote_side'], unique=False)
    op.create_index(op.f('ix__ms_markets__curve__status'), 'ms_markets__curve', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__ms_markets__curve__status'), table_name='ms_markets__curve')
    op.drop_index(op.f('ix__ms_markets__curve__quote_side'), table_name='ms_markets__curve')
    op.drop_index(op.f('ix__ms_markets__curve__currency_code'), table_name='ms_markets__curve')
    op.add_column('ms_markets__curve', sa.Column('index_uid', sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f('fk__ms_markets__curve__index_uid__ms_markets__indexc_c0f6b81568'),
        'ms_markets__curve',
        'ms_markets__indexconventiondetails',
        ['index_uid'],
        ['index_uid'],
        ondelete='RESTRICT',
    )
    op.create_index(op.f('ix__ms_markets__curve__index_uid'), 'ms_markets__curve', ['index_uid'], unique=False)
    op.drop_column('ms_markets__curve', 'status')
    op.drop_column('ms_markets__curve', 'quote_side')
    op.drop_column('ms_markets__curve', 'currency_code')
    op.drop_index(op.f('uix__ms_markets__pricingmarketdatasetcurvebinding__m_a4fd2dc807'), table_name='ms_markets__pricingmarketdatasetcurvebinding')
    op.drop_index(op.f('ix__ms_markets__pricingmarketdatasetcurvebinding__status'), table_name='ms_markets__pricingmarketdatasetcurvebinding')
    op.drop_index(op.f('ix__ms_markets__pricingmarketdatasetcurvebinding__se_c122951238'), table_name='ms_markets__pricingmarketdatasetcurvebinding')
    op.drop_index(op.f('ix__ms_markets__pricingmarketdatasetcurvebinding__role_key'), table_name='ms_markets__pricingmarketdatasetcurvebinding')
    op.drop_index(op.f('ix__ms_markets__pricingmarketdatasetcurvebinding__quote_side'), table_name='ms_markets__pricingmarketdatasetcurvebinding')
    op.drop_index(op.f('ix__ms_markets__pricingmarketdatasetcurvebinding__curve_uid'), table_name='ms_markets__pricingmarketdatasetcurvebinding')
    op.drop_table('ms_markets__pricingmarketdatasetcurvebinding')
    op.drop_index(op.f('ix__ms_markets__curvebuildingdetails__source'), table_name='ms_markets__curvebuildingdetails')
    op.drop_index(op.f('ix__ms_markets__curvebuildingdetails__quote_convention'), table_name='ms_markets__curvebuildingdetails')
    op.drop_index(op.f('ix__ms_markets__curvebuildingdetails__builder_type'), table_name='ms_markets__curvebuildingdetails')
    op.drop_table('ms_markets__curvebuildingdetails')
    # ### end Alembic commands ###
