"""add discount curve key nodes

Revision ID: 0008
Revises: 0007
Create Date: 2026-07-01 11:00:34.313888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0008'
down_revision: Union[str, Sequence[str], None] = '0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ms_markets__discountcurvests', sa.Column('key_nodes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('ms_markets__discountcurvests', sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ms_markets__discountcurvests', 'metadata_json')
    op.drop_column('ms_markets__discountcurvests', 'key_nodes')
    # ### end Alembic commands ###
