"""remove index provider

Revision ID: 0014
Revises: 0013
Create Date: 2026-07-20 09:48:18.728711

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0014"
down_revision: Union[str, Sequence[str], None] = "0013"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix__ms_markets__index__provider"), table_name="ms_markets__index")
    op.drop_column("ms_markets__index", "provider")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ms_markets__index",
        sa.Column("provider", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    )
    op.create_index(
        op.f("ix__ms_markets__index__provider"), "ms_markets__index", ["provider"], unique=False
    )
    # ### end Alembic commands ###
