"""add portfolio accounting ledger

Revision ID: 0017
Revises: 0016
Create Date: 2026-09-12 08:38:47.439136

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0017"
down_revision: Union[str, Sequence[str], None] = "0016"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ms_markets__portfoliocashflowsts",
        sa.Column("time_index", sa.DateTime(timezone=True), nullable=False),
        sa.Column("portfolio_identifier", sa.String(length=255), nullable=False),
        sa.Column("cash_flow_identifier", sa.String(length=64), nullable=False),
        sa.Column("ledger_state_identifier", sa.String(length=64), nullable=False),
        sa.Column("event_identifier", sa.String(length=64), nullable=False),
        sa.Column("cash_flow_type", sa.String(length=64), nullable=False),
        sa.Column("asset_identifier", sa.String(length=255), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("valuation_amount", sa.Float(), nullable=True),
        sa.Column("valuation_asset_identifier", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["asset_identifier"],
            ["ms_markets__asset.unique_identifier"],
            name=op.f("fk__ms_markets__portfoliocashflowsts__asset_identifi_ccd9c15c47"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_identifier"],
            ["ms_markets__portfolio.unique_identifier"],
            name=op.f("fk__ms_markets__portfoliocashflowsts__portfolio_iden_1aa3ff9f1e"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["valuation_asset_identifier"],
            ["ms_markets__asset.unique_identifier"],
            name=op.f("fk__ms_markets__portfoliocashflowsts__valuation_asse_ca078ce47d"),
            ondelete="RESTRICT",
        ),
        info={
            "markets_storage_app": "ms_markets",
            "namespace": "mainsequence.markets",
            "identifier": "PortfolioCashFlowsTS",
        },
    )
    op.create_index(
        "uix__ms_markets__portfoliocashflowsts__time_index__p_e4e66e3ed6",
        "ms_markets__portfoliocashflowsts",
        ["time_index", "portfolio_identifier", "cash_flow_identifier"],
        unique=True,
    )
    op.create_table(
        "ms_markets__portfolioeventledgerts",
        sa.Column("time_index", sa.DateTime(timezone=True), nullable=False),
        sa.Column("portfolio_identifier", sa.String(length=255), nullable=False),
        sa.Column("event_identifier", sa.String(length=64), nullable=False),
        sa.Column("event_revision", sa.String(length=64), nullable=False),
        sa.Column("record_identifier", sa.String(length=64), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("event_status", sa.String(length=32), nullable=False),
        sa.Column("phase", sa.String(length=32), nullable=False),
        sa.Column("event_sequence", sa.BigInteger(), nullable=False),
        sa.Column("record_sequence", sa.BigInteger(), nullable=False),
        sa.Column("event_record_count", sa.Integer(), nullable=False),
        sa.Column("event_digest", sa.String(length=64), nullable=False),
        sa.Column("source_identifier", sa.String(length=255), nullable=False),
        sa.Column("source_revision", sa.String(length=255), nullable=False),
        sa.Column("model_identifier", sa.String(length=255), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column("supersedes_event_revision", sa.String(length=64), nullable=True),
        sa.Column("causal_event_identifiers", sa.Text(), nullable=True),
        sa.Column("input_state_identifier", sa.String(length=64), nullable=False),
        sa.Column("ledger_state_identifier", sa.String(length=64), nullable=False),
        sa.Column("terms_version", sa.String(length=255), nullable=True),
        sa.Column("valuation_references", sa.Text(), nullable=False),
        sa.Column("record_kind", sa.String(length=32), nullable=False),
        sa.Column("position_identifier", sa.String(length=255), nullable=True),
        sa.Column("obligation_identifier", sa.String(length=255), nullable=True),
        sa.Column("state_identifier", sa.String(length=255), nullable=True),
        sa.Column("asset_identifier", sa.String(length=255), nullable=True),
        sa.Column("balance_role", sa.String(length=64), nullable=True),
        sa.Column("quantity_delta", sa.Float(), nullable=True),
        sa.Column("quantity_unit", sa.String(length=64), nullable=True),
        sa.Column("amount_delta", sa.Float(), nullable=True),
        sa.Column("amount_asset_identifier", sa.String(length=255), nullable=True),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("price_asset_identifier", sa.String(length=255), nullable=True),
        sa.Column("eligible_quantity", sa.Float(), nullable=True),
        sa.Column("recognized_pnl", sa.Float(), nullable=True),
        sa.Column("nav_before", sa.Float(), nullable=True),
        sa.Column("nav_after", sa.Float(), nullable=True),
        sa.Column("valuation_asset_identifier", sa.String(length=255), nullable=True),
        sa.Column("state_schema_version", sa.Integer(), nullable=True),
        sa.Column("extension_payload", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["amount_asset_identifier"],
            ["ms_markets__asset.unique_identifier"],
            name=op.f("fk__ms_markets__portfolioeventledgerts__amount_asset_8007a31a3a"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["asset_identifier"],
            ["ms_markets__asset.unique_identifier"],
            name=op.f("fk__ms_markets__portfolioeventledgerts__asset_identi_687949c5aa"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_identifier"],
            ["ms_markets__portfolio.unique_identifier"],
            name=op.f("fk__ms_markets__portfolioeventledgerts__portfolio_id_2d298ef7c8"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["price_asset_identifier"],
            ["ms_markets__asset.unique_identifier"],
            name=op.f("fk__ms_markets__portfolioeventledgerts__price_asset_e86d478e61"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["valuation_asset_identifier"],
            ["ms_markets__asset.unique_identifier"],
            name=op.f("fk__ms_markets__portfolioeventledgerts__valuation_as_22afd4739f"),
            ondelete="RESTRICT",
        ),
        sa.UniqueConstraint(
            "portfolio_identifier",
            "event_identifier",
            "event_revision",
            "record_identifier",
            name=op.f("uq__ms_markets__portfolioeventledgerts__portfolio_id_256b1e63f2"),
        ),
        info={
            "markets_storage_app": "ms_markets",
            "namespace": "mainsequence.markets",
            "identifier": "PortfolioEventLedgerTS",
        },
    )
    op.create_index(
        "uix__ms_markets__portfolioeventledgerts__time_index_2c8bf183e0",
        "ms_markets__portfolioeventledgerts",
        [
            "time_index",
            "portfolio_identifier",
            "event_identifier",
            "event_revision",
            "record_identifier",
        ],
        unique=True,
    )
    op.create_table(
        "ms_markets__portfoliostatets",
        sa.Column("time_index", sa.DateTime(timezone=True), nullable=False),
        sa.Column("portfolio_identifier", sa.String(length=255), nullable=False),
        sa.Column("state_identifier", sa.String(length=255), nullable=False),
        sa.Column("ledger_state_identifier", sa.String(length=64), nullable=False),
        sa.Column("originating_event_identifier", sa.String(length=64), nullable=False),
        sa.Column("state_kind", sa.String(length=32), nullable=False),
        sa.Column("asset_identifier", sa.String(length=255), nullable=True),
        sa.Column("balance_role", sa.String(length=64), nullable=True),
        sa.Column("quantity", sa.Float(), nullable=True),
        sa.Column("quantity_unit", sa.String(length=64), nullable=True),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("valuation_asset_identifier", sa.String(length=255), nullable=True),
        sa.Column("is_closed", sa.Boolean(), nullable=False),
        sa.Column("extension_payload", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["asset_identifier"],
            ["ms_markets__asset.unique_identifier"],
            name=op.f("fk__ms_markets__portfoliostatets__asset_identifier_08fe4310f7"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_identifier"],
            ["ms_markets__portfolio.unique_identifier"],
            name=op.f("fk__ms_markets__portfoliostatets__portfolio_identifi_bdf8b70f4b"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["valuation_asset_identifier"],
            ["ms_markets__asset.unique_identifier"],
            name=op.f("fk__ms_markets__portfoliostatets__valuation_asset_id_e7977ed80d"),
            ondelete="RESTRICT",
        ),
        info={
            "markets_storage_app": "ms_markets",
            "namespace": "mainsequence.markets",
            "identifier": "PortfolioStateTS",
        },
    )
    op.create_index(
        "uix__ms_markets__portfoliostatets__time_index__portf_7089b41a16",
        "ms_markets__portfoliostatets",
        ["time_index", "portfolio_identifier", "state_identifier"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uix__ms_markets__portfoliostatets__time_index__portf_7089b41a16",
        table_name="ms_markets__portfoliostatets",
    )
    op.drop_table("ms_markets__portfoliostatets")
    op.drop_index(
        "uix__ms_markets__portfolioeventledgerts__time_index_2c8bf183e0",
        table_name="ms_markets__portfolioeventledgerts",
    )
    op.drop_table("ms_markets__portfolioeventledgerts")
    op.drop_index(
        "uix__ms_markets__portfoliocashflowsts__time_index__p_e4e66e3ed6",
        table_name="ms_markets__portfoliocashflowsts",
    )
    op.drop_table("ms_markets__portfoliocashflowsts")
    # ### end Alembic commands ###
