from __future__ import annotations

from .reference_data import (
    EXAMPLE_ASSET_CATEGORY,
    EXAMPLE_ASSET_UNIQUE_IDENTIFIER_PREFIX,
    EXAMPLE_BTC_ASSET,
    EXAMPLE_BTC_ASSET_UNIQUE_IDENTIFIER,
    EXAMPLE_CRYPTO_ASSETS,
    EXAMPLE_CRYPTO_ASSET_TYPE,
    EXAMPLE_CURRENCIES,
    EXAMPLE_CURRENCY_ASSETS,
    EXAMPLE_CURRENCY_ASSET_TYPE,
    EXAMPLE_EQUITY_ASSET_TYPE,
    EXAMPLE_ETH_ASSET,
    EXAMPLE_ETH_ASSET_UNIQUE_IDENTIFIER,
    EXAMPLE_EURUSD_OPENFIGI_FIGI,
    EXAMPLE_EUR_CURRENCY,
    EXAMPLE_OPENFIGI_EQUITY_FIGI,
    EXAMPLE_USD_CURRENCY,
)

__all__ = [
    "EXAMPLE_ASSET_CATEGORY",
    "EXAMPLE_ASSET_UNIQUE_IDENTIFIER_PREFIX",
    "EXAMPLE_BTC_ASSET",
    "EXAMPLE_BTC_ASSET_UNIQUE_IDENTIFIER",
    "EXAMPLE_CRYPTO_ASSETS",
    "EXAMPLE_CRYPTO_ASSET_TYPE",
    "EXAMPLE_CURRENCIES",
    "EXAMPLE_CURRENCY_ASSETS",
    "EXAMPLE_CURRENCY_ASSET_TYPE",
    "EXAMPLE_EQUITY_ASSET_TYPE",
    "EXAMPLE_ETH_ASSET",
    "EXAMPLE_ETH_ASSET_UNIQUE_IDENTIFIER",
    "EXAMPLE_EURUSD_OPENFIGI_FIGI",
    "EXAMPLE_EUR_CURRENCY",
    "EXAMPLE_OPENFIGI_EQUITY_FIGI",
    "EXAMPLE_USD_CURRENCY",
]
