from __future__ import annotations

from msm.repositories.base import (
    MarketsMetaTableHandle,
    MarketsOperationContext,
    MarketsRepositoryContext,
    compile_markets_statement,
    execute_markets_operation,
)
from msm.repositories.crud import (
    build_create_model_operation,
    build_delete_model_operation,
    build_get_model_by_uid_operation,
    build_get_model_by_unique_identifier_operation,
    build_search_model_operation,
    build_update_model_operation,
    create_model,
    delete_model,
    get_model_by_uid,
    get_model_by_unique_identifier,
    search_model,
    update_model,
)

from .virtual_funds import (
    build_create_virtual_fund_operation,
    build_delete_virtual_fund_operation,
    build_get_virtual_fund_by_unique_identifier_operation,
    build_get_virtual_funds_by_account_operation,
    build_get_virtual_funds_by_portfolio_operation,
    build_update_virtual_fund_operation,
    create_virtual_fund,
    delete_virtual_fund,
    get_virtual_fund_by_unique_identifier,
    get_virtual_funds_by_account,
    get_virtual_funds_by_portfolio,
    update_virtual_fund,
)

__all__ = [
    "MarketsMetaTableHandle",
    "MarketsOperationContext",
    "MarketsRepositoryContext",
    "build_create_model_operation",
    "build_create_virtual_fund_operation",
    "build_delete_model_operation",
    "build_delete_virtual_fund_operation",
    "build_get_model_by_uid_operation",
    "build_get_model_by_unique_identifier_operation",
    "build_get_virtual_fund_by_unique_identifier_operation",
    "build_get_virtual_funds_by_account_operation",
    "build_get_virtual_funds_by_portfolio_operation",
    "build_search_model_operation",
    "build_update_model_operation",
    "build_update_virtual_fund_operation",
    "compile_markets_statement",
    "create_model",
    "create_virtual_fund",
    "delete_model",
    "delete_virtual_fund",
    "execute_markets_operation",
    "get_model_by_uid",
    "get_model_by_unique_identifier",
    "get_virtual_fund_by_unique_identifier",
    "get_virtual_funds_by_account",
    "get_virtual_funds_by_portfolio",
    "search_model",
    "update_model",
    "update_virtual_fund",
]
