"""Strict Index formula calculation and independent spread analytics."""

from msm.analytics.indices.contracts import (
    FormulaAlignmentPolicy,
    FormulaMissingDataPolicy,
    FormulaReference,
    FormulaSourceType,
    FormulaStatus,
    FormulaSyntaxError,
    IndexFormula,
    IndexFormulaDefinition,
    IndexFormulaEvaluation,
    IndexFormulaInput,
    IndexFormulaResult,
    IndexFormulaSourceReference,
    canonical_formula,
    compute_formula_definition_hash,
    formula_references,
    parse_formula,
    validate_formula_contract,
)
from msm.analytics.indices.engine import (
    IncompleteFormulaObservationsError,
    IndexFormulaError,
    calculate_formula_index,
)
from msm.analytics.indices.spreads import (
    HedgeRatioMethod,
    NumericSeriesInput,
    PairSpreadMetrics,
    SpreadSeries,
    build_pair_history_frame,
    build_spread_series,
    estimate_hedge_ratio,
    ornstein_uhlenbeck_forecast_cone,
    pair_spread_metrics,
    require_optional_dependency,
    rolling_spread_zscore,
    spread_zscore,
    spread_zscore_matrix,
)

__all__ = [
    "FormulaAlignmentPolicy",
    "FormulaMissingDataPolicy",
    "FormulaReference",
    "FormulaSourceType",
    "FormulaStatus",
    "FormulaSyntaxError",
    "HedgeRatioMethod",
    "IncompleteFormulaObservationsError",
    "IndexFormula",
    "IndexFormulaDefinition",
    "IndexFormulaError",
    "IndexFormulaEvaluation",
    "IndexFormulaInput",
    "IndexFormulaResult",
    "IndexFormulaSourceReference",
    "NumericSeriesInput",
    "PairSpreadMetrics",
    "SpreadSeries",
    "build_pair_history_frame",
    "build_spread_series",
    "calculate_formula_index",
    "canonical_formula",
    "compute_formula_definition_hash",
    "estimate_hedge_ratio",
    "formula_references",
    "ornstein_uhlenbeck_forecast_cone",
    "pair_spread_metrics",
    "parse_formula",
    "require_optional_dependency",
    "rolling_spread_zscore",
    "spread_zscore",
    "spread_zscore_matrix",
    "validate_formula_contract",
]
