"""Generic derived-index definitions, calculation, and resolution."""

from msm.analytics.indices.contracts import (
    IndexCalculationDefinition,
    IndexCalculationLeg,
    IndexCalculationResult,
    ResolvedIndexLeg,
    compute_definition_hash,
    validate_definition_hash,
)
from msm.analytics.indices.engine import (
    IncompleteObservationsError,
    IndexCalculationError,
    LookAheadError,
    calculate_index,
    validate_calculation_contract,
)
from msm.analytics.indices.registries import (
    ALIGNMENT_REGISTRY,
    CALCULATION_REGISTRY,
    COEFFICIENT_REGISTRY,
    MISSING_DATA_REGISTRY,
    REBALANCE_REGISTRY,
    SELECTOR_REGISTRY,
    TRANSFORM_REGISTRY,
    UNIT_REGISTRY,
)
from msm.analytics.indices.resolution import resolve_index_legs, resolve_selector
from msm.analytics.indices.spreads import (
    HedgeRatioMethod,
    NumericSeriesInput,
    PairSpreadMetrics,
    SpreadSeries,
    build_pair_history_frame,
    build_spread_series,
    estimate_hedge_ratio,
    ornstein_uhlenbeck_forecast_cone,
    pair_spread_metrics,
    require_optional_dependency,
    rolling_spread_zscore,
    spread_zscore,
    spread_zscore_matrix,
)

__all__ = [
    "ALIGNMENT_REGISTRY",
    "CALCULATION_REGISTRY",
    "COEFFICIENT_REGISTRY",
    "IncompleteObservationsError",
    "HedgeRatioMethod",
    "IndexCalculationDefinition",
    "IndexCalculationError",
    "IndexCalculationLeg",
    "IndexCalculationResult",
    "LookAheadError",
    "MISSING_DATA_REGISTRY",
    "NumericSeriesInput",
    "PairSpreadMetrics",
    "REBALANCE_REGISTRY",
    "ResolvedIndexLeg",
    "SELECTOR_REGISTRY",
    "SpreadSeries",
    "TRANSFORM_REGISTRY",
    "UNIT_REGISTRY",
    "calculate_index",
    "build_pair_history_frame",
    "build_spread_series",
    "compute_definition_hash",
    "estimate_hedge_ratio",
    "ornstein_uhlenbeck_forecast_cone",
    "pair_spread_metrics",
    "require_optional_dependency",
    "resolve_index_legs",
    "resolve_selector",
    "rolling_spread_zscore",
    "spread_zscore",
    "spread_zscore_matrix",
    "validate_calculation_contract",
    "validate_definition_hash",
]
