"""migration

Revision ID: 0001
Revises: 
Create Date: 2026-06-10 18:07:00.388417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ms_markets__accountallocationmodel',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('allocation_model_name', sa.String(length=100), nullable=False),
    sa.Column('allocation_model_description', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__accountallocationmodel')),
    info={'namespace': 'mainsequence.markets', 'identifier': 'AccountAllocationModel', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('uix__ms_markets__accountallocationmodel__allocation_model_name'), 'ms_markets__accountallocationmodel', ['allocation_model_name'], unique=True)
    op.create_table('ms_markets__accountgroup',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('group_name', sa.String(length=100), nullable=True),
    sa.Column('group_description', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__accountgroup')),
    info={'namespace': 'mainsequence.markets', 'identifier': 'AccountGroup', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('uix__ms_markets__accountgroup__group_name'), 'ms_markets__accountgroup', ['group_name'], unique=True)
    op.create_table('ms_markets__asset',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('unique_identifier', sa.String(length=255), nullable=False),
    sa.Column('asset_type', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__asset')),
    info={'namespace': 'mainsequence.markets', 'identifier': 'Asset', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__asset__asset_type'), 'ms_markets__asset', ['asset_type'], unique=False)
    op.create_index(op.f('uix__ms_markets__asset__unique_identifier'), 'ms_markets__asset', ['unique_identifier'], unique=True)
    op.create_table('ms_markets__assetcategory',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('unique_identifier', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__assetcategory')),
    info={'namespace': 'mainsequence.markets', 'identifier': 'AssetCategory', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__assetcategory__display_name'), 'ms_markets__assetcategory', ['display_name'], unique=False)
    op.create_index(op.f('uix__ms_markets__assetcategory__unique_identifier'), 'ms_markets__assetcategory', ['unique_identifier'], unique=True)
    op.create_table('ms_markets__assettype',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('asset_type', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__assettype')),
    info={'namespace': 'mainsequence.markets', 'identifier': 'AssetType', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__assettype__display_name'), 'ms_markets__assettype', ['display_name'], unique=False)
    op.create_index(op.f('uix__ms_markets__assettype__asset_type'), 'ms_markets__assettype', ['asset_type'], unique=True)
    op.create_table('ms_markets__calendar',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('unique_identifier', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('calendar_type', sa.String(length=64), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('source_identifier', sa.String(length=255), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__calendar')),
    info={'namespace': 'mainsequence.markets', 'identifier': 'Calendar', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__calendar__calendar_type'), 'ms_markets__calendar', ['calendar_type'], unique=False)
    op.create_index(op.f('ix__ms_markets__calendar__source__source_identifier'), 'ms_markets__calendar', ['source', 'source_identifier'], unique=False)
    op.create_index(op.f('uix__ms_markets__calendar__unique_identifier'), 'ms_markets__calendar', ['unique_identifier'], unique=True)
    op.create_table('ms_markets__index',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('unique_identifier', sa.String(length=255), nullable=False),
    sa.Column('index_type', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__index')),
    info={'namespace': 'mainsequence.markets', 'identifier': 'Index', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__index__display_name'), 'ms_markets__index', ['display_name'], unique=False)
    op.create_index(op.f('ix__ms_markets__index__index_type'), 'ms_markets__index', ['index_type'], unique=False)
    op.create_index(op.f('ix__ms_markets__index__provider'), 'ms_markets__index', ['provider'], unique=False)
    op.create_index(op.f('uix__ms_markets__index__unique_identifier'), 'ms_markets__index', ['unique_identifier'], unique=True)
    op.create_table('ms_markets__indextype',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('index_type', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__indextype')),
    info={'namespace': 'mainsequence.markets', 'identifier': 'IndexType', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__indextype__display_name'), 'ms_markets__indextype', ['display_name'], unique=False)
    op.create_index(op.f('uix__ms_markets__indextype__index_type'), 'ms_markets__indextype', ['index_type'], unique=True)
    op.create_table('ms_markets__issuer',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('unique_identifier', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__issuer')),
    info={'namespace': 'mainsequence.markets', 'identifier': 'Issuer', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__issuer__display_name'), 'ms_markets__issuer', ['display_name'], unique=False)
    op.create_index(op.f('uix__ms_markets__issuer__unique_identifier'), 'ms_markets__issuer', ['unique_identifier'], unique=True)
    op.create_table('ms_markets__ordereventsts',
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('order_identifier', sa.String(), nullable=False),
    sa.Column('order_status', sa.String(), nullable=True),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    info={'markets_storage_app': 'ms_markets', 'namespace': 'mainsequence.markets', 'identifier': 'OrderEventsTS'}
    )
    op.create_index('uix__ms_markets__ordereventsts__event_time__order_identifier', 'ms_markets__ordereventsts', ['event_time', 'order_identifier'], unique=True)
    op.create_table('ms_markets__ordersts',
    sa.Column('order_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('order_identifier', sa.String(), nullable=False),
    sa.Column('account_identifier', sa.String(), nullable=False),
    sa.Column('fund_identifier', sa.String(), nullable=True),
    sa.Column('order_manager_identifier', sa.String(), nullable=True),
    sa.Column('asset_identifier', sa.String(), nullable=False),
    sa.Column('order_remote_id', sa.String(), nullable=True),
    sa.Column('client_order_id', sa.String(), nullable=True),
    sa.Column('order_type', sa.String(), nullable=True),
    sa.Column('order_side', sa.BigInteger(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('filled_quantity', sa.Float(), nullable=True),
    sa.Column('filled_price', sa.Float(), nullable=True),
    sa.Column('expires_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('limit_price', sa.Float(), nullable=True),
    sa.Column('time_in_force', sa.String(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('venue_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    info={'markets_storage_app': 'ms_markets', 'namespace': 'mainsequence.markets', 'identifier': 'OrdersTS'}
    )
    op.create_index('uix__ms_markets__ordersts__order_time__order_identif_20c686be5c', 'ms_markets__ordersts', ['order_time', 'order_identifier', 'account_identifier', 'asset_identifier'], unique=True)
    op.create_table('ms_markets__portfoliometadata',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('unique_identifier', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__portfoliometadata')),
    info={'namespace': 'mainsequence.markets', 'identifier': 'PortfolioMetadata', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('uix__ms_markets__portfoliometadata__unique_identifier'), 'ms_markets__portfoliometadata', ['unique_identifier'], unique=True)
    op.create_table('ms_markets__portfolioweightsts',
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.Column('portfolio_identifier', sa.String(), nullable=False),
    sa.Column('asset_identifier', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('weight_before', sa.Float(), nullable=True),
    sa.Column('price_current', sa.Float(), nullable=True),
    sa.Column('price_before', sa.Float(), nullable=True),
    sa.Column('volume_current', sa.Float(), nullable=True),
    sa.Column('volume_before', sa.Float(), nullable=True),
    info={'markets_storage_app': 'ms_markets', 'namespace': 'mainsequence.markets', 'identifier': 'PortfolioWeightsTS'}
    )
    op.create_index('uix__ms_markets__portfolioweightsts__time_index__por_d92475bae0', 'ms_markets__portfolioweightsts', ['time_index', 'portfolio_identifier', 'asset_identifier'], unique=True)
    op.create_table('ms_markets__pricingmarketdataset',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('set_key', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__pricingmarketdataset')),
    info={'namespace': 'mainsequence.markets', 'identifier': 'PricingMarketDataSet', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__pricingmarketdataset__status'), 'ms_markets__pricingmarketdataset', ['status'], unique=False)
    op.create_index(op.f('uix__ms_markets__pricingmarketdataset__set_key'), 'ms_markets__pricingmarketdataset', ['set_key'], unique=True)
    op.create_table('ms_markets__rebalancestrategymetadata',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('rebalance_strategy_uid', sa.String(length=255), nullable=False),
    sa.Column('rebalance_strategy_description', sa.Text(), nullable=True),
    sa.Column('configuration_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__rebalancestrategymetadata')),
    info={'namespace': 'mainsequence.markets', 'identifier': 'RebalanceStrategyMetadata', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('uix__ms_markets__rebalancestrategymetadata__rebalanc_a097a6f535'), 'ms_markets__rebalancestrategymetadata', ['rebalance_strategy_uid'], unique=True)
    op.create_table('ms_markets__signalmetadata',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('signal_uid', sa.String(length=255), nullable=False),
    sa.Column('signal_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__signalmetadata')),
    info={'namespace': 'mainsequence.markets', 'identifier': 'SignalMetadata', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('uix__ms_markets__signalmetadata__signal_uid'), 'ms_markets__signalmetadata', ['signal_uid'], unique=True)
    op.create_table('ms_markets__tradests',
    sa.Column('trade_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trade_identifier', sa.String(), nullable=False),
    sa.Column('account_identifier', sa.String(), nullable=False),
    sa.Column('fund_identifier', sa.String(), nullable=True),
    sa.Column('order_identifier', sa.String(), nullable=True),
    sa.Column('asset_identifier', sa.String(), nullable=False),
    sa.Column('trade_side', sa.BigInteger(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('commission_asset_identifier', sa.String(), nullable=True),
    sa.Column('settlement_cost', sa.Float(), nullable=True),
    sa.Column('settlement_asset_identifier', sa.String(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('venue_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    info={'markets_storage_app': 'ms_markets', 'namespace': 'mainsequence.markets', 'identifier': 'TradesTS'}
    )
    op.create_index('uix__ms_markets__tradests__trade_time__trade_identif_4ad9fea888', 'ms_markets__tradests', ['trade_time', 'trade_identifier', 'account_identifier', 'asset_identifier'], unique=True)
    op.create_table('ms_markets__account',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('unique_identifier', sa.String(length=255), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('is_paper', sa.Boolean(), nullable=False),
    sa.Column('account_is_active', sa.Boolean(), nullable=False),
    sa.Column('account_group_uid', sa.Uuid(), nullable=True),
    sa.Column('holdings_data_node_uid', sa.Uuid(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['account_group_uid'], ['ms_markets__accountgroup.uid'], name=op.f('fk__ms_markets__account__account_group_uid__ms_marke_6e57748f82'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__account')),
    info={'namespace': 'mainsequence.markets', 'identifier': 'Account', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__account__account_group_uid'), 'ms_markets__account', ['account_group_uid'], unique=False)
    op.create_index(op.f('ix__ms_markets__account__account_is_active'), 'ms_markets__account', ['account_is_active'], unique=False)
    op.create_index(op.f('ix__ms_markets__account__account_name'), 'ms_markets__account', ['account_name'], unique=False)
    op.create_index(op.f('uix__ms_markets__account__unique_identifier'), 'ms_markets__account', ['unique_identifier'], unique=True)
    op.create_table('ms_markets__assetcategorymembership',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('category_uid', sa.Uuid(), nullable=False),
    sa.Column('asset_uid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['asset_uid'], ['ms_markets__asset.uid'], name=op.f('fk__ms_markets__assetcategorymembership__asset_uid_5f2895c7b9'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_uid'], ['ms_markets__assetcategory.uid'], name=op.f('fk__ms_markets__assetcategorymembership__category_ui_38bb05de48'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__assetcategorymembership')),
    info={'namespace': 'mainsequence.markets', 'identifier': 'AssetCategoryMembership', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__assetcategorymembership__asset_uid'), 'ms_markets__assetcategorymembership', ['asset_uid'], unique=False)
    op.create_index(op.f('uix__ms_markets__assetcategorymembership__category_u_0c42bc3572'), 'ms_markets__assetcategorymembership', ['category_uid', 'asset_uid'], unique=True)
    op.create_table('ms_markets__assetcurrentpricingdetails',
    sa.Column('asset_uid', sa.Uuid(), nullable=False),
    sa.Column('instrument_type', sa.String(length=128), nullable=False),
    sa.Column('instrument_dump', sa.JSON(), nullable=False),
    sa.Column('pricing_details_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('serialization_format', sa.String(length=128), nullable=False),
    sa.Column('pricing_package_version', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['asset_uid'], ['ms_markets__asset.uid'], name=op.f('fk__ms_markets__assetcurrentpricingdetails__asset_ui_1c2887baef'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_uid', name=op.f('pk__ms_markets__assetcurrentpricingdetails')),
    info={'namespace': 'mainsequence.markets', 'identifier': 'AssetCurrentPricingDetails', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__assetcurrentpricingdetails__instrument_type'), 'ms_markets__assetcurrentpricingdetails', ['instrument_type'], unique=False)
    op.create_index(op.f('ix__ms_markets__assetcurrentpricingdetails__pricing_dc942ad94f'), 'ms_markets__assetcurrentpricingdetails', ['pricing_details_date'], unique=False)
    op.create_table('ms_markets__assetpricingdetailsts',
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.Column('asset_identifier', sa.String(length=255), nullable=False),
    sa.Column('instrument_dump', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('instrument_type', sa.String(length=128), nullable=False),
    sa.Column('serialization_format', sa.String(length=128), nullable=False),
    sa.Column('pricing_package_version', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['asset_identifier'], ['ms_markets__asset.unique_identifier'], name=op.f('fk__ms_markets__assetpricingdetailsts__asset_identif_f006fec295'), ondelete='RESTRICT'),
    info={'markets_storage_app': 'ms_markets', 'namespace': 'mainsequence.markets', 'identifier': 'AssetPricingDetailsTS'}
    )
    op.create_index('uix__ms_markets__assetpricingdetailsts__time_index_affb4cd407', 'ms_markets__assetpricingdetailsts', ['time_index', 'asset_identifier'], unique=True)
    op.create_table('ms_markets__assetsnapshotsts',
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.Column('asset_identifier', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('exchange_code', sa.String(), nullable=True),
    sa.Column('asset_ticker_group_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['asset_identifier'], ['ms_markets__asset.unique_identifier'], name=op.f('fk__ms_markets__assetsnapshotsts__asset_identifier_dbde28e44f'), ondelete='RESTRICT'),
    info={'markets_storage_app': 'ms_markets', 'namespace': 'mainsequence.markets', 'identifier': 'AssetSnapshotsTS'}
    )
    op.create_index('uix__ms_markets__assetsnapshotsts__time_index__asset_identifier', 'ms_markets__assetsnapshotsts', ['time_index', 'asset_identifier'], unique=True)
    op.create_table('ms_markets__bondassetdetails',
    sa.Column('asset_uid', sa.Uuid(), nullable=False),
    sa.Column('issuer_uid', sa.Uuid(), nullable=False),
    sa.Column('currency_asset_uid', sa.Uuid(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['asset_uid'], ['ms_markets__asset.uid'], name=op.f('fk__ms_markets__bondassetdetails__asset_uid__ms_mark_b546a4682d'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['currency_asset_uid'], ['ms_markets__asset.uid'], name=op.f('fk__ms_markets__bondassetdetails__currency_asset_uid_ea9b01c897'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['issuer_uid'], ['ms_markets__issuer.uid'], name=op.f('fk__ms_markets__bondassetdetails__issuer_uid__ms_mar_8fe31913aa'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('asset_uid', name=op.f('pk__ms_markets__bondassetdetails')),
    info={'namespace': 'mainsequence.markets', 'identifier': 'BondAssetDetails', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__bondassetdetails__currency_asset_uid'), 'ms_markets__bondassetdetails', ['currency_asset_uid'], unique=False)
    op.create_index(op.f('ix__ms_markets__bondassetdetails__issuer_uid'), 'ms_markets__bondassetdetails', ['issuer_uid'], unique=False)
    op.create_index(op.f('ix__ms_markets__bondassetdetails__maturity_date'), 'ms_markets__bondassetdetails', ['maturity_date'], unique=False)
    op.create_index(op.f('ix__ms_markets__bondassetdetails__status'), 'ms_markets__bondassetdetails', ['status'], unique=False)
    op.create_table('ms_markets__calendardate',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('calendar_uid', sa.Uuid(), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('is_business_day', sa.Boolean(), nullable=False),
    sa.Column('is_holiday', sa.Boolean(), nullable=False),
    sa.Column('is_weekend', sa.Boolean(), nullable=False),
    sa.Column('is_early_close', sa.Boolean(), nullable=False),
    sa.Column('holiday_name', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['calendar_uid'], ['ms_markets__calendar.uid'], name=op.f('fk__ms_markets__calendardate__calendar_uid__ms_marke_d1ea943953'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__calendardate')),
    info={'namespace': 'mainsequence.markets', 'identifier': 'CalendarDate', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__calendardate__calendar_uid__is_business_day'), 'ms_markets__calendardate', ['calendar_uid', 'is_business_day'], unique=False)
    op.create_index(op.f('ix__ms_markets__calendardate__local_date'), 'ms_markets__calendardate', ['local_date'], unique=False)
    op.create_index(op.f('uix__ms_markets__calendardate__calendar_uid__local_date'), 'ms_markets__calendardate', ['calendar_uid', 'local_date'], unique=True)
    op.create_table('ms_markets__calendarevent',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('calendar_uid', sa.Uuid(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('event_label', sa.String(length=255), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_uid', sa.Uuid(), nullable=True),
    sa.Column('target_identifier', sa.String(length=255), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['calendar_uid'], ['ms_markets__calendar.uid'], name=op.f('fk__ms_markets__calendarevent__calendar_uid__ms_mark_82f9e66428'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__calendarevent')),
    info={'namespace': 'mainsequence.markets', 'identifier': 'CalendarEvent', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__calendarevent__calendar_uid__event_date'), 'ms_markets__calendarevent', ['calendar_uid', 'event_date'], unique=False)
    op.create_index(op.f('ix__ms_markets__calendarevent__event_type'), 'ms_markets__calendarevent', ['event_type'], unique=False)
    op.create_index(op.f('ix__ms_markets__calendarevent__target_type__target_uid'), 'ms_markets__calendarevent', ['target_type', 'target_uid'], unique=False)
    op.create_index(op.f('uix__ms_markets__calendarevent__calendar_uid__event_5ff36d9c47'), 'ms_markets__calendarevent', ['calendar_uid', 'event_date', 'event_type', 'event_label', 'target_type', 'target_identifier'], unique=True)
    op.create_table('ms_markets__calendarsession',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('calendar_uid', sa.Uuid(), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('session_label', sa.String(length=64), nullable=False),
    sa.Column('opens_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closes_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['calendar_uid'], ['ms_markets__calendar.uid'], name=op.f('fk__ms_markets__calendarsession__calendar_uid__ms_ma_1b8e1a05d3'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__calendarsession')),
    info={'namespace': 'mainsequence.markets', 'identifier': 'CalendarSession', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__calendarsession__calendar_uid__is_primary'), 'ms_markets__calendarsession', ['calendar_uid', 'is_primary'], unique=False)
    op.create_index(op.f('ix__ms_markets__calendarsession__local_date'), 'ms_markets__calendarsession', ['local_date'], unique=False)
    op.create_index(op.f('uix__ms_markets__calendarsession__calendar_uid__loca_30b16604ba'), 'ms_markets__calendarsession', ['calendar_uid', 'local_date', 'session_label'], unique=True)
    op.create_table('ms_markets__currencyspotassetdetails',
    sa.Column('asset_uid', sa.Uuid(), nullable=False),
    sa.Column('base_currency_uid', sa.Uuid(), nullable=False),
    sa.Column('quote_currency_uid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['asset_uid'], ['ms_markets__asset.uid'], name=op.f('fk__ms_markets__currencyspotassetdetails__asset_uid_14d1916f45'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['base_currency_uid'], ['ms_markets__asset.uid'], name=op.f('fk__ms_markets__currencyspotassetdetails__base_curre_f7fc7a4996'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['quote_currency_uid'], ['ms_markets__asset.uid'], name=op.f('fk__ms_markets__currencyspotassetdetails__quote_curr_12d82159e5'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('asset_uid', name=op.f('pk__ms_markets__currencyspotassetdetails')),
    info={'namespace': 'mainsequence.markets', 'identifier': 'CurrencySpotAssetDetails', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__currencyspotassetdetails__base_currency_uid'), 'ms_markets__currencyspotassetdetails', ['base_currency_uid'], unique=False)
    op.create_index(op.f('ix__ms_markets__currencyspotassetdetails__quote_currency_uid'), 'ms_markets__currencyspotassetdetails', ['quote_currency_uid'], unique=False)
    op.create_index(op.f('uix__ms_markets__currencyspotassetdetails__base_curr_c8929e9103'), 'ms_markets__currencyspotassetdetails', ['base_currency_uid', 'quote_currency_uid'], unique=True)
    op.create_table('ms_markets__externalpricests',
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.Column('asset_identifier', sa.String(length=255), nullable=False),
    sa.Column('open_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('trade_count', sa.Float(), nullable=True),
    sa.Column('vwap', sa.Float(), nullable=True),
    sa.Column('interpolated', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['asset_identifier'], ['ms_markets__asset.unique_identifier'], name=op.f('fk__ms_markets__externalpricests__asset_identifier_1e0967f48c'), ondelete='RESTRICT'),
    info={'markets_storage_app': 'ms_markets', 'namespace': 'mainsequence.markets', 'identifier': 'ExternalPricesTS'}
    )
    op.create_index('uix__ms_markets__externalpricests__time_index__asset_identifier', 'ms_markets__externalpricests', ['time_index', 'asset_identifier'], unique=True)
    op.create_table('ms_markets__futureassetdetails',
    sa.Column('asset_uid', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('underlying_index_uid', sa.Uuid(), nullable=False),
    sa.Column('quote_unit', sa.String(length=64), nullable=False),
    sa.Column('settlement_asset', sa.Uuid(), nullable=False),
    sa.Column('margin_asset', sa.Uuid(), nullable=False),
    sa.Column('settlement_model', sa.String(length=32), nullable=False),
    sa.Column('settlement_method', sa.String(length=32), nullable=False),
    sa.Column('contract_size', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('contract_unit', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settles_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['asset_uid'], ['ms_markets__asset.uid'], name=op.f('fk__ms_markets__futureassetdetails__asset_uid__ms_ma_9a160ba3da'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['margin_asset'], ['ms_markets__asset.uid'], name=op.f('fk__ms_markets__futureassetdetails__margin_asset__ms_beef65882d'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['settlement_asset'], ['ms_markets__asset.uid'], name=op.f('fk__ms_markets__futureassetdetails__settlement_asset_7b263cb41b'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['underlying_index_uid'], ['ms_markets__index.uid'], name=op.f('fk__ms_markets__futureassetdetails__underlying_index_a3b279700b'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('asset_uid', name=op.f('pk__ms_markets__futureassetdetails')),
    info={'namespace': 'mainsequence.markets', 'identifier': 'FutureAssetDetails', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__futureassetdetails__expires_at'), 'ms_markets__futureassetdetails', ['expires_at'], unique=False)
    op.create_index(op.f('ix__ms_markets__futureassetdetails__margin_asset'), 'ms_markets__futureassetdetails', ['margin_asset'], unique=False)
    op.create_index(op.f('ix__ms_markets__futureassetdetails__settlement_asset'), 'ms_markets__futureassetdetails', ['settlement_asset'], unique=False)
    op.create_index(op.f('ix__ms_markets__futureassetdetails__underlying_index_uid'), 'ms_markets__futureassetdetails', ['underlying_index_uid'], unique=False)
    op.create_table('ms_markets__indexconventiondetails',
    sa.Column('index_uid', sa.Uuid(), nullable=False),
    sa.Column('index_family', sa.String(length=64), nullable=False),
    sa.Column('convention_dump', sa.JSON(), nullable=False),
    sa.Column('serialization_format', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['index_uid'], ['ms_markets__index.uid'], name=op.f('fk__ms_markets__indexconventiondetails__index_uid__m_b3b3091742'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('index_uid', name=op.f('pk__ms_markets__indexconventiondetails')),
    info={'namespace': 'mainsequence.markets', 'identifier': 'IndexConventionDetails', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__indexconventiondetails__index_family'), 'ms_markets__indexconventiondetails', ['index_family'], unique=False)
    op.create_index(op.f('ix__ms_markets__indexconventiondetails__source'), 'ms_markets__indexconventiondetails', ['source'], unique=False)
    op.create_table('ms_markets__indexfixingsts',
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.Column('index_identifier', sa.String(length=255), nullable=False),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['index_identifier'], ['ms_markets__index.unique_identifier'], name=op.f('fk__ms_markets__indexfixingsts__index_identifier__ms_011a6aef3b'), ondelete='RESTRICT'),
    info={'markets_storage_app': 'ms_markets', 'namespace': 'mainsequence.markets', 'identifier': 'IndexFixingsTS'}
    )
    op.create_index('uix__ms_markets__indexfixingsts__time_index__index_identifier', 'ms_markets__indexfixingsts', ['time_index', 'index_identifier'], unique=True)
    op.create_table('ms_markets__interpolatedpricests',
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.Column('asset_identifier', sa.String(length=255), nullable=False),
    sa.Column('open_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('trade_count', sa.Float(), nullable=True),
    sa.Column('vwap', sa.Float(), nullable=True),
    sa.Column('interpolated', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['asset_identifier'], ['ms_markets__asset.unique_identifier'], name=op.f('fk__ms_markets__interpolatedpricests__asset_identifi_2eaa30fd5d'), ondelete='RESTRICT'),
    info={'markets_storage_app': 'ms_markets', 'namespace': 'mainsequence.markets', 'identifier': 'InterpolatedPricesTS'}
    )
    op.create_index('uix__ms_markets__interpolatedpricests__time_index__a_303e840ea7', 'ms_markets__interpolatedpricests', ['time_index', 'asset_identifier'], unique=True)
    op.create_table('ms_markets__openfigiassetdetails',
    sa.Column('asset_uid', sa.Uuid(), nullable=False),
    sa.Column('figi', sa.String(length=12), nullable=True),
    sa.Column('composite', sa.String(length=12), nullable=True),
    sa.Column('share_class', sa.String(length=12), nullable=True),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('ticker', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('exchange_code', sa.String(length=50), nullable=True),
    sa.Column('security_type', sa.String(length=50), nullable=True),
    sa.Column('security_type_2', sa.String(length=50), nullable=True),
    sa.Column('security_market_sector', sa.String(length=50), nullable=True),
    sa.Column('security_description', sa.String(length=255), nullable=True),
    sa.Column('unique_id', sa.String(length=255), nullable=True),
    sa.Column('unique_id_fut_opt', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['asset_uid'], ['ms_markets__asset.uid'], name=op.f('fk__ms_markets__openfigiassetdetails__asset_uid__ms_71f6ffefab'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_uid', name=op.f('pk__ms_markets__openfigiassetdetails')),
    info={'namespace': 'mainsequence.markets', 'identifier': 'OpenFigiAssetDetails', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__openfigiassetdetails__figi'), 'ms_markets__openfigiassetdetails', ['figi'], unique=False)
    op.create_index(op.f('ix__ms_markets__openfigiassetdetails__isin'), 'ms_markets__openfigiassetdetails', ['isin'], unique=False)
    op.create_index(op.f('ix__ms_markets__openfigiassetdetails__ticker'), 'ms_markets__openfigiassetdetails', ['ticker'], unique=False)
    op.create_table('ms_markets__portfolio',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('unique_identifier', sa.String(length=255), nullable=False),
    sa.Column('calendar_name', sa.String(length=255), nullable=True),
    sa.Column('calendar_uid', sa.Uuid(), nullable=True),
    sa.Column('published_index_uid', sa.Uuid(), nullable=True),
    sa.Column('portfolio_weights_data_node_uid', sa.Uuid(), nullable=True),
    sa.Column('signal_weights_data_node_uid', sa.Uuid(), nullable=True),
    sa.Column('portfolio_data_node_uid', sa.Uuid(), nullable=True),
    sa.Column('backtest_table_price_column_name', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['calendar_uid'], ['ms_markets__calendar.uid'], name=op.f('fk__ms_markets__portfolio__calendar_uid__ms_markets_38b74ba255'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['published_index_uid'], ['ms_markets__index.uid'], name=op.f('fk__ms_markets__portfolio__published_index_uid__ms_m_55735b6fcf'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__portfolio')),
    info={'namespace': 'mainsequence.markets', 'identifier': 'Portfolio', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__portfolio__calendar_name'), 'ms_markets__portfolio', ['calendar_name'], unique=False)
    op.create_index(op.f('ix__ms_markets__portfolio__calendar_uid'), 'ms_markets__portfolio', ['calendar_uid'], unique=False)
    op.create_index(op.f('ix__ms_markets__portfolio__published_index_uid'), 'ms_markets__portfolio', ['published_index_uid'], unique=False)
    op.create_index(op.f('uix__ms_markets__portfolio__unique_identifier'), 'ms_markets__portfolio', ['unique_identifier'], unique=True)
    op.create_table('ms_markets__pricingmarketdatasetbinding',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('market_data_set_uid', sa.Uuid(), nullable=False),
    sa.Column('concept_key', sa.String(length=128), nullable=False),
    sa.Column('data_node_uid', sa.Uuid(), nullable=False),
    sa.Column('storage_table_identifier', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['market_data_set_uid'], ['ms_markets__pricingmarketdataset.uid'], name=op.f('fk__ms_markets__pricingmarketdatasetbinding__market_905593db9d'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__pricingmarketdatasetbinding')),
    info={'namespace': 'mainsequence.markets', 'identifier': 'PricingMarketDataSetBinding', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__pricingmarketdatasetbinding__concept_key'), 'ms_markets__pricingmarketdatasetbinding', ['concept_key'], unique=False)
    op.create_index(op.f('ix__ms_markets__pricingmarketdatasetbinding__data_node_uid'), 'ms_markets__pricingmarketdatasetbinding', ['data_node_uid'], unique=False)
    op.create_index(op.f('uix__ms_markets__pricingmarketdatasetbinding__market_7fb160d6c7'), 'ms_markets__pricingmarketdatasetbinding', ['market_data_set_uid', 'concept_key'], unique=True)
    op.create_table('ms_markets__signalweightsts',
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signal_uid', sa.String(length=255), nullable=False),
    sa.Column('asset_identifier', sa.String(), nullable=False),
    sa.Column('signal_weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['signal_uid'], ['ms_markets__signalmetadata.signal_uid'], name=op.f('fk__ms_markets__signalweightsts__signal_uid__ms_mark_5e17963320'), ondelete='RESTRICT'),
    info={'markets_storage_app': 'ms_markets', 'namespace': 'mainsequence.markets', 'identifier': 'SignalWeightsTS'}
    )
    op.create_index('uix__ms_markets__signalweightsts__time_index__signal_94cdab9295', 'ms_markets__signalweightsts', ['time_index', 'signal_uid', 'asset_identifier'], unique=True)
    op.create_table('ms_markets__accountholdingsset',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('account_uid', sa.Uuid(), nullable=False),
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_data_node_uid', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['account_uid'], ['ms_markets__account.uid'], name=op.f('fk__ms_markets__accountholdingsset__account_uid__ms_e2a71b318d'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__accountholdingsset')),
    info={'namespace': 'mainsequence.markets', 'identifier': 'AccountHoldingsSet', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__accountholdingsset__account_uid'), 'ms_markets__accountholdingsset', ['account_uid'], unique=False)
    op.create_index(op.f('ix__ms_markets__accountholdingsset__time_index'), 'ms_markets__accountholdingsset', ['time_index'], unique=False)
    op.create_index(op.f('uix__ms_markets__accountholdingsset__account_uid__time_index'), 'ms_markets__accountholdingsset', ['account_uid', 'time_index'], unique=True)
    op.create_table('ms_markets__accounttargetallocation',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('unique_identifier', sa.String(length=255), nullable=False),
    sa.Column('account_uid', sa.Uuid(), nullable=False),
    sa.Column('account_allocation_model_uid', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['account_allocation_model_uid'], ['ms_markets__accountallocationmodel.uid'], name=op.f('fk__ms_markets__accounttargetallocation__account_all_3ad225212e'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['account_uid'], ['ms_markets__account.uid'], name=op.f('fk__ms_markets__accounttargetallocation__account_uid_39a0fc4ade'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__accounttargetallocation')),
    info={'namespace': 'mainsequence.markets', 'identifier': 'AccountTargetAllocation', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__accounttargetallocation__account_all_f241db4002'), 'ms_markets__accounttargetallocation', ['account_allocation_model_uid'], unique=False)
    op.create_index(op.f('ix__ms_markets__accounttargetallocation__account_uid'), 'ms_markets__accounttargetallocation', ['account_uid'], unique=False)
    op.create_index(op.f('ix__ms_markets__accounttargetallocation__is_active'), 'ms_markets__accounttargetallocation', ['is_active'], unique=False)
    op.create_index(op.f('uix__ms_markets__accounttargetallocation__unique_identifier'), 'ms_markets__accounttargetallocation', ['unique_identifier'], unique=True)
    op.create_table('ms_markets__curve',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('unique_identifier', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('curve_type', sa.String(length=64), nullable=False),
    sa.Column('index_uid', sa.Uuid(), nullable=False),
    sa.Column('interpolation_method', sa.String(length=64), nullable=True),
    sa.Column('compounding', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['index_uid'], ['ms_markets__indexconventiondetails.index_uid'], name=op.f('fk__ms_markets__curve__index_uid__ms_markets__indexc_c0f6b81568'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__curve')),
    info={'namespace': 'mainsequence.markets', 'identifier': 'Curve', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__curve__curve_type'), 'ms_markets__curve', ['curve_type'], unique=False)
    op.create_index(op.f('ix__ms_markets__curve__index_uid'), 'ms_markets__curve', ['index_uid'], unique=False)
    op.create_index(op.f('ix__ms_markets__curve__source'), 'ms_markets__curve', ['source'], unique=False)
    op.create_index(op.f('uix__ms_markets__curve__unique_identifier'), 'ms_markets__curve', ['unique_identifier'], unique=True)
    op.create_table('ms_markets__ordermanager',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('unique_identifier', sa.String(length=255), nullable=False),
    sa.Column('target_account_uid', sa.Uuid(), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('order_received_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['target_account_uid'], ['ms_markets__account.uid'], name=op.f('fk__ms_markets__ordermanager__target_account_uid__ms_54bb7bca6f'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__ordermanager')),
    info={'namespace': 'mainsequence.markets', 'identifier': 'OrderManager', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__ordermanager__status'), 'ms_markets__ordermanager', ['status'], unique=False)
    op.create_index(op.f('ix__ms_markets__ordermanager__target_account_uid'), 'ms_markets__ordermanager', ['target_account_uid'], unique=False)
    op.create_index(op.f('uix__ms_markets__ordermanager__unique_identifier'), 'ms_markets__ordermanager', ['unique_identifier'], unique=True)
    op.create_table('ms_markets__portfoliosts',
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.Column('portfolio_identifier', sa.String(length=255), nullable=False),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('return', sa.Float(), nullable=True),
    sa.Column('calculated_close', sa.Float(), nullable=True),
    sa.Column('close_time', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_identifier'], ['ms_markets__portfolio.unique_identifier'], name=op.f('fk__ms_markets__portfoliosts__portfolio_identifier_b1074f8062'), ondelete='RESTRICT'),
    info={'markets_storage_app': 'ms_markets', 'namespace': 'mainsequence.markets', 'identifier': 'PortfoliosTS'}
    )
    op.create_index('uix__ms_markets__portfoliosts__time_index__portfolio_identifier', 'ms_markets__portfoliosts', ['time_index', 'portfolio_identifier'], unique=True)
    op.create_table('ms_markets__virtualfund',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('unique_identifier', sa.String(length=255), nullable=False),
    sa.Column('account_uid', sa.Uuid(), nullable=False),
    sa.Column('target_portfolio_uid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['account_uid'], ['ms_markets__account.uid'], name=op.f('fk__ms_markets__virtualfund__account_uid__ms_markets_aff139259e'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_portfolio_uid'], ['ms_markets__portfolio.uid'], name=op.f('fk__ms_markets__virtualfund__target_portfolio_uid__m_829c99c153'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__virtualfund')),
    info={'namespace': 'mainsequence.markets', 'identifier': 'VirtualFund', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__virtualfund__account_uid'), 'ms_markets__virtualfund', ['account_uid'], unique=False)
    op.create_index(op.f('ix__ms_markets__virtualfund__target_portfolio_uid'), 'ms_markets__virtualfund', ['target_portfolio_uid'], unique=False)
    op.create_index(op.f('uix__ms_markets__virtualfund__unique_identifier'), 'ms_markets__virtualfund', ['unique_identifier'], unique=True)
    op.create_table('ms_markets__accountholdingsts',
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.Column('account_uid', sa.Uuid(), nullable=False),
    sa.Column('asset_identifier', sa.String(length=255), nullable=False),
    sa.Column('holdings_set_uid', sa.Uuid(), nullable=False),
    sa.Column('is_trade_snapshot', sa.Boolean(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('direction', sa.SmallInteger(), nullable=False),
    sa.Column('target_trade_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint('direction IN (1, -1)', name=op.f('ck__ms_markets__accountholdingsts__ck_account_holdin_5ad266251b')),
    sa.ForeignKeyConstraint(['account_uid'], ['ms_markets__account.uid'], name=op.f('fk__ms_markets__accountholdingsts__account_uid__ms_m_16e561105a'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['asset_identifier'], ['ms_markets__asset.unique_identifier'], name=op.f('fk__ms_markets__accountholdingsts__asset_identifier_59e659b7be'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['holdings_set_uid'], ['ms_markets__accountholdingsset.uid'], name=op.f('fk__ms_markets__accountholdingsts__holdings_set_uid_b7de9105a4'), ondelete='CASCADE'),
    info={'markets_storage_app': 'ms_markets', 'namespace': 'mainsequence.markets', 'identifier': 'AccountHoldingsTS'}
    )
    op.create_index('uix__ms_markets__accountholdingsts__time_index__acco_dc2e0ec020', 'ms_markets__accountholdingsts', ['time_index', 'account_uid', 'asset_identifier'], unique=True)
    op.create_table('ms_markets__discountcurvests',
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.Column('curve_identifier', sa.String(length=255), nullable=False),
    sa.Column('curve', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['curve_identifier'], ['ms_markets__curve.unique_identifier'], name=op.f('fk__ms_markets__discountcurvests__curve_identifier_0413caaa5f'), ondelete='RESTRICT'),
    info={'markets_storage_app': 'ms_markets', 'namespace': 'mainsequence.markets', 'identifier': 'DiscountCurvesTS'}
    )
    op.create_index('uix__ms_markets__discountcurvests__time_index__curve_identifier', 'ms_markets__discountcurvests', ['time_index', 'curve_identifier'], unique=True)
    op.create_table('ms_markets__positionset',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('account_target_allocation_uid', sa.Uuid(), nullable=False),
    sa.Column('position_set_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['account_target_allocation_uid'], ['ms_markets__accounttargetallocation.uid'], name=op.f('fk__ms_markets__positionset__account_target_allocati_ce4417ded1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__positionset')),
    info={'namespace': 'mainsequence.markets', 'identifier': 'PositionSet', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__positionset__account_target_allocation_uid'), 'ms_markets__positionset', ['account_target_allocation_uid'], unique=False)
    op.create_index(op.f('ix__ms_markets__positionset__position_set_time'), 'ms_markets__positionset', ['position_set_time'], unique=False)
    op.create_index(op.f('uix__ms_markets__positionset__account_target_allocat_655208003c'), 'ms_markets__positionset', ['account_target_allocation_uid', 'position_set_time'], unique=True)
    op.create_table('ms_markets__virtualfundholdingsset',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('virtual_fund_uid', sa.Uuid(), nullable=False),
    sa.Column('source_account_holdings_set_uid', sa.Uuid(), nullable=False),
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_account_holdings_set_uid'], ['ms_markets__accountholdingsset.uid'], name=op.f('fk__ms_markets__virtualfundholdingsset__source_accou_8cda520909'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['virtual_fund_uid'], ['ms_markets__virtualfund.uid'], name=op.f('fk__ms_markets__virtualfundholdingsset__virtual_fund_6d3a9e95bb'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__virtualfundholdingsset')),
    info={'namespace': 'mainsequence.markets', 'identifier': 'VirtualFundHoldingsSet', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__virtualfundholdingsset__source_accou_06924f9c22'), 'ms_markets__virtualfundholdingsset', ['source_account_holdings_set_uid'], unique=False)
    op.create_index(op.f('ix__ms_markets__virtualfundholdingsset__virtual_fund_uid'), 'ms_markets__virtualfundholdingsset', ['virtual_fund_uid'], unique=False)
    op.create_index(op.f('uix__ms_markets__virtualfundholdingsset__virtual_fun_dff1425c83'), 'ms_markets__virtualfundholdingsset', ['virtual_fund_uid', 'source_account_holdings_set_uid'], unique=True)
    op.create_table('ms_markets__targetpositionsts',
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.Column('position_set_uid', sa.Uuid(), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_uid', sa.Uuid(), nullable=False),
    sa.Column('asset_uid', sa.Uuid(), nullable=True),
    sa.Column('portfolio_uid', sa.Uuid(), nullable=True),
    sa.Column('weight_notional_exposure', sa.Float(), nullable=True),
    sa.Column('constant_notional_exposure', sa.Float(), nullable=True),
    sa.Column('single_asset_quantity', sa.Float(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("(target_type = 'asset' AND asset_uid IS NOT NULL AND portfolio_uid IS NULL AND target_uid = asset_uid) OR (target_type = 'portfolio' AND portfolio_uid IS NOT NULL AND asset_uid IS NULL AND target_uid = portfolio_uid)", name=op.f('ck__ms_markets__targetpositionsts__ck_target_positio_804f77878f')),
    sa.CheckConstraint("target_type IN ('asset', 'portfolio')", name=op.f('ck__ms_markets__targetpositionsts__ck_target_positio_3daf2e6c82')),
    sa.CheckConstraint('(CASE WHEN weight_notional_exposure IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN constant_notional_exposure IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN single_asset_quantity IS NOT NULL THEN 1 ELSE 0 END) = 1', name=op.f('ck__ms_markets__targetpositionsts__ck_target_positio_76b533764b')),
    sa.ForeignKeyConstraint(['asset_uid'], ['ms_markets__asset.uid'], name=op.f('fk__ms_markets__targetpositionsts__asset_uid__ms_mar_d18c80b341'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['portfolio_uid'], ['ms_markets__portfolio.uid'], name=op.f('fk__ms_markets__targetpositionsts__portfolio_uid__ms_fc069f94cf'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['position_set_uid'], ['ms_markets__positionset.uid'], name=op.f('fk__ms_markets__targetpositionsts__position_set_uid_ba3522b914'), ondelete='CASCADE'),
    info={'markets_storage_app': 'ms_markets', 'namespace': 'mainsequence.markets', 'identifier': 'TargetPositionsTS'}
    )
    op.create_index(op.f('ix__ms_markets__targetpositionsts__asset_uid'), 'ms_markets__targetpositionsts', ['asset_uid'], unique=False)
    op.create_index(op.f('ix__ms_markets__targetpositionsts__portfolio_uid'), 'ms_markets__targetpositionsts', ['portfolio_uid'], unique=False)
    op.create_index(op.f('ix__ms_markets__targetpositionsts__position_set_uid_e12d130813'), 'ms_markets__targetpositionsts', ['position_set_uid', 'target_type', 'target_uid'], unique=False)
    op.create_index('uix__ms_markets__targetpositionsts__time_index__posi_d64428cc34', 'ms_markets__targetpositionsts', ['time_index', 'position_set_uid', 'target_type', 'target_uid'], unique=True)
    op.create_table('ms_markets__virtualfundholdingsts',
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.Column('virtual_fund_uid', sa.Uuid(), nullable=False),
    sa.Column('asset_identifier', sa.String(length=255), nullable=False),
    sa.Column('virtual_fund_holdings_set_uid', sa.Uuid(), nullable=False),
    sa.Column('source_account_holdings_set_uid', sa.Uuid(), nullable=False),
    sa.Column('allocated_quantity', sa.Float(), nullable=False),
    sa.Column('allocation_strategy', sa.String(length=64), nullable=False),
    sa.Column('direction', sa.SmallInteger(), nullable=False),
    sa.Column('target_trade_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint('direction IN (1, -1)', name=op.f('ck__ms_markets__virtualfundholdingsts__ck_virtual_fu_0baf4f8e22')),
    sa.ForeignKeyConstraint(['asset_identifier'], ['ms_markets__asset.unique_identifier'], name=op.f('fk__ms_markets__virtualfundholdingsts__asset_identif_9a6a629329'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_account_holdings_set_uid'], ['ms_markets__accountholdingsset.uid'], name=op.f('fk__ms_markets__virtualfundholdingsts__source_accoun_f80c80eed8'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['virtual_fund_holdings_set_uid'], ['ms_markets__virtualfundholdingsset.uid'], name=op.f('fk__ms_markets__virtualfundholdingsts__virtual_fund_8833b421bd'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['virtual_fund_uid'], ['ms_markets__virtualfund.uid'], name=op.f('fk__ms_markets__virtualfundholdingsts__virtual_fund_611277f0e0'), ondelete='CASCADE'),
    info={'markets_storage_app': 'ms_markets', 'namespace': 'mainsequence.markets', 'identifier': 'VirtualFundHoldingsTS'}
    )
    op.create_index('uix__ms_markets__virtualfundholdingsts__time_index_3dd71cda5c', 'ms_markets__virtualfundholdingsts', ['time_index', 'virtual_fund_uid', 'asset_identifier'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uix__ms_markets__virtualfundholdingsts__time_index_3dd71cda5c', table_name='ms_markets__virtualfundholdingsts')
    op.drop_table('ms_markets__virtualfundholdingsts')
    op.drop_index('uix__ms_markets__targetpositionsts__time_index__posi_d64428cc34', table_name='ms_markets__targetpositionsts')
    op.drop_index(op.f('ix__ms_markets__targetpositionsts__position_set_uid_e12d130813'), table_name='ms_markets__targetpositionsts')
    op.drop_index(op.f('ix__ms_markets__targetpositionsts__portfolio_uid'), table_name='ms_markets__targetpositionsts')
    op.drop_index(op.f('ix__ms_markets__targetpositionsts__asset_uid'), table_name='ms_markets__targetpositionsts')
    op.drop_table('ms_markets__targetpositionsts')
    op.drop_index(op.f('uix__ms_markets__virtualfundholdingsset__virtual_fun_dff1425c83'), table_name='ms_markets__virtualfundholdingsset')
    op.drop_index(op.f('ix__ms_markets__virtualfundholdingsset__virtual_fund_uid'), table_name='ms_markets__virtualfundholdingsset')
    op.drop_index(op.f('ix__ms_markets__virtualfundholdingsset__source_accou_06924f9c22'), table_name='ms_markets__virtualfundholdingsset')
    op.drop_table('ms_markets__virtualfundholdingsset')
    op.drop_index(op.f('uix__ms_markets__positionset__account_target_allocat_655208003c'), table_name='ms_markets__positionset')
    op.drop_index(op.f('ix__ms_markets__positionset__position_set_time'), table_name='ms_markets__positionset')
    op.drop_index(op.f('ix__ms_markets__positionset__account_target_allocation_uid'), table_name='ms_markets__positionset')
    op.drop_table('ms_markets__positionset')
    op.drop_index('uix__ms_markets__discountcurvests__time_index__curve_identifier', table_name='ms_markets__discountcurvests')
    op.drop_table('ms_markets__discountcurvests')
    op.drop_index('uix__ms_markets__accountholdingsts__time_index__acco_dc2e0ec020', table_name='ms_markets__accountholdingsts')
    op.drop_table('ms_markets__accountholdingsts')
    op.drop_index(op.f('uix__ms_markets__virtualfund__unique_identifier'), table_name='ms_markets__virtualfund')
    op.drop_index(op.f('ix__ms_markets__virtualfund__target_portfolio_uid'), table_name='ms_markets__virtualfund')
    op.drop_index(op.f('ix__ms_markets__virtualfund__account_uid'), table_name='ms_markets__virtualfund')
    op.drop_table('ms_markets__virtualfund')
    op.drop_index('uix__ms_markets__portfoliosts__time_index__portfolio_identifier', table_name='ms_markets__portfoliosts')
    op.drop_table('ms_markets__portfoliosts')
    op.drop_index(op.f('uix__ms_markets__ordermanager__unique_identifier'), table_name='ms_markets__ordermanager')
    op.drop_index(op.f('ix__ms_markets__ordermanager__target_account_uid'), table_name='ms_markets__ordermanager')
    op.drop_index(op.f('ix__ms_markets__ordermanager__status'), table_name='ms_markets__ordermanager')
    op.drop_table('ms_markets__ordermanager')
    op.drop_index(op.f('uix__ms_markets__curve__unique_identifier'), table_name='ms_markets__curve')
    op.drop_index(op.f('ix__ms_markets__curve__source'), table_name='ms_markets__curve')
    op.drop_index(op.f('ix__ms_markets__curve__index_uid'), table_name='ms_markets__curve')
    op.drop_index(op.f('ix__ms_markets__curve__curve_type'), table_name='ms_markets__curve')
    op.drop_table('ms_markets__curve')
    op.drop_index(op.f('uix__ms_markets__accounttargetallocation__unique_identifier'), table_name='ms_markets__accounttargetallocation')
    op.drop_index(op.f('ix__ms_markets__accounttargetallocation__is_active'), table_name='ms_markets__accounttargetallocation')
    op.drop_index(op.f('ix__ms_markets__accounttargetallocation__account_uid'), table_name='ms_markets__accounttargetallocation')
    op.drop_index(op.f('ix__ms_markets__accounttargetallocation__account_all_f241db4002'), table_name='ms_markets__accounttargetallocation')
    op.drop_table('ms_markets__accounttargetallocation')
    op.drop_index(op.f('uix__ms_markets__accountholdingsset__account_uid__time_index'), table_name='ms_markets__accountholdingsset')
    op.drop_index(op.f('ix__ms_markets__accountholdingsset__time_index'), table_name='ms_markets__accountholdingsset')
    op.drop_index(op.f('ix__ms_markets__accountholdingsset__account_uid'), table_name='ms_markets__accountholdingsset')
    op.drop_table('ms_markets__accountholdingsset')
    op.drop_index('uix__ms_markets__signalweightsts__time_index__signal_94cdab9295', table_name='ms_markets__signalweightsts')
    op.drop_table('ms_markets__signalweightsts')
    op.drop_index(op.f('uix__ms_markets__pricingmarketdatasetbinding__market_7fb160d6c7'), table_name='ms_markets__pricingmarketdatasetbinding')
    op.drop_index(op.f('ix__ms_markets__pricingmarketdatasetbinding__data_node_uid'), table_name='ms_markets__pricingmarketdatasetbinding')
    op.drop_index(op.f('ix__ms_markets__pricingmarketdatasetbinding__concept_key'), table_name='ms_markets__pricingmarketdatasetbinding')
    op.drop_table('ms_markets__pricingmarketdatasetbinding')
    op.drop_index(op.f('uix__ms_markets__portfolio__unique_identifier'), table_name='ms_markets__portfolio')
    op.drop_index(op.f('ix__ms_markets__portfolio__published_index_uid'), table_name='ms_markets__portfolio')
    op.drop_index(op.f('ix__ms_markets__portfolio__calendar_uid'), table_name='ms_markets__portfolio')
    op.drop_index(op.f('ix__ms_markets__portfolio__calendar_name'), table_name='ms_markets__portfolio')
    op.drop_table('ms_markets__portfolio')
    op.drop_index(op.f('ix__ms_markets__openfigiassetdetails__ticker'), table_name='ms_markets__openfigiassetdetails')
    op.drop_index(op.f('ix__ms_markets__openfigiassetdetails__isin'), table_name='ms_markets__openfigiassetdetails')
    op.drop_index(op.f('ix__ms_markets__openfigiassetdetails__figi'), table_name='ms_markets__openfigiassetdetails')
    op.drop_table('ms_markets__openfigiassetdetails')
    op.drop_index('uix__ms_markets__interpolatedpricests__time_index__a_303e840ea7', table_name='ms_markets__interpolatedpricests')
    op.drop_table('ms_markets__interpolatedpricests')
    op.drop_index('uix__ms_markets__indexfixingsts__time_index__index_identifier', table_name='ms_markets__indexfixingsts')
    op.drop_table('ms_markets__indexfixingsts')
    op.drop_index(op.f('ix__ms_markets__indexconventiondetails__source'), table_name='ms_markets__indexconventiondetails')
    op.drop_index(op.f('ix__ms_markets__indexconventiondetails__index_family'), table_name='ms_markets__indexconventiondetails')
    op.drop_table('ms_markets__indexconventiondetails')
    op.drop_index(op.f('ix__ms_markets__futureassetdetails__underlying_index_uid'), table_name='ms_markets__futureassetdetails')
    op.drop_index(op.f('ix__ms_markets__futureassetdetails__settlement_asset'), table_name='ms_markets__futureassetdetails')
    op.drop_index(op.f('ix__ms_markets__futureassetdetails__margin_asset'), table_name='ms_markets__futureassetdetails')
    op.drop_index(op.f('ix__ms_markets__futureassetdetails__expires_at'), table_name='ms_markets__futureassetdetails')
    op.drop_table('ms_markets__futureassetdetails')
    op.drop_index('uix__ms_markets__externalpricests__time_index__asset_identifier', table_name='ms_markets__externalpricests')
    op.drop_table('ms_markets__externalpricests')
    op.drop_index(op.f('uix__ms_markets__currencyspotassetdetails__base_curr_c8929e9103'), table_name='ms_markets__currencyspotassetdetails')
    op.drop_index(op.f('ix__ms_markets__currencyspotassetdetails__quote_currency_uid'), table_name='ms_markets__currencyspotassetdetails')
    op.drop_index(op.f('ix__ms_markets__currencyspotassetdetails__base_currency_uid'), table_name='ms_markets__currencyspotassetdetails')
    op.drop_table('ms_markets__currencyspotassetdetails')
    op.drop_index(op.f('uix__ms_markets__calendarsession__calendar_uid__loca_30b16604ba'), table_name='ms_markets__calendarsession')
    op.drop_index(op.f('ix__ms_markets__calendarsession__local_date'), table_name='ms_markets__calendarsession')
    op.drop_index(op.f('ix__ms_markets__calendarsession__calendar_uid__is_primary'), table_name='ms_markets__calendarsession')
    op.drop_table('ms_markets__calendarsession')
    op.drop_index(op.f('uix__ms_markets__calendarevent__calendar_uid__event_5ff36d9c47'), table_name='ms_markets__calendarevent')
    op.drop_index(op.f('ix__ms_markets__calendarevent__target_type__target_uid'), table_name='ms_markets__calendarevent')
    op.drop_index(op.f('ix__ms_markets__calendarevent__event_type'), table_name='ms_markets__calendarevent')
    op.drop_index(op.f('ix__ms_markets__calendarevent__calendar_uid__event_date'), table_name='ms_markets__calendarevent')
    op.drop_table('ms_markets__calendarevent')
    op.drop_index(op.f('uix__ms_markets__calendardate__calendar_uid__local_date'), table_name='ms_markets__calendardate')
    op.drop_index(op.f('ix__ms_markets__calendardate__local_date'), table_name='ms_markets__calendardate')
    op.drop_index(op.f('ix__ms_markets__calendardate__calendar_uid__is_business_day'), table_name='ms_markets__calendardate')
    op.drop_table('ms_markets__calendardate')
    op.drop_index(op.f('ix__ms_markets__bondassetdetails__status'), table_name='ms_markets__bondassetdetails')
    op.drop_index(op.f('ix__ms_markets__bondassetdetails__maturity_date'), table_name='ms_markets__bondassetdetails')
    op.drop_index(op.f('ix__ms_markets__bondassetdetails__issuer_uid'), table_name='ms_markets__bondassetdetails')
    op.drop_index(op.f('ix__ms_markets__bondassetdetails__currency_asset_uid'), table_name='ms_markets__bondassetdetails')
    op.drop_table('ms_markets__bondassetdetails')
    op.drop_index('uix__ms_markets__assetsnapshotsts__time_index__asset_identifier', table_name='ms_markets__assetsnapshotsts')
    op.drop_table('ms_markets__assetsnapshotsts')
    op.drop_index('uix__ms_markets__assetpricingdetailsts__time_index_affb4cd407', table_name='ms_markets__assetpricingdetailsts')
    op.drop_table('ms_markets__assetpricingdetailsts')
    op.drop_index(op.f('ix__ms_markets__assetcurrentpricingdetails__pricing_dc942ad94f'), table_name='ms_markets__assetcurrentpricingdetails')
    op.drop_index(op.f('ix__ms_markets__assetcurrentpricingdetails__instrument_type'), table_name='ms_markets__assetcurrentpricingdetails')
    op.drop_table('ms_markets__assetcurrentpricingdetails')
    op.drop_index(op.f('uix__ms_markets__assetcategorymembership__category_u_0c42bc3572'), table_name='ms_markets__assetcategorymembership')
    op.drop_index(op.f('ix__ms_markets__assetcategorymembership__asset_uid'), table_name='ms_markets__assetcategorymembership')
    op.drop_table('ms_markets__assetcategorymembership')
    op.drop_index(op.f('uix__ms_markets__account__unique_identifier'), table_name='ms_markets__account')
    op.drop_index(op.f('ix__ms_markets__account__account_name'), table_name='ms_markets__account')
    op.drop_index(op.f('ix__ms_markets__account__account_is_active'), table_name='ms_markets__account')
    op.drop_index(op.f('ix__ms_markets__account__account_group_uid'), table_name='ms_markets__account')
    op.drop_table('ms_markets__account')
    op.drop_index('uix__ms_markets__tradests__trade_time__trade_identif_4ad9fea888', table_name='ms_markets__tradests')
    op.drop_table('ms_markets__tradests')
    op.drop_index(op.f('uix__ms_markets__signalmetadata__signal_uid'), table_name='ms_markets__signalmetadata')
    op.drop_table('ms_markets__signalmetadata')
    op.drop_index(op.f('uix__ms_markets__rebalancestrategymetadata__rebalanc_a097a6f535'), table_name='ms_markets__rebalancestrategymetadata')
    op.drop_table('ms_markets__rebalancestrategymetadata')
    op.drop_index(op.f('uix__ms_markets__pricingmarketdataset__set_key'), table_name='ms_markets__pricingmarketdataset')
    op.drop_index(op.f('ix__ms_markets__pricingmarketdataset__status'), table_name='ms_markets__pricingmarketdataset')
    op.drop_table('ms_markets__pricingmarketdataset')
    op.drop_index('uix__ms_markets__portfolioweightsts__time_index__por_d92475bae0', table_name='ms_markets__portfolioweightsts')
    op.drop_table('ms_markets__portfolioweightsts')
    op.drop_index(op.f('uix__ms_markets__portfoliometadata__unique_identifier'), table_name='ms_markets__portfoliometadata')
    op.drop_table('ms_markets__portfoliometadata')
    op.drop_index('uix__ms_markets__ordersts__order_time__order_identif_20c686be5c', table_name='ms_markets__ordersts')
    op.drop_table('ms_markets__ordersts')
    op.drop_index('uix__ms_markets__ordereventsts__event_time__order_identifier', table_name='ms_markets__ordereventsts')
    op.drop_table('ms_markets__ordereventsts')
    op.drop_index(op.f('uix__ms_markets__issuer__unique_identifier'), table_name='ms_markets__issuer')
    op.drop_index(op.f('ix__ms_markets__issuer__display_name'), table_name='ms_markets__issuer')
    op.drop_table('ms_markets__issuer')
    op.drop_index(op.f('uix__ms_markets__indextype__index_type'), table_name='ms_markets__indextype')
    op.drop_index(op.f('ix__ms_markets__indextype__display_name'), table_name='ms_markets__indextype')
    op.drop_table('ms_markets__indextype')
    op.drop_index(op.f('uix__ms_markets__index__unique_identifier'), table_name='ms_markets__index')
    op.drop_index(op.f('ix__ms_markets__index__provider'), table_name='ms_markets__index')
    op.drop_index(op.f('ix__ms_markets__index__index_type'), table_name='ms_markets__index')
    op.drop_index(op.f('ix__ms_markets__index__display_name'), table_name='ms_markets__index')
    op.drop_table('ms_markets__index')
    op.drop_index(op.f('uix__ms_markets__calendar__unique_identifier'), table_name='ms_markets__calendar')
    op.drop_index(op.f('ix__ms_markets__calendar__source__source_identifier'), table_name='ms_markets__calendar')
    op.drop_index(op.f('ix__ms_markets__calendar__calendar_type'), table_name='ms_markets__calendar')
    op.drop_table('ms_markets__calendar')
    op.drop_index(op.f('uix__ms_markets__assettype__asset_type'), table_name='ms_markets__assettype')
    op.drop_index(op.f('ix__ms_markets__assettype__display_name'), table_name='ms_markets__assettype')
    op.drop_table('ms_markets__assettype')
    op.drop_index(op.f('uix__ms_markets__assetcategory__unique_identifier'), table_name='ms_markets__assetcategory')
    op.drop_index(op.f('ix__ms_markets__assetcategory__display_name'), table_name='ms_markets__assetcategory')
    op.drop_table('ms_markets__assetcategory')
    op.drop_index(op.f('uix__ms_markets__asset__unique_identifier'), table_name='ms_markets__asset')
    op.drop_index(op.f('ix__ms_markets__asset__asset_type'), table_name='ms_markets__asset')
    op.drop_table('ms_markets__asset')
    op.drop_index(op.f('uix__ms_markets__accountgroup__group_name'), table_name='ms_markets__accountgroup')
    op.drop_table('ms_markets__accountgroup')
    op.drop_index(op.f('uix__ms_markets__accountallocationmodel__allocation_model_name'), table_name='ms_markets__accountallocationmodel')
    op.drop_table('ms_markets__accountallocationmodel')
    # ### end Alembic commands ###
