"""migration

Revision ID: 0002
Revises: 0001
Create Date: 2026-06-10 18:53:34.636971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk__ms_markets__ordersts__account_identifier__ms_mar_dc1a18e044'), 'ms_markets__ordersts', 'ms_markets__account', ['account_identifier'], ['unique_identifier'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk__ms_markets__ordersts__asset_identifier__ms_marke_e41085088a'), 'ms_markets__ordersts', 'ms_markets__asset', ['asset_identifier'], ['unique_identifier'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk__ms_markets__ordersts__order_manager_identifier_b80dd3d684'), 'ms_markets__ordersts', 'ms_markets__ordermanager', ['order_manager_identifier'], ['unique_identifier'], ondelete='RESTRICT')
    op.drop_column('ms_markets__ordersts', 'fund_identifier')
    op.create_foreign_key(op.f('fk__ms_markets__portfolioweightsts__portfolio_identi_2d183320e0'), 'ms_markets__portfolioweightsts', 'ms_markets__portfolio', ['portfolio_identifier'], ['unique_identifier'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk__ms_markets__portfolioweightsts__asset_identifier_589cee70db'), 'ms_markets__portfolioweightsts', 'ms_markets__asset', ['asset_identifier'], ['unique_identifier'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk__ms_markets__signalweightsts__asset_identifier__m_5ab737e205'), 'ms_markets__signalweightsts', 'ms_markets__asset', ['asset_identifier'], ['unique_identifier'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk__ms_markets__tradests__commission_asset_identifie_d3e610dd3a'), 'ms_markets__tradests', 'ms_markets__asset', ['commission_asset_identifier'], ['unique_identifier'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk__ms_markets__tradests__asset_identifier__ms_marke_a480feaac0'), 'ms_markets__tradests', 'ms_markets__asset', ['asset_identifier'], ['unique_identifier'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk__ms_markets__tradests__account_identifier__ms_mar_30086c4426'), 'ms_markets__tradests', 'ms_markets__account', ['account_identifier'], ['unique_identifier'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk__ms_markets__tradests__settlement_asset_identifie_7d43f1681c'), 'ms_markets__tradests', 'ms_markets__asset', ['settlement_asset_identifier'], ['unique_identifier'], ondelete='RESTRICT')
    op.drop_column('ms_markets__tradests', 'fund_identifier')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ms_markets__tradests', sa.Column('fund_identifier', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk__ms_markets__tradests__settlement_asset_identifie_7d43f1681c'), 'ms_markets__tradests', type_='foreignkey')
    op.drop_constraint(op.f('fk__ms_markets__tradests__account_identifier__ms_mar_30086c4426'), 'ms_markets__tradests', type_='foreignkey')
    op.drop_constraint(op.f('fk__ms_markets__tradests__asset_identifier__ms_marke_a480feaac0'), 'ms_markets__tradests', type_='foreignkey')
    op.drop_constraint(op.f('fk__ms_markets__tradests__commission_asset_identifie_d3e610dd3a'), 'ms_markets__tradests', type_='foreignkey')
    op.drop_constraint(op.f('fk__ms_markets__signalweightsts__asset_identifier__m_5ab737e205'), 'ms_markets__signalweightsts', type_='foreignkey')
    op.drop_constraint(op.f('fk__ms_markets__portfolioweightsts__asset_identifier_589cee70db'), 'ms_markets__portfolioweightsts', type_='foreignkey')
    op.drop_constraint(op.f('fk__ms_markets__portfolioweightsts__portfolio_identi_2d183320e0'), 'ms_markets__portfolioweightsts', type_='foreignkey')
    op.add_column('ms_markets__ordersts', sa.Column('fund_identifier', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk__ms_markets__ordersts__order_manager_identifier_b80dd3d684'), 'ms_markets__ordersts', type_='foreignkey')
    op.drop_constraint(op.f('fk__ms_markets__ordersts__asset_identifier__ms_marke_e41085088a'), 'ms_markets__ordersts', type_='foreignkey')
    op.drop_constraint(op.f('fk__ms_markets__ordersts__account_identifier__ms_mar_dc1a18e044'), 'ms_markets__ordersts', type_='foreignkey')
    # ### end Alembic commands ###
