"""make discount curve payload required

Revision ID: 0009
Revises: 0008
Create Date: 2026-07-01 11:32:32.774380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0009'
down_revision: Union[str, Sequence[str], None] = '0008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    null_curve_count = connection.execute(
        sa.text("SELECT count(*) FROM ms_markets__discountcurvests WHERE curve IS NULL")
    ).scalar_one()
    if null_curve_count:
        raise RuntimeError(
            "Cannot make ms_markets__discountcurvests.curve NOT NULL because "
            f"{null_curve_count} existing discount-curve observations have no "
            "compressed curve payload."
        )
    op.alter_column('ms_markets__discountcurvests', 'curve',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ms_markets__discountcurvests', 'curve',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
