"""derived_index_framework

Revision ID: 0011
Revises: 0010
Create Date: 2026-07-18 16:41:33.873877

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0011"
down_revision: Union[str, Sequence[str], None] = "0010"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ms_markets__indexcalculationdefinition",
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("index_uid", sa.Uuid(), nullable=False),
        sa.Column("definition_version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("calculation_kind", sa.String(length=64), nullable=False),
        sa.Column("calculation_family", sa.String(length=64), nullable=False),
        sa.Column("calculation_parameters_json", sa.JSON(), nullable=True),
        sa.Column("output_unit", sa.String(length=64), nullable=False),
        sa.Column("alignment_policy", sa.String(length=64), nullable=False),
        sa.Column("alignment_parameters_json", sa.JSON(), nullable=True),
        sa.Column("missing_data_policy", sa.String(length=64), nullable=False),
        sa.Column("missing_data_parameters_json", sa.JSON(), nullable=True),
        sa.Column("composition_mode", sa.String(length=32), nullable=False),
        sa.Column("rebalance_policy", sa.String(length=64), nullable=True),
        sa.Column("rebalance_parameters_json", sa.JSON(), nullable=True),
        sa.Column("definition_hash", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=255), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.CheckConstraint(
            "composition_mode IN ('fixed', 'rule_selected', 'rebalanced')",
            name=op.f("ck__ms_markets__indexcalculationdefinition__composit_bf73c53f3d"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'active', 'retired')",
            name=op.f("ck__ms_markets__indexcalculationdefinition__definiti_e3b8e77e03"),
        ),
        sa.CheckConstraint(
            "definition_version > 0",
            name=op.f("ck__ms_markets__indexcalculationdefinition__definiti_10c95eaaf7"),
        ),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_to > effective_from",
            name=op.f("ck__ms_markets__indexcalculationdefinition__effectiv_177fe45ba6"),
        ),
        sa.ForeignKeyConstraint(
            ["index_uid"],
            ["ms_markets__index.uid"],
            name=op.f("fk__ms_markets__indexcalculationdefinition__index_ui_a08c700ff3"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("uid", name=op.f("pk__ms_markets__indexcalculationdefinition")),
        info={
            "namespace": "mainsequence.markets",
            "identifier": "IndexCalculationDefinition",
            "markets_storage_app": "ms_markets",
        },
    )
    op.create_index(
        op.f("ix__ms_markets__indexcalculationdefinition__calculation_family"),
        "ms_markets__indexcalculationdefinition",
        ["calculation_family"],
        unique=False,
    )
    op.create_index(
        op.f("uix__ms_markets__indexcalculationdefinition__index_u_0840549a8f"),
        "ms_markets__indexcalculationdefinition",
        ["index_uid", "definition_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix__ms_markets__indexcalculationdefinition__effective_from"),
        "ms_markets__indexcalculationdefinition",
        ["effective_from"],
        unique=False,
    )
    op.create_index(
        op.f("ix__ms_markets__indexcalculationdefinition__index_uid"),
        "ms_markets__indexcalculationdefinition",
        ["index_uid"],
        unique=False,
    )
    op.create_index(
        op.f("ix__ms_markets__indexcalculationdefinition__status"),
        "ms_markets__indexcalculationdefinition",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("uix__ms_markets__indexcalculationdefinition__index_u_37d1a540c1"),
        "ms_markets__indexcalculationdefinition",
        ["index_uid", "definition_version"],
        unique=True,
    )
    op.create_table(
        "ms_markets__indexcalculationleg",
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("definition_uid", sa.Uuid(), nullable=False),
        sa.Column("leg_key", sa.String(length=64), nullable=False),
        sa.Column("leg_order", sa.Integer(), nullable=False),
        sa.Column("leg_role", sa.String(length=64), nullable=True),
        sa.Column("component_kind", sa.String(length=32), nullable=False),
        sa.Column("asset_uid", sa.Uuid(), nullable=True),
        sa.Column("component_index_uid", sa.Uuid(), nullable=True),
        sa.Column("selector_code", sa.String(length=64), nullable=True),
        sa.Column("selector_parameters_json", sa.JSON(), nullable=True),
        sa.Column("observable_code", sa.String(length=64), nullable=False),
        sa.Column("input_unit", sa.String(length=64), nullable=False),
        sa.Column("transform_code", sa.String(length=64), nullable=False),
        sa.Column("transform_parameters_json", sa.JSON(), nullable=True),
        sa.Column("coefficient_method", sa.String(length=64), nullable=False),
        sa.Column("coefficient", sa.Float(), nullable=True),
        sa.Column("coefficient_parameters_json", sa.JSON(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.CheckConstraint(
            "(coefficient_method = 'fixed' AND coefficient IS NOT NULL) OR (coefficient_method <> 'fixed' AND coefficient IS NULL)",
            name=op.f("ck__ms_markets__indexcalculationleg__coefficient_contract_valid"),
        ),
        sa.CheckConstraint(
            "(CASE WHEN asset_uid IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN component_index_uid IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN selector_code IS NOT NULL THEN 1 ELSE 0 END) = 1",
            name=op.f("ck__ms_markets__indexcalculationleg__component_source_exclusive"),
        ),
        sa.CheckConstraint(
            "leg_order >= 0",
            name=op.f("ck__ms_markets__indexcalculationleg__leg_order_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["asset_uid"],
            ["ms_markets__asset.uid"],
            name=op.f("fk__ms_markets__indexcalculationleg__asset_uid__ms_m_85090b9224"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["component_index_uid"],
            ["ms_markets__index.uid"],
            name=op.f("fk__ms_markets__indexcalculationleg__component_index_a1673e8c1a"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["definition_uid"],
            ["ms_markets__indexcalculationdefinition.uid"],
            name=op.f("fk__ms_markets__indexcalculationleg__definition_uid_9cf16af7e8"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("uid", name=op.f("pk__ms_markets__indexcalculationleg")),
        info={
            "namespace": "mainsequence.markets",
            "identifier": "IndexCalculationLeg",
            "markets_storage_app": "ms_markets",
        },
    )
    op.create_index(
        op.f("ix__ms_markets__indexcalculationleg__asset_uid"),
        "ms_markets__indexcalculationleg",
        ["asset_uid"],
        unique=False,
    )
    op.create_index(
        op.f("ix__ms_markets__indexcalculationleg__component_index_uid"),
        "ms_markets__indexcalculationleg",
        ["component_index_uid"],
        unique=False,
    )
    op.create_index(
        op.f("ix__ms_markets__indexcalculationleg__selector_code"),
        "ms_markets__indexcalculationleg",
        ["selector_code"],
        unique=False,
    )
    op.create_index(
        op.f("uix__ms_markets__indexcalculationleg__definition_uid__leg_key"),
        "ms_markets__indexcalculationleg",
        ["definition_uid", "leg_key"],
        unique=True,
    )
    op.create_index(
        op.f("uix__ms_markets__indexcalculationleg__definition_uid__leg_order"),
        "ms_markets__indexcalculationleg",
        ["definition_uid", "leg_order"],
        unique=True,
    )
    op.create_table(
        "ms_markets__indexresolvedlegsts",
        sa.Column("time_index", sa.DateTime(timezone=True), nullable=False),
        sa.Column("index_identifier", sa.String(length=255), nullable=False),
        sa.Column("definition_uid", sa.Uuid(), nullable=False),
        sa.Column("leg_key", sa.String(length=64), nullable=False),
        sa.Column("resolved_component_key", sa.String(length=255), nullable=False),
        sa.Column("component_kind", sa.String(length=32), nullable=False),
        sa.Column("resolved_coefficient", sa.Float(), nullable=False),
        sa.Column("coefficient_method", sa.String(length=64), nullable=False),
        sa.Column("observable_code", sa.String(length=64), nullable=False),
        sa.Column("source_observation_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution_status", sa.String(length=32), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.CheckConstraint(
            "component_kind IN ('asset', 'index')",
            name=op.f("ck__ms_markets__indexresolvedlegsts__resolved_compon_c4e9f6a222"),
        ),
        sa.ForeignKeyConstraint(
            ["definition_uid"],
            ["ms_markets__indexcalculationdefinition.uid"],
            name=op.f("fk__ms_markets__indexresolvedlegsts__definition_uid_de6d33624e"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["index_identifier"],
            ["ms_markets__index.unique_identifier"],
            name=op.f("fk__ms_markets__indexresolvedlegsts__index_identifie_06fc4f127f"),
            ondelete="RESTRICT",
        ),
        info={
            "markets_storage_app": "ms_markets",
            "namespace": "mainsequence.markets",
            "identifier": "IndexResolvedLegsTS",
        },
    )
    op.create_index(
        op.f("ix__ms_markets__indexresolvedlegsts__definition_uid"),
        "ms_markets__indexresolvedlegsts",
        ["definition_uid"],
        unique=False,
    )
    op.create_index(
        op.f("ix__ms_markets__indexresolvedlegsts__resolution_status"),
        "ms_markets__indexresolvedlegsts",
        ["resolution_status"],
        unique=False,
    )
    op.create_index(
        "uix__ms_markets__indexresolvedlegsts__time_index__in_14106b6d52",
        "ms_markets__indexresolvedlegsts",
        ["time_index", "index_identifier", "leg_key", "resolved_component_key"],
        unique=True,
    )
    op.create_table(
        "ms_markets__indexvaluests",
        sa.Column("time_index", sa.DateTime(timezone=True), nullable=False),
        sa.Column("index_identifier", sa.String(length=255), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(length=64), nullable=False),
        sa.Column("definition_uid", sa.Uuid(), nullable=False),
        sa.Column("calculation_status", sa.String(length=32), nullable=False),
        sa.Column("source_as_of", sa.DateTime(timezone=True), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["definition_uid"],
            ["ms_markets__indexcalculationdefinition.uid"],
            name=op.f("fk__ms_markets__indexvaluests__definition_uid__ms_ma_3500b75a57"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["index_identifier"],
            ["ms_markets__index.unique_identifier"],
            name=op.f("fk__ms_markets__indexvaluests__index_identifier__ms_dc817632b8"),
            ondelete="RESTRICT",
        ),
        info={
            "markets_storage_app": "ms_markets",
            "namespace": "mainsequence.markets",
            "identifier": "IndexValuesTS",
        },
    )
    op.create_index(
        op.f("ix__ms_markets__indexvaluests__calculation_status"),
        "ms_markets__indexvaluests",
        ["calculation_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix__ms_markets__indexvaluests__definition_uid"),
        "ms_markets__indexvaluests",
        ["definition_uid"],
        unique=False,
    )
    op.create_index(
        "uix__ms_markets__indexvaluests__time_index__index_identifier",
        "ms_markets__indexvaluests",
        ["time_index", "index_identifier"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uix__ms_markets__indexvaluests__time_index__index_identifier",
        table_name="ms_markets__indexvaluests",
    )
    op.drop_index(
        op.f("ix__ms_markets__indexvaluests__definition_uid"),
        table_name="ms_markets__indexvaluests",
    )
    op.drop_index(
        op.f("ix__ms_markets__indexvaluests__calculation_status"),
        table_name="ms_markets__indexvaluests",
    )
    op.drop_table("ms_markets__indexvaluests")
    op.drop_index(
        "uix__ms_markets__indexresolvedlegsts__time_index__in_14106b6d52",
        table_name="ms_markets__indexresolvedlegsts",
    )
    op.drop_index(
        op.f("ix__ms_markets__indexresolvedlegsts__resolution_status"),
        table_name="ms_markets__indexresolvedlegsts",
    )
    op.drop_index(
        op.f("ix__ms_markets__indexresolvedlegsts__definition_uid"),
        table_name="ms_markets__indexresolvedlegsts",
    )
    op.drop_table("ms_markets__indexresolvedlegsts")
    op.drop_index(
        op.f("uix__ms_markets__indexcalculationleg__definition_uid__leg_order"),
        table_name="ms_markets__indexcalculationleg",
    )
    op.drop_index(
        op.f("uix__ms_markets__indexcalculationleg__definition_uid__leg_key"),
        table_name="ms_markets__indexcalculationleg",
    )
    op.drop_index(
        op.f("ix__ms_markets__indexcalculationleg__selector_code"),
        table_name="ms_markets__indexcalculationleg",
    )
    op.drop_index(
        op.f("ix__ms_markets__indexcalculationleg__component_index_uid"),
        table_name="ms_markets__indexcalculationleg",
    )
    op.drop_index(
        op.f("ix__ms_markets__indexcalculationleg__asset_uid"),
        table_name="ms_markets__indexcalculationleg",
    )
    op.drop_table("ms_markets__indexcalculationleg")
    op.drop_index(
        op.f("uix__ms_markets__indexcalculationdefinition__index_u_37d1a540c1"),
        table_name="ms_markets__indexcalculationdefinition",
    )
    op.drop_index(
        op.f("ix__ms_markets__indexcalculationdefinition__status"),
        table_name="ms_markets__indexcalculationdefinition",
    )
    op.drop_index(
        op.f("ix__ms_markets__indexcalculationdefinition__index_uid"),
        table_name="ms_markets__indexcalculationdefinition",
    )
    op.drop_index(
        op.f("ix__ms_markets__indexcalculationdefinition__effective_from"),
        table_name="ms_markets__indexcalculationdefinition",
    )
    op.drop_index(
        op.f("uix__ms_markets__indexcalculationdefinition__index_u_0840549a8f"),
        table_name="ms_markets__indexcalculationdefinition",
    )
    op.drop_index(
        op.f("ix__ms_markets__indexcalculationdefinition__calculation_family"),
        table_name="ms_markets__indexcalculationdefinition",
    )
    op.drop_table("ms_markets__indexcalculationdefinition")
    # ### end Alembic commands ###
