"""migration

Revision ID: 0001
Revises: 
Create Date: 2026-06-07 18:29:03.925292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ms_markets__accountallocationmodel__mainsequence_examples',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('allocation_model_name', sa.String(length=100), nullable=False),
    sa.Column('allocation_model_description', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__accountallocationmodel__mainsequence_examples')),
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.AccountAllocationModel', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('uix__ms_markets__accountallocationmodel__mainsequenc_d5d6816908'), 'ms_markets__accountallocationmodel__mainsequence_examples', ['allocation_model_name'], unique=True)
    op.create_table('ms_markets__accountgroup__mainsequence_examples',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('group_name', sa.String(length=100), nullable=True),
    sa.Column('group_description', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__accountgroup__mainsequence_examples')),
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.AccountGroup', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('uix__ms_markets__accountgroup__mainsequence_examples_a47462aee6'), 'ms_markets__accountgroup__mainsequence_examples', ['group_name'], unique=True)
    op.create_table('ms_markets__asset__mainsequence_examples',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('unique_identifier', sa.String(length=255), nullable=False),
    sa.Column('asset_type', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__asset__mainsequence_examples')),
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.Asset', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__asset__mainsequence_examples__asset_type'), 'ms_markets__asset__mainsequence_examples', ['asset_type'], unique=False)
    op.create_index(op.f('uix__ms_markets__asset__mainsequence_examples__uniqu_b17b6bd854'), 'ms_markets__asset__mainsequence_examples', ['unique_identifier'], unique=True)
    op.create_table('ms_markets__assetcategory__mainsequence_examples',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('unique_identifier', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__assetcategory__mainsequence_examples')),
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.AssetCategory', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__assetcategory__mainsequence_examples_8cef4665e2'), 'ms_markets__assetcategory__mainsequence_examples', ['display_name'], unique=False)
    op.create_index(op.f('uix__ms_markets__assetcategory__mainsequence_example_657fa45c6f'), 'ms_markets__assetcategory__mainsequence_examples', ['unique_identifier'], unique=True)
    op.create_table('ms_markets__assettype__mainsequence_examples',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('asset_type', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__assettype__mainsequence_examples')),
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.AssetType', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__assettype__mainsequence_examples__display_name'), 'ms_markets__assettype__mainsequence_examples', ['display_name'], unique=False)
    op.create_index(op.f('uix__ms_markets__assettype__mainsequence_examples__asset_type'), 'ms_markets__assettype__mainsequence_examples', ['asset_type'], unique=True)
    op.create_table('ms_markets__calendar__mainsequence_examples',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('unique_identifier', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('calendar_type', sa.String(length=64), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('source_identifier', sa.String(length=255), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__calendar__mainsequence_examples')),
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.Calendar', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__calendar__mainsequence_examples__calendar_type'), 'ms_markets__calendar__mainsequence_examples', ['calendar_type'], unique=False)
    op.create_index(op.f('ix__ms_markets__calendar__mainsequence_examples__sou_2ddf7c50e9'), 'ms_markets__calendar__mainsequence_examples', ['source', 'source_identifier'], unique=False)
    op.create_index(op.f('uix__ms_markets__calendar__mainsequence_examples__un_b900d44ed4'), 'ms_markets__calendar__mainsequence_examples', ['unique_identifier'], unique=True)
    op.create_table('ms_markets__externalpricests__mainsequence_examples',
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.Column('asset_identifier', sa.String(), nullable=False),
    sa.Column('open_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('trade_count', sa.Float(), nullable=True),
    sa.Column('vwap', sa.Float(), nullable=True),
    sa.Column('interpolated', sa.Boolean(), nullable=True),
    info={'markets_storage_app': 'ms_markets'}
    )
    op.create_index('uix__ms_markets__externalpricests__mainsequence_exam_bdce163d05', 'ms_markets__externalpricests__mainsequence_examples', ['time_index', 'asset_identifier'], unique=True)
    op.create_table('ms_markets__index__mainsequence_examples',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('unique_identifier', sa.String(length=255), nullable=False),
    sa.Column('index_type', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__index__mainsequence_examples')),
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.Index', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__index__mainsequence_examples__display_name'), 'ms_markets__index__mainsequence_examples', ['display_name'], unique=False)
    op.create_index(op.f('ix__ms_markets__index__mainsequence_examples__index_type'), 'ms_markets__index__mainsequence_examples', ['index_type'], unique=False)
    op.create_index(op.f('ix__ms_markets__index__mainsequence_examples__provider'), 'ms_markets__index__mainsequence_examples', ['provider'], unique=False)
    op.create_index(op.f('uix__ms_markets__index__mainsequence_examples__uniqu_ba58bcb4d0'), 'ms_markets__index__mainsequence_examples', ['unique_identifier'], unique=True)
    op.create_table('ms_markets__indextype__mainsequence_examples',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('index_type', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__indextype__mainsequence_examples')),
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.IndexType', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__indextype__mainsequence_examples__display_name'), 'ms_markets__indextype__mainsequence_examples', ['display_name'], unique=False)
    op.create_index(op.f('uix__ms_markets__indextype__mainsequence_examples__index_type'), 'ms_markets__indextype__mainsequence_examples', ['index_type'], unique=True)
    op.create_table('ms_markets__interpolatedpricests__mainsequence_examples',
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.Column('asset_identifier', sa.String(), nullable=False),
    sa.Column('open_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('trade_count', sa.Float(), nullable=True),
    sa.Column('vwap', sa.Float(), nullable=True),
    sa.Column('interpolated', sa.Boolean(), nullable=True),
    info={'markets_storage_app': 'ms_markets'}
    )
    op.create_index('uix__ms_markets__interpolatedpricests__mainsequence_34f03829ba', 'ms_markets__interpolatedpricests__mainsequence_examples', ['time_index', 'asset_identifier'], unique=True)
    op.create_table('ms_markets__issuer__mainsequence_examples',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('unique_identifier', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__issuer__mainsequence_examples')),
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.Issuer', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__issuer__mainsequence_examples__display_name'), 'ms_markets__issuer__mainsequence_examples', ['display_name'], unique=False)
    op.create_index(op.f('uix__ms_markets__issuer__mainsequence_examples__uniq_5f112eb7b5'), 'ms_markets__issuer__mainsequence_examples', ['unique_identifier'], unique=True)
    op.create_table('ms_markets__ordereventsts__mainsequence_examples',
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('order_identifier', sa.String(), nullable=False),
    sa.Column('order_status', sa.String(), nullable=True),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    info={'markets_storage_app': 'ms_markets'}
    )
    op.create_index('uix__ms_markets__ordereventsts__mainsequence_example_e5d5b7267c', 'ms_markets__ordereventsts__mainsequence_examples', ['event_time', 'order_identifier'], unique=True)
    op.create_table('ms_markets__ordersts__mainsequence_examples',
    sa.Column('order_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('order_identifier', sa.String(), nullable=False),
    sa.Column('account_identifier', sa.String(), nullable=False),
    sa.Column('fund_identifier', sa.String(), nullable=True),
    sa.Column('order_manager_identifier', sa.String(), nullable=True),
    sa.Column('asset_identifier', sa.String(), nullable=False),
    sa.Column('order_remote_id', sa.String(), nullable=True),
    sa.Column('client_order_id', sa.String(), nullable=True),
    sa.Column('order_type', sa.String(), nullable=True),
    sa.Column('order_side', sa.BigInteger(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('filled_quantity', sa.Float(), nullable=True),
    sa.Column('filled_price', sa.Float(), nullable=True),
    sa.Column('expires_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('limit_price', sa.Float(), nullable=True),
    sa.Column('time_in_force', sa.String(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('venue_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    info={'markets_storage_app': 'ms_markets'}
    )
    op.create_index('uix__ms_markets__ordersts__mainsequence_examples__or_175e488d61', 'ms_markets__ordersts__mainsequence_examples', ['order_time', 'order_identifier', 'account_identifier', 'asset_identifier'], unique=True)
    op.create_table('ms_markets__portfoliometadata__mainsequence_examples',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('unique_identifier', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__portfoliometadata__mainsequence_examples')),
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.PortfolioMetadata', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('uix__ms_markets__portfoliometadata__mainsequence_exa_a8c57177f8'), 'ms_markets__portfoliometadata__mainsequence_examples', ['unique_identifier'], unique=True)
    op.create_table('ms_markets__portfoliosts__mainsequence_examples',
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.Column('portfolio_identifier', sa.String(), nullable=False),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('return', sa.Float(), nullable=True),
    sa.Column('calculated_close', sa.Float(), nullable=True),
    sa.Column('close_time', sa.DateTime(timezone=True), nullable=True),
    info={'markets_storage_app': 'ms_markets'}
    )
    op.create_index('uix__ms_markets__portfoliosts__mainsequence_examples_18eda21ee1', 'ms_markets__portfoliosts__mainsequence_examples', ['time_index', 'portfolio_identifier'], unique=True)
    op.create_table('ms_markets__portfolioweightsts__mainsequence_examples',
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.Column('portfolio_index_identifier', sa.String(), nullable=False),
    sa.Column('asset_identifier', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('weight_before', sa.Float(), nullable=True),
    sa.Column('price_current', sa.Float(), nullable=True),
    sa.Column('price_before', sa.Float(), nullable=True),
    sa.Column('volume_current', sa.Float(), nullable=True),
    sa.Column('volume_before', sa.Float(), nullable=True),
    info={'markets_storage_app': 'ms_markets'}
    )
    op.create_index('uix__ms_markets__portfolioweightsts__mainsequence_ex_c1365e7560', 'ms_markets__portfolioweightsts__mainsequence_examples', ['time_index', 'portfolio_index_identifier', 'asset_identifier'], unique=True)
    op.create_table('ms_markets__pricingmarketdataset__mainsequence_examples',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('set_key', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__pricingmarketdataset__mainsequence_examples')),
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.PricingMarketDataSet', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__pricingmarketdataset__mainsequence_e_4960208f20'), 'ms_markets__pricingmarketdataset__mainsequence_examples', ['status'], unique=False)
    op.create_index(op.f('uix__ms_markets__pricingmarketdataset__mainsequence_1a99e61cba'), 'ms_markets__pricingmarketdataset__mainsequence_examples', ['set_key'], unique=True)
    op.create_table('ms_markets__rebalancestrategymetadata__mainsequence_examples',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('rebalance_strategy_uid', sa.String(length=255), nullable=False),
    sa.Column('rebalance_strategy_description', sa.Text(), nullable=True),
    sa.Column('configuration_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__rebalancestrategymetadata__mainseque_152999e6b6')),
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.RebalanceStrategyMetadata', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('uix__ms_markets__rebalancestrategymetadata__mainsequ_6b6ca232fc'), 'ms_markets__rebalancestrategymetadata__mainsequence_examples', ['rebalance_strategy_uid'], unique=True)
    op.create_table('ms_markets__signalmetadata__mainsequence_examples',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('signal_uid', sa.String(length=255), nullable=False),
    sa.Column('signal_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__signalmetadata__mainsequence_examples')),
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.SignalMetadata', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('uix__ms_markets__signalmetadata__mainsequence_exampl_3074904c43'), 'ms_markets__signalmetadata__mainsequence_examples', ['signal_uid'], unique=True)
    op.create_table('ms_markets__signalweightsts__mainsequence_examples',
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signal_uid', sa.String(), nullable=False),
    sa.Column('asset_identifier', sa.String(), nullable=False),
    sa.Column('signal_weight', sa.Float(), nullable=True),
    info={'markets_storage_app': 'ms_markets'}
    )
    op.create_index('uix__ms_markets__signalweightsts__mainsequence_examp_486fb6308a', 'ms_markets__signalweightsts__mainsequence_examples', ['time_index', 'signal_uid', 'asset_identifier'], unique=True)
    op.create_table('ms_markets__tradests__mainsequence_examples',
    sa.Column('trade_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trade_identifier', sa.String(), nullable=False),
    sa.Column('account_identifier', sa.String(), nullable=False),
    sa.Column('fund_identifier', sa.String(), nullable=True),
    sa.Column('order_identifier', sa.String(), nullable=True),
    sa.Column('asset_identifier', sa.String(), nullable=False),
    sa.Column('trade_side', sa.BigInteger(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('commission_asset_identifier', sa.String(), nullable=True),
    sa.Column('settlement_cost', sa.Float(), nullable=True),
    sa.Column('settlement_asset_identifier', sa.String(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('venue_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    info={'markets_storage_app': 'ms_markets'}
    )
    op.create_index('uix__ms_markets__tradests__mainsequence_examples__tr_7ad1af6c1a', 'ms_markets__tradests__mainsequence_examples', ['trade_time', 'trade_identifier', 'account_identifier', 'asset_identifier'], unique=True)
    op.create_table('ms_markets__account__mainsequence_examples',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('unique_identifier', sa.String(length=255), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('is_paper', sa.Boolean(), nullable=False),
    sa.Column('account_is_active', sa.Boolean(), nullable=False),
    sa.Column('account_group_uid', sa.Uuid(), nullable=True),
    sa.Column('holdings_data_node_uid', sa.Uuid(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['account_group_uid'], ['ms_markets__accountgroup__mainsequence_examples.uid'], name=op.f('fk__ms_markets__account__mainsequence_examples__acco_b069423eb9'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__account__mainsequence_examples')),
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.Account', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__account__mainsequence_examples__acco_78c7641f5d'), 'ms_markets__account__mainsequence_examples', ['account_is_active'], unique=False)
    op.create_index(op.f('ix__ms_markets__account__mainsequence_examples__acco_94d0c32b9b'), 'ms_markets__account__mainsequence_examples', ['account_group_uid'], unique=False)
    op.create_index(op.f('ix__ms_markets__account__mainsequence_examples__account_name'), 'ms_markets__account__mainsequence_examples', ['account_name'], unique=False)
    op.create_index(op.f('uix__ms_markets__account__mainsequence_examples__uni_a15bc62da9'), 'ms_markets__account__mainsequence_examples', ['unique_identifier'], unique=True)
    op.create_table('ms_markets__assetcategorymembership__mainsequence_examples',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('category_uid', sa.Uuid(), nullable=False),
    sa.Column('asset_uid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['asset_uid'], ['ms_markets__asset__mainsequence_examples.uid'], name=op.f('fk__ms_markets__assetcategorymembership__mainsequenc_4b1100681a'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_uid'], ['ms_markets__assetcategory__mainsequence_examples.uid'], name=op.f('fk__ms_markets__assetcategorymembership__mainsequenc_ff681f7a01'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__assetcategorymembership__mainsequence_examples')),
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.AssetCategoryMembership', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__assetcategorymembership__mainsequenc_b8154287aa'), 'ms_markets__assetcategorymembership__mainsequence_examples', ['asset_uid'], unique=False)
    op.create_index(op.f('uix__ms_markets__assetcategorymembership__mainsequen_9d5443b2cc'), 'ms_markets__assetcategorymembership__mainsequence_examples', ['category_uid', 'asset_uid'], unique=True)
    op.create_table('ms_markets__assetcurrentpricingdetails__mainsequence_examples',
    sa.Column('asset_uid', sa.Uuid(), nullable=False),
    sa.Column('instrument_type', sa.String(length=128), nullable=False),
    sa.Column('instrument_dump', sa.JSON(), nullable=False),
    sa.Column('pricing_details_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('serialization_format', sa.String(length=128), nullable=False),
    sa.Column('pricing_package_version', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['asset_uid'], ['ms_markets__asset__mainsequence_examples.uid'], name=op.f('fk__ms_markets__assetcurrentpricingdetails__mainsequ_f7b8e60f34'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_uid', name=op.f('pk__ms_markets__assetcurrentpricingdetails__mainsequ_d6444fc189')),
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.AssetCurrentPricingDetails', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__assetcurrentpricingdetails__mainsequ_2a92d6c31f'), 'ms_markets__assetcurrentpricingdetails__mainsequence_examples', ['instrument_type'], unique=False)
    op.create_index(op.f('ix__ms_markets__assetcurrentpricingdetails__mainsequ_a2d063f2aa'), 'ms_markets__assetcurrentpricingdetails__mainsequence_examples', ['pricing_details_date'], unique=False)
    op.create_table('ms_markets__assetpricingdetailsts__mainsequence_examples',
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.Column('asset_identifier', sa.String(length=255), nullable=False),
    sa.Column('instrument_dump', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['asset_identifier'], ['ms_markets__asset__mainsequence_examples.unique_identifier'], name=op.f('fk__ms_markets__assetpricingdetailsts__mainsequence_edf5c6cb98'), ondelete='RESTRICT'),
    info={'markets_storage_app': 'ms_markets'}
    )
    op.create_index('uix__ms_markets__assetpricingdetailsts__mainsequence_3f465e3beb', 'ms_markets__assetpricingdetailsts__mainsequence_examples', ['time_index', 'asset_identifier'], unique=True)
    op.create_table('ms_markets__assetsnapshotsts__mainsequence_examples',
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.Column('asset_identifier', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('exchange_code', sa.String(), nullable=True),
    sa.Column('asset_ticker_group_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['asset_identifier'], ['ms_markets__asset__mainsequence_examples.unique_identifier'], name=op.f('fk__ms_markets__assetsnapshotsts__mainsequence_examp_928209cef0'), ondelete='RESTRICT'),
    info={'markets_storage_app': 'ms_markets'}
    )
    op.create_index('uix__ms_markets__assetsnapshotsts__mainsequence_exam_21493f481e', 'ms_markets__assetsnapshotsts__mainsequence_examples', ['time_index', 'asset_identifier'], unique=True)
    op.create_table('ms_markets__bondassetdetails__mainsequence_examples',
    sa.Column('asset_uid', sa.Uuid(), nullable=False),
    sa.Column('issuer_uid', sa.Uuid(), nullable=False),
    sa.Column('currency_asset_uid', sa.Uuid(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['asset_uid'], ['ms_markets__asset__mainsequence_examples.uid'], name=op.f('fk__ms_markets__bondassetdetails__mainsequence_examp_4c248ca7d2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['currency_asset_uid'], ['ms_markets__asset__mainsequence_examples.uid'], name=op.f('fk__ms_markets__bondassetdetails__mainsequence_examp_a4a0a7b2dc'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['issuer_uid'], ['ms_markets__issuer__mainsequence_examples.uid'], name=op.f('fk__ms_markets__bondassetdetails__mainsequence_examp_8e3aacbbf1'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('asset_uid', name=op.f('pk__ms_markets__bondassetdetails__mainsequence_examples')),
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.BondAssetDetails', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__bondassetdetails__mainsequence_examp_07099ef1be'), 'ms_markets__bondassetdetails__mainsequence_examples', ['currency_asset_uid'], unique=False)
    op.create_index(op.f('ix__ms_markets__bondassetdetails__mainsequence_examp_21045e0336'), 'ms_markets__bondassetdetails__mainsequence_examples', ['issuer_uid'], unique=False)
    op.create_index(op.f('ix__ms_markets__bondassetdetails__mainsequence_examp_fb406959be'), 'ms_markets__bondassetdetails__mainsequence_examples', ['maturity_date'], unique=False)
    op.create_index(op.f('ix__ms_markets__bondassetdetails__mainsequence_examples__status'), 'ms_markets__bondassetdetails__mainsequence_examples', ['status'], unique=False)
    op.create_table('ms_markets__calendardate__mainsequence_examples',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('calendar_uid', sa.Uuid(), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('is_business_day', sa.Boolean(), nullable=False),
    sa.Column('is_holiday', sa.Boolean(), nullable=False),
    sa.Column('is_weekend', sa.Boolean(), nullable=False),
    sa.Column('is_early_close', sa.Boolean(), nullable=False),
    sa.Column('holiday_name', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['calendar_uid'], ['ms_markets__calendar__mainsequence_examples.uid'], name=op.f('fk__ms_markets__calendardate__mainsequence_examples_139944a94b'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__calendardate__mainsequence_examples')),
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.CalendarDate', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__calendardate__mainsequence_examples_655c235a4b'), 'ms_markets__calendardate__mainsequence_examples', ['calendar_uid', 'is_business_day'], unique=False)
    op.create_index(op.f('ix__ms_markets__calendardate__mainsequence_examples__local_date'), 'ms_markets__calendardate__mainsequence_examples', ['local_date'], unique=False)
    op.create_index(op.f('uix__ms_markets__calendardate__mainsequence_examples_3928e12e5f'), 'ms_markets__calendardate__mainsequence_examples', ['calendar_uid', 'local_date'], unique=True)
    op.create_table('ms_markets__calendarevent__mainsequence_examples',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('calendar_uid', sa.Uuid(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('event_label', sa.String(length=255), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_uid', sa.Uuid(), nullable=True),
    sa.Column('target_identifier', sa.String(length=255), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['calendar_uid'], ['ms_markets__calendar__mainsequence_examples.uid'], name=op.f('fk__ms_markets__calendarevent__mainsequence_examples_ed8bfdf31a'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__calendarevent__mainsequence_examples')),
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.CalendarEvent', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__calendarevent__mainsequence_examples_11efc7e898'), 'ms_markets__calendarevent__mainsequence_examples', ['event_type'], unique=False)
    op.create_index(op.f('ix__ms_markets__calendarevent__mainsequence_examples_63b477ee1a'), 'ms_markets__calendarevent__mainsequence_examples', ['target_type', 'target_uid'], unique=False)
    op.create_index(op.f('ix__ms_markets__calendarevent__mainsequence_examples_d7d0a27b17'), 'ms_markets__calendarevent__mainsequence_examples', ['calendar_uid', 'event_date'], unique=False)
    op.create_index(op.f('uix__ms_markets__calendarevent__mainsequence_example_92503b5092'), 'ms_markets__calendarevent__mainsequence_examples', ['calendar_uid', 'event_date', 'event_type', 'event_label', 'target_type', 'target_identifier'], unique=True)
    op.create_table('ms_markets__calendarsession__mainsequence_examples',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('calendar_uid', sa.Uuid(), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('session_label', sa.String(length=64), nullable=False),
    sa.Column('opens_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closes_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['calendar_uid'], ['ms_markets__calendar__mainsequence_examples.uid'], name=op.f('fk__ms_markets__calendarsession__mainsequence_exampl_d917b767d7'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__calendarsession__mainsequence_examples')),
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.CalendarSession', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__calendarsession__mainsequence_exampl_270873e502'), 'ms_markets__calendarsession__mainsequence_examples', ['local_date'], unique=False)
    op.create_index(op.f('ix__ms_markets__calendarsession__mainsequence_exampl_2790a5ca68'), 'ms_markets__calendarsession__mainsequence_examples', ['calendar_uid', 'is_primary'], unique=False)
    op.create_index(op.f('uix__ms_markets__calendarsession__mainsequence_examp_320afea704'), 'ms_markets__calendarsession__mainsequence_examples', ['calendar_uid', 'local_date', 'session_label'], unique=True)
    op.create_table('ms_markets__currencyspotassetdetails__mainsequence_examples',
    sa.Column('asset_uid', sa.Uuid(), nullable=False),
    sa.Column('base_currency_uid', sa.Uuid(), nullable=False),
    sa.Column('quote_currency_uid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['asset_uid'], ['ms_markets__asset__mainsequence_examples.uid'], name=op.f('fk__ms_markets__currencyspotassetdetails__mainsequen_3217b51479'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['base_currency_uid'], ['ms_markets__asset__mainsequence_examples.uid'], name=op.f('fk__ms_markets__currencyspotassetdetails__mainsequen_6a4b93cc15'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['quote_currency_uid'], ['ms_markets__asset__mainsequence_examples.uid'], name=op.f('fk__ms_markets__currencyspotassetdetails__mainsequen_0403bae9ea'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('asset_uid', name=op.f('pk__ms_markets__currencyspotassetdetails__mainsequence_examples')),
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.CurrencySpotAssetDetails', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__currencyspotassetdetails__mainsequen_8b7ede8384'), 'ms_markets__currencyspotassetdetails__mainsequence_examples', ['base_currency_uid'], unique=False)
    op.create_index(op.f('ix__ms_markets__currencyspotassetdetails__mainsequen_ebcf1bf6aa'), 'ms_markets__currencyspotassetdetails__mainsequence_examples', ['quote_currency_uid'], unique=False)
    op.create_index(op.f('uix__ms_markets__currencyspotassetdetails__mainseque_8b9fdcca79'), 'ms_markets__currencyspotassetdetails__mainsequence_examples', ['base_currency_uid', 'quote_currency_uid'], unique=True)
    op.create_table('ms_markets__futureassetdetails__mainsequence_examples',
    sa.Column('asset_uid', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('underlying_index_uid', sa.Uuid(), nullable=False),
    sa.Column('quote_unit', sa.String(length=64), nullable=False),
    sa.Column('settlement_asset', sa.Uuid(), nullable=False),
    sa.Column('margin_asset', sa.Uuid(), nullable=False),
    sa.Column('settlement_model', sa.String(length=32), nullable=False),
    sa.Column('settlement_method', sa.String(length=32), nullable=False),
    sa.Column('contract_size', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('contract_unit', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settles_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['asset_uid'], ['ms_markets__asset__mainsequence_examples.uid'], name=op.f('fk__ms_markets__futureassetdetails__mainsequence_exa_79e212cfb9'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['margin_asset'], ['ms_markets__asset__mainsequence_examples.uid'], name=op.f('fk__ms_markets__futureassetdetails__mainsequence_exa_1c0a2a9cc7'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['settlement_asset'], ['ms_markets__asset__mainsequence_examples.uid'], name=op.f('fk__ms_markets__futureassetdetails__mainsequence_exa_2379ff6da6'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['underlying_index_uid'], ['ms_markets__index__mainsequence_examples.uid'], name=op.f('fk__ms_markets__futureassetdetails__mainsequence_exa_3a4bee8e5b'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('asset_uid', name=op.f('pk__ms_markets__futureassetdetails__mainsequence_examples')),
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.FutureAssetDetails', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__futureassetdetails__mainsequence_exa_428191a3a7'), 'ms_markets__futureassetdetails__mainsequence_examples', ['underlying_index_uid'], unique=False)
    op.create_index(op.f('ix__ms_markets__futureassetdetails__mainsequence_exa_735b6a2f60'), 'ms_markets__futureassetdetails__mainsequence_examples', ['settlement_asset'], unique=False)
    op.create_index(op.f('ix__ms_markets__futureassetdetails__mainsequence_exa_9c55564c45'), 'ms_markets__futureassetdetails__mainsequence_examples', ['expires_at'], unique=False)
    op.create_index(op.f('ix__ms_markets__futureassetdetails__mainsequence_exa_d6dcf6844e'), 'ms_markets__futureassetdetails__mainsequence_examples', ['margin_asset'], unique=False)
    op.create_table('ms_markets__indexconventiondetails__mainsequence_examples',
    sa.Column('index_uid', sa.Uuid(), nullable=False),
    sa.Column('index_family', sa.String(length=64), nullable=False),
    sa.Column('convention_dump', sa.JSON(), nullable=False),
    sa.Column('serialization_format', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['index_uid'], ['ms_markets__index__mainsequence_examples.uid'], name=op.f('fk__ms_markets__indexconventiondetails__mainsequence_c73357be16'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('index_uid', name=op.f('pk__ms_markets__indexconventiondetails__mainsequence_examples')),
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.IndexConventionDetails', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__indexconventiondetails__mainsequence_171cfb5e75'), 'ms_markets__indexconventiondetails__mainsequence_examples', ['index_family'], unique=False)
    op.create_index(op.f('ix__ms_markets__indexconventiondetails__mainsequence_b20b7708b0'), 'ms_markets__indexconventiondetails__mainsequence_examples', ['source'], unique=False)
    op.create_table('ms_markets__indexfixingsts__mainsequence_examples',
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.Column('index_identifier', sa.String(length=255), nullable=False),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['index_identifier'], ['ms_markets__index__mainsequence_examples.unique_identifier'], name=op.f('fk__ms_markets__indexfixingsts__mainsequence_example_aa88465fdc'), ondelete='RESTRICT'),
    info={'markets_storage_app': 'ms_markets'}
    )
    op.create_index('uix__ms_markets__indexfixingsts__mainsequence_exampl_47c1458038', 'ms_markets__indexfixingsts__mainsequence_examples', ['time_index', 'index_identifier'], unique=True)
    op.create_table('ms_markets__openfigiassetdetails__mainsequence_examples',
    sa.Column('asset_uid', sa.Uuid(), nullable=False),
    sa.Column('figi', sa.String(length=12), nullable=True),
    sa.Column('composite', sa.String(length=12), nullable=True),
    sa.Column('share_class', sa.String(length=12), nullable=True),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('ticker', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('exchange_code', sa.String(length=50), nullable=True),
    sa.Column('security_type', sa.String(length=50), nullable=True),
    sa.Column('security_type_2', sa.String(length=50), nullable=True),
    sa.Column('security_market_sector', sa.String(length=50), nullable=True),
    sa.Column('security_description', sa.String(length=255), nullable=True),
    sa.Column('unique_id', sa.String(length=255), nullable=True),
    sa.Column('unique_id_fut_opt', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['asset_uid'], ['ms_markets__asset__mainsequence_examples.uid'], name=op.f('fk__ms_markets__openfigiassetdetails__mainsequence_e_a1aea7a257'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_uid', name=op.f('pk__ms_markets__openfigiassetdetails__mainsequence_examples')),
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.OpenFigiAssetDetails', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__openfigiassetdetails__mainsequence_e_1ff7676b30'), 'ms_markets__openfigiassetdetails__mainsequence_examples', ['ticker'], unique=False)
    op.create_index(op.f('ix__ms_markets__openfigiassetdetails__mainsequence_e_25d1e87815'), 'ms_markets__openfigiassetdetails__mainsequence_examples', ['isin'], unique=False)
    op.create_index(op.f('ix__ms_markets__openfigiassetdetails__mainsequence_e_77f62d51dd'), 'ms_markets__openfigiassetdetails__mainsequence_examples', ['figi'], unique=False)
    op.create_table('ms_markets__portfolio__mainsequence_examples',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('unique_identifier', sa.String(length=255), nullable=False),
    sa.Column('calendar_name', sa.String(length=255), nullable=True),
    sa.Column('calendar_uid', sa.Uuid(), nullable=True),
    sa.Column('portfolio_index_uid', sa.Uuid(), nullable=True),
    sa.Column('portfolio_weights_data_node_uid', sa.Uuid(), nullable=True),
    sa.Column('signal_weights_data_node_uid', sa.Uuid(), nullable=True),
    sa.Column('portfolio_data_node_uid', sa.Uuid(), nullable=True),
    sa.Column('backtest_table_price_column_name', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['calendar_uid'], ['ms_markets__calendar__mainsequence_examples.uid'], name=op.f('fk__ms_markets__portfolio__mainsequence_examples__ca_e64c32eae0'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['portfolio_index_uid'], ['ms_markets__index__mainsequence_examples.uid'], name=op.f('fk__ms_markets__portfolio__mainsequence_examples__po_55ef2ceb40'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__portfolio__mainsequence_examples')),
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.Portfolio', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__portfolio__mainsequence_examples__calendar_name'), 'ms_markets__portfolio__mainsequence_examples', ['calendar_name'], unique=False)
    op.create_index(op.f('ix__ms_markets__portfolio__mainsequence_examples__calendar_uid'), 'ms_markets__portfolio__mainsequence_examples', ['calendar_uid'], unique=False)
    op.create_index(op.f('ix__ms_markets__portfolio__mainsequence_examples__po_be638370d3'), 'ms_markets__portfolio__mainsequence_examples', ['portfolio_index_uid'], unique=False)
    op.create_index(op.f('uix__ms_markets__portfolio__mainsequence_examples__u_e62554a184'), 'ms_markets__portfolio__mainsequence_examples', ['unique_identifier'], unique=True)
    op.create_table('ms_markets__pricingmarketdatasetbinding__mainsequence_examples',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('market_data_set_uid', sa.Uuid(), nullable=False),
    sa.Column('concept_key', sa.String(length=128), nullable=False),
    sa.Column('data_node_uid', sa.Uuid(), nullable=False),
    sa.Column('storage_table_identifier', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['market_data_set_uid'], ['ms_markets__pricingmarketdataset__mainsequence_examples.uid'], name=op.f('fk__ms_markets__pricingmarketdatasetbinding__mainseq_857b3d1975'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__pricingmarketdatasetbinding__mainseq_c8bb5d90fb')),
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.PricingMarketDataSetBinding', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__pricingmarketdatasetbinding__mainseq_5f23236bc8'), 'ms_markets__pricingmarketdatasetbinding__mainsequence_examples', ['data_node_uid'], unique=False)
    op.create_index(op.f('ix__ms_markets__pricingmarketdatasetbinding__mainseq_79ca1f1880'), 'ms_markets__pricingmarketdatasetbinding__mainsequence_examples', ['concept_key'], unique=False)
    op.create_index(op.f('uix__ms_markets__pricingmarketdatasetbinding__mainse_2c36426886'), 'ms_markets__pricingmarketdatasetbinding__mainsequence_examples', ['market_data_set_uid', 'concept_key'], unique=True)
    op.create_table('ms_markets__accountholdingsset__mainsequence_examples',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('account_uid', sa.Uuid(), nullable=False),
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_data_node_uid', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['account_uid'], ['ms_markets__account__mainsequence_examples.uid'], name=op.f('fk__ms_markets__accountholdingsset__mainsequence_exa_e037bb2c1b'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__accountholdingsset__mainsequence_examples')),
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.AccountHoldingsSet', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__accountholdingsset__mainsequence_exa_9c1f40d6d6'), 'ms_markets__accountholdingsset__mainsequence_examples', ['account_uid'], unique=False)
    op.create_index(op.f('ix__ms_markets__accountholdingsset__mainsequence_exa_eee87a5288'), 'ms_markets__accountholdingsset__mainsequence_examples', ['time_index'], unique=False)
    op.create_index(op.f('uix__ms_markets__accountholdingsset__mainsequence_ex_e671625762'), 'ms_markets__accountholdingsset__mainsequence_examples', ['account_uid', 'time_index'], unique=True)
    op.create_table('ms_markets__accounttargetallocation__mainsequence_examples',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('unique_identifier', sa.String(length=255), nullable=False),
    sa.Column('account_uid', sa.Uuid(), nullable=False),
    sa.Column('account_allocation_model_uid', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['account_allocation_model_uid'], ['ms_markets__accountallocationmodel__mainsequence_examples.uid'], name=op.f('fk__ms_markets__accounttargetallocation__mainsequenc_c1678a4356'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['account_uid'], ['ms_markets__account__mainsequence_examples.uid'], name=op.f('fk__ms_markets__accounttargetallocation__mainsequenc_e9824eda2c'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__accounttargetallocation__mainsequence_examples')),
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.AccountTargetAllocation', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__accounttargetallocation__mainsequenc_365f522006'), 'ms_markets__accounttargetallocation__mainsequence_examples', ['account_uid'], unique=False)
    op.create_index(op.f('ix__ms_markets__accounttargetallocation__mainsequenc_4b86c21852'), 'ms_markets__accounttargetallocation__mainsequence_examples', ['account_allocation_model_uid'], unique=False)
    op.create_index(op.f('ix__ms_markets__accounttargetallocation__mainsequenc_f6bd50d503'), 'ms_markets__accounttargetallocation__mainsequence_examples', ['is_active'], unique=False)
    op.create_index(op.f('uix__ms_markets__accounttargetallocation__mainsequen_e97b117246'), 'ms_markets__accounttargetallocation__mainsequence_examples', ['unique_identifier'], unique=True)
    op.create_table('ms_markets__curve__mainsequence_examples',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('unique_identifier', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('curve_type', sa.String(length=64), nullable=False),
    sa.Column('index_uid', sa.Uuid(), nullable=False),
    sa.Column('interpolation_method', sa.String(length=64), nullable=True),
    sa.Column('compounding', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['index_uid'], ['ms_markets__indexconventiondetails__mainsequence_examples.index_uid'], name=op.f('fk__ms_markets__curve__mainsequence_examples__index_3259429324'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__curve__mainsequence_examples')),
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.Curve', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__curve__mainsequence_examples__curve_type'), 'ms_markets__curve__mainsequence_examples', ['curve_type'], unique=False)
    op.create_index(op.f('ix__ms_markets__curve__mainsequence_examples__index_uid'), 'ms_markets__curve__mainsequence_examples', ['index_uid'], unique=False)
    op.create_index(op.f('ix__ms_markets__curve__mainsequence_examples__source'), 'ms_markets__curve__mainsequence_examples', ['source'], unique=False)
    op.create_index(op.f('uix__ms_markets__curve__mainsequence_examples__uniqu_90f7438a7e'), 'ms_markets__curve__mainsequence_examples', ['unique_identifier'], unique=True)
    op.create_table('ms_markets__ordermanager__mainsequence_examples',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('unique_identifier', sa.String(length=255), nullable=False),
    sa.Column('target_account_uid', sa.Uuid(), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('order_received_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['target_account_uid'], ['ms_markets__account__mainsequence_examples.uid'], name=op.f('fk__ms_markets__ordermanager__mainsequence_examples_896b7d73b3'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__ordermanager__mainsequence_examples')),
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.OrderManager', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__ordermanager__mainsequence_examples_886151fb86'), 'ms_markets__ordermanager__mainsequence_examples', ['target_account_uid'], unique=False)
    op.create_index(op.f('ix__ms_markets__ordermanager__mainsequence_examples__status'), 'ms_markets__ordermanager__mainsequence_examples', ['status'], unique=False)
    op.create_index(op.f('uix__ms_markets__ordermanager__mainsequence_examples_57a6fec046'), 'ms_markets__ordermanager__mainsequence_examples', ['unique_identifier'], unique=True)
    op.create_table('ms_markets__virtualfund__mainsequence_examples',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('unique_identifier', sa.String(length=255), nullable=False),
    sa.Column('account_uid', sa.Uuid(), nullable=False),
    sa.Column('target_portfolio_uid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['account_uid'], ['ms_markets__account__mainsequence_examples.uid'], name=op.f('fk__ms_markets__virtualfund__mainsequence_examples_59efb9c33a'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_portfolio_uid'], ['ms_markets__portfolio__mainsequence_examples.uid'], name=op.f('fk__ms_markets__virtualfund__mainsequence_examples_877c8a99ec'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__virtualfund__mainsequence_examples')),
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.VirtualFund', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__virtualfund__mainsequence_examples__account_uid'), 'ms_markets__virtualfund__mainsequence_examples', ['account_uid'], unique=False)
    op.create_index(op.f('ix__ms_markets__virtualfund__mainsequence_examples_fbe02d39d4'), 'ms_markets__virtualfund__mainsequence_examples', ['target_portfolio_uid'], unique=False)
    op.create_index(op.f('uix__ms_markets__virtualfund__mainsequence_examples_506bd57e1d'), 'ms_markets__virtualfund__mainsequence_examples', ['unique_identifier'], unique=True)
    op.create_table('ms_markets__accountholdingsts__mainsequence_examples',
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.Column('account_uid', sa.Uuid(), nullable=False),
    sa.Column('asset_identifier', sa.String(length=255), nullable=False),
    sa.Column('holdings_set_uid', sa.Uuid(), nullable=False),
    sa.Column('is_trade_snapshot', sa.Boolean(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('direction', sa.SmallInteger(), nullable=False),
    sa.Column('target_trade_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint('direction IN (1, -1)', name=op.f('ck__ms_markets__accountholdingsts__mainsequence_exam_6266b5b632')),
    sa.ForeignKeyConstraint(['account_uid'], ['ms_markets__account__mainsequence_examples.uid'], name=op.f('fk__ms_markets__accountholdingsts__mainsequence_exam_f6a5c0f449'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['asset_identifier'], ['ms_markets__asset__mainsequence_examples.unique_identifier'], name=op.f('fk__ms_markets__accountholdingsts__mainsequence_exam_59e2f8b6f8'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['holdings_set_uid'], ['ms_markets__accountholdingsset__mainsequence_examples.uid'], name=op.f('fk__ms_markets__accountholdingsts__mainsequence_exam_a9991e28d8'), ondelete='CASCADE'),
    info={'markets_storage_app': 'ms_markets'}
    )
    op.create_index('uix__ms_markets__accountholdingsts__mainsequence_exa_336f239b52', 'ms_markets__accountholdingsts__mainsequence_examples', ['time_index', 'account_uid', 'asset_identifier'], unique=True)
    op.create_table('ms_markets__discountcurvests__mainsequence_examples',
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.Column('curve_identifier', sa.String(length=255), nullable=False),
    sa.Column('curve', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['curve_identifier'], ['ms_markets__curve__mainsequence_examples.unique_identifier'], name=op.f('fk__ms_markets__discountcurvests__mainsequence_examp_3cb058a38e'), ondelete='RESTRICT'),
    info={'markets_storage_app': 'ms_markets'}
    )
    op.create_index('uix__ms_markets__discountcurvests__mainsequence_exam_51b8d86135', 'ms_markets__discountcurvests__mainsequence_examples', ['time_index', 'curve_identifier'], unique=True)
    op.create_table('ms_markets__positionset__mainsequence_examples',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('account_target_allocation_uid', sa.Uuid(), nullable=False),
    sa.Column('position_set_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['account_target_allocation_uid'], ['ms_markets__accounttargetallocation__mainsequence_examples.uid'], name=op.f('fk__ms_markets__positionset__mainsequence_examples_5fb35d5c6d'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__positionset__mainsequence_examples')),
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.PositionSet', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__positionset__mainsequence_examples_ce995d975d'), 'ms_markets__positionset__mainsequence_examples', ['position_set_time'], unique=False)
    op.create_index(op.f('ix__ms_markets__positionset__mainsequence_examples_ee452bd9df'), 'ms_markets__positionset__mainsequence_examples', ['account_target_allocation_uid'], unique=False)
    op.create_index(op.f('uix__ms_markets__positionset__mainsequence_examples_8e6792a2ee'), 'ms_markets__positionset__mainsequence_examples', ['account_target_allocation_uid', 'position_set_time'], unique=True)
    op.create_table('ms_markets__virtualfundholdingsset__mainsequence_examples',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('virtual_fund_uid', sa.Uuid(), nullable=False),
    sa.Column('source_account_holdings_set_uid', sa.Uuid(), nullable=False),
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_account_holdings_set_uid'], ['ms_markets__accountholdingsset__mainsequence_examples.uid'], name=op.f('fk__ms_markets__virtualfundholdingsset__mainsequence_c0047f6339'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['virtual_fund_uid'], ['ms_markets__virtualfund__mainsequence_examples.uid'], name=op.f('fk__ms_markets__virtualfundholdingsset__mainsequence_5dcd81dcac'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__virtualfundholdingsset__mainsequence_examples')),
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.VirtualFundHoldingsSet', 'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__virtualfundholdingsset__mainsequence_84a71731e5'), 'ms_markets__virtualfundholdingsset__mainsequence_examples', ['virtual_fund_uid'], unique=False)
    op.create_index(op.f('ix__ms_markets__virtualfundholdingsset__mainsequence_85d8a20b93'), 'ms_markets__virtualfundholdingsset__mainsequence_examples', ['source_account_holdings_set_uid'], unique=False)
    op.create_index(op.f('uix__ms_markets__virtualfundholdingsset__mainsequenc_8007d1fcdb'), 'ms_markets__virtualfundholdingsset__mainsequence_examples', ['virtual_fund_uid', 'source_account_holdings_set_uid'], unique=True)
    op.create_table('ms_markets__targetpositionsts__mainsequence_examples',
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.Column('position_set_uid', sa.Uuid(), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_uid', sa.Uuid(), nullable=False),
    sa.Column('asset_uid', sa.Uuid(), nullable=True),
    sa.Column('portfolio_uid', sa.Uuid(), nullable=True),
    sa.Column('weight_notional_exposure', sa.Float(), nullable=True),
    sa.Column('constant_notional_exposure', sa.Float(), nullable=True),
    sa.Column('single_asset_quantity', sa.Float(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("(target_type = 'asset' AND asset_uid IS NOT NULL AND portfolio_uid IS NULL AND target_uid = asset_uid) OR (target_type = 'portfolio' AND portfolio_uid IS NOT NULL AND asset_uid IS NULL AND target_uid = portfolio_uid)", name=op.f('ck__ms_markets__targetpositionsts__mainsequence_exam_8b7a5c5108')),
    sa.CheckConstraint("target_type IN ('asset', 'portfolio')", name=op.f('ck__ms_markets__targetpositionsts__mainsequence_exam_090467615c')),
    sa.CheckConstraint('(CASE WHEN weight_notional_exposure IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN constant_notional_exposure IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN single_asset_quantity IS NOT NULL THEN 1 ELSE 0 END) = 1', name=op.f('ck__ms_markets__targetpositionsts__mainsequence_exam_54d0ed828a')),
    sa.ForeignKeyConstraint(['asset_uid'], ['ms_markets__asset__mainsequence_examples.uid'], name=op.f('fk__ms_markets__targetpositionsts__mainsequence_exam_21645482de'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['portfolio_uid'], ['ms_markets__portfolio__mainsequence_examples.uid'], name=op.f('fk__ms_markets__targetpositionsts__mainsequence_exam_41e34dab69'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['position_set_uid'], ['ms_markets__positionset__mainsequence_examples.uid'], name=op.f('fk__ms_markets__targetpositionsts__mainsequence_exam_9916b6f47e'), ondelete='CASCADE'),
    info={'markets_storage_app': 'ms_markets'}
    )
    op.create_index(op.f('ix__ms_markets__targetpositionsts__mainsequence_exam_4f286bcf1c'), 'ms_markets__targetpositionsts__mainsequence_examples', ['portfolio_uid'], unique=False)
    op.create_index(op.f('ix__ms_markets__targetpositionsts__mainsequence_exam_782379de98'), 'ms_markets__targetpositionsts__mainsequence_examples', ['position_set_uid', 'target_type', 'target_uid'], unique=False)
    op.create_index(op.f('ix__ms_markets__targetpositionsts__mainsequence_exam_c5cb925c03'), 'ms_markets__targetpositionsts__mainsequence_examples', ['asset_uid'], unique=False)
    op.create_index('uix__ms_markets__targetpositionsts__mainsequence_exa_9864e9a65f', 'ms_markets__targetpositionsts__mainsequence_examples', ['time_index', 'position_set_uid', 'target_type', 'target_uid'], unique=True)
    op.create_table('ms_markets__virtualfundholdingsts__mainsequence_examples',
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.Column('virtual_fund_uid', sa.Uuid(), nullable=False),
    sa.Column('asset_identifier', sa.String(length=255), nullable=False),
    sa.Column('virtual_fund_holdings_set_uid', sa.Uuid(), nullable=False),
    sa.Column('source_account_holdings_set_uid', sa.Uuid(), nullable=False),
    sa.Column('allocated_quantity', sa.Float(), nullable=False),
    sa.Column('direction', sa.SmallInteger(), nullable=False),
    sa.Column('target_trade_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint('direction IN (1, -1)', name=op.f('ck__ms_markets__virtualfundholdingsts__mainsequence_c103fe4b3c')),
    sa.ForeignKeyConstraint(['asset_identifier'], ['ms_markets__asset__mainsequence_examples.unique_identifier'], name=op.f('fk__ms_markets__virtualfundholdingsts__mainsequence_b0095ceb39'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_account_holdings_set_uid'], ['ms_markets__accountholdingsset__mainsequence_examples.uid'], name=op.f('fk__ms_markets__virtualfundholdingsts__mainsequence_faa42e578a'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['virtual_fund_holdings_set_uid'], ['ms_markets__virtualfundholdingsset__mainsequence_examples.uid'], name=op.f('fk__ms_markets__virtualfundholdingsts__mainsequence_4c4817e958'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['virtual_fund_uid'], ['ms_markets__virtualfund__mainsequence_examples.uid'], name=op.f('fk__ms_markets__virtualfundholdingsts__mainsequence_0db59af269'), ondelete='CASCADE'),
    info={'markets_storage_app': 'ms_markets'}
    )
    op.create_index('uix__ms_markets__virtualfundholdingsts__mainsequence_49c5da1a85', 'ms_markets__virtualfundholdingsts__mainsequence_examples', ['time_index', 'virtual_fund_uid', 'asset_identifier'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uix__ms_markets__virtualfundholdingsts__mainsequence_49c5da1a85', table_name='ms_markets__virtualfundholdingsts__mainsequence_examples')
    op.drop_table('ms_markets__virtualfundholdingsts__mainsequence_examples')
    op.drop_index('uix__ms_markets__targetpositionsts__mainsequence_exa_9864e9a65f', table_name='ms_markets__targetpositionsts__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__targetpositionsts__mainsequence_exam_c5cb925c03'), table_name='ms_markets__targetpositionsts__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__targetpositionsts__mainsequence_exam_782379de98'), table_name='ms_markets__targetpositionsts__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__targetpositionsts__mainsequence_exam_4f286bcf1c'), table_name='ms_markets__targetpositionsts__mainsequence_examples')
    op.drop_table('ms_markets__targetpositionsts__mainsequence_examples')
    op.drop_index(op.f('uix__ms_markets__virtualfundholdingsset__mainsequenc_8007d1fcdb'), table_name='ms_markets__virtualfundholdingsset__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__virtualfundholdingsset__mainsequence_85d8a20b93'), table_name='ms_markets__virtualfundholdingsset__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__virtualfundholdingsset__mainsequence_84a71731e5'), table_name='ms_markets__virtualfundholdingsset__mainsequence_examples')
    op.drop_table('ms_markets__virtualfundholdingsset__mainsequence_examples')
    op.drop_index(op.f('uix__ms_markets__positionset__mainsequence_examples_8e6792a2ee'), table_name='ms_markets__positionset__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__positionset__mainsequence_examples_ee452bd9df'), table_name='ms_markets__positionset__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__positionset__mainsequence_examples_ce995d975d'), table_name='ms_markets__positionset__mainsequence_examples')
    op.drop_table('ms_markets__positionset__mainsequence_examples')
    op.drop_index('uix__ms_markets__discountcurvests__mainsequence_exam_51b8d86135', table_name='ms_markets__discountcurvests__mainsequence_examples')
    op.drop_table('ms_markets__discountcurvests__mainsequence_examples')
    op.drop_index('uix__ms_markets__accountholdingsts__mainsequence_exa_336f239b52', table_name='ms_markets__accountholdingsts__mainsequence_examples')
    op.drop_table('ms_markets__accountholdingsts__mainsequence_examples')
    op.drop_index(op.f('uix__ms_markets__virtualfund__mainsequence_examples_506bd57e1d'), table_name='ms_markets__virtualfund__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__virtualfund__mainsequence_examples_fbe02d39d4'), table_name='ms_markets__virtualfund__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__virtualfund__mainsequence_examples__account_uid'), table_name='ms_markets__virtualfund__mainsequence_examples')
    op.drop_table('ms_markets__virtualfund__mainsequence_examples')
    op.drop_index(op.f('uix__ms_markets__ordermanager__mainsequence_examples_57a6fec046'), table_name='ms_markets__ordermanager__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__ordermanager__mainsequence_examples__status'), table_name='ms_markets__ordermanager__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__ordermanager__mainsequence_examples_886151fb86'), table_name='ms_markets__ordermanager__mainsequence_examples')
    op.drop_table('ms_markets__ordermanager__mainsequence_examples')
    op.drop_index(op.f('uix__ms_markets__curve__mainsequence_examples__uniqu_90f7438a7e'), table_name='ms_markets__curve__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__curve__mainsequence_examples__source'), table_name='ms_markets__curve__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__curve__mainsequence_examples__index_uid'), table_name='ms_markets__curve__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__curve__mainsequence_examples__curve_type'), table_name='ms_markets__curve__mainsequence_examples')
    op.drop_table('ms_markets__curve__mainsequence_examples')
    op.drop_index(op.f('uix__ms_markets__accounttargetallocation__mainsequen_e97b117246'), table_name='ms_markets__accounttargetallocation__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__accounttargetallocation__mainsequenc_f6bd50d503'), table_name='ms_markets__accounttargetallocation__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__accounttargetallocation__mainsequenc_4b86c21852'), table_name='ms_markets__accounttargetallocation__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__accounttargetallocation__mainsequenc_365f522006'), table_name='ms_markets__accounttargetallocation__mainsequence_examples')
    op.drop_table('ms_markets__accounttargetallocation__mainsequence_examples')
    op.drop_index(op.f('uix__ms_markets__accountholdingsset__mainsequence_ex_e671625762'), table_name='ms_markets__accountholdingsset__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__accountholdingsset__mainsequence_exa_eee87a5288'), table_name='ms_markets__accountholdingsset__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__accountholdingsset__mainsequence_exa_9c1f40d6d6'), table_name='ms_markets__accountholdingsset__mainsequence_examples')
    op.drop_table('ms_markets__accountholdingsset__mainsequence_examples')
    op.drop_index(op.f('uix__ms_markets__pricingmarketdatasetbinding__mainse_2c36426886'), table_name='ms_markets__pricingmarketdatasetbinding__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__pricingmarketdatasetbinding__mainseq_79ca1f1880'), table_name='ms_markets__pricingmarketdatasetbinding__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__pricingmarketdatasetbinding__mainseq_5f23236bc8'), table_name='ms_markets__pricingmarketdatasetbinding__mainsequence_examples')
    op.drop_table('ms_markets__pricingmarketdatasetbinding__mainsequence_examples')
    op.drop_index(op.f('uix__ms_markets__portfolio__mainsequence_examples__u_e62554a184'), table_name='ms_markets__portfolio__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__portfolio__mainsequence_examples__po_be638370d3'), table_name='ms_markets__portfolio__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__portfolio__mainsequence_examples__calendar_uid'), table_name='ms_markets__portfolio__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__portfolio__mainsequence_examples__calendar_name'), table_name='ms_markets__portfolio__mainsequence_examples')
    op.drop_table('ms_markets__portfolio__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__openfigiassetdetails__mainsequence_e_77f62d51dd'), table_name='ms_markets__openfigiassetdetails__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__openfigiassetdetails__mainsequence_e_25d1e87815'), table_name='ms_markets__openfigiassetdetails__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__openfigiassetdetails__mainsequence_e_1ff7676b30'), table_name='ms_markets__openfigiassetdetails__mainsequence_examples')
    op.drop_table('ms_markets__openfigiassetdetails__mainsequence_examples')
    op.drop_index('uix__ms_markets__indexfixingsts__mainsequence_exampl_47c1458038', table_name='ms_markets__indexfixingsts__mainsequence_examples')
    op.drop_table('ms_markets__indexfixingsts__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__indexconventiondetails__mainsequence_b20b7708b0'), table_name='ms_markets__indexconventiondetails__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__indexconventiondetails__mainsequence_171cfb5e75'), table_name='ms_markets__indexconventiondetails__mainsequence_examples')
    op.drop_table('ms_markets__indexconventiondetails__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__futureassetdetails__mainsequence_exa_d6dcf6844e'), table_name='ms_markets__futureassetdetails__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__futureassetdetails__mainsequence_exa_9c55564c45'), table_name='ms_markets__futureassetdetails__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__futureassetdetails__mainsequence_exa_735b6a2f60'), table_name='ms_markets__futureassetdetails__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__futureassetdetails__mainsequence_exa_428191a3a7'), table_name='ms_markets__futureassetdetails__mainsequence_examples')
    op.drop_table('ms_markets__futureassetdetails__mainsequence_examples')
    op.drop_index(op.f('uix__ms_markets__currencyspotassetdetails__mainseque_8b9fdcca79'), table_name='ms_markets__currencyspotassetdetails__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__currencyspotassetdetails__mainsequen_ebcf1bf6aa'), table_name='ms_markets__currencyspotassetdetails__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__currencyspotassetdetails__mainsequen_8b7ede8384'), table_name='ms_markets__currencyspotassetdetails__mainsequence_examples')
    op.drop_table('ms_markets__currencyspotassetdetails__mainsequence_examples')
    op.drop_index(op.f('uix__ms_markets__calendarsession__mainsequence_examp_320afea704'), table_name='ms_markets__calendarsession__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__calendarsession__mainsequence_exampl_2790a5ca68'), table_name='ms_markets__calendarsession__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__calendarsession__mainsequence_exampl_270873e502'), table_name='ms_markets__calendarsession__mainsequence_examples')
    op.drop_table('ms_markets__calendarsession__mainsequence_examples')
    op.drop_index(op.f('uix__ms_markets__calendarevent__mainsequence_example_92503b5092'), table_name='ms_markets__calendarevent__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__calendarevent__mainsequence_examples_d7d0a27b17'), table_name='ms_markets__calendarevent__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__calendarevent__mainsequence_examples_63b477ee1a'), table_name='ms_markets__calendarevent__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__calendarevent__mainsequence_examples_11efc7e898'), table_name='ms_markets__calendarevent__mainsequence_examples')
    op.drop_table('ms_markets__calendarevent__mainsequence_examples')
    op.drop_index(op.f('uix__ms_markets__calendardate__mainsequence_examples_3928e12e5f'), table_name='ms_markets__calendardate__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__calendardate__mainsequence_examples__local_date'), table_name='ms_markets__calendardate__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__calendardate__mainsequence_examples_655c235a4b'), table_name='ms_markets__calendardate__mainsequence_examples')
    op.drop_table('ms_markets__calendardate__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__bondassetdetails__mainsequence_examples__status'), table_name='ms_markets__bondassetdetails__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__bondassetdetails__mainsequence_examp_fb406959be'), table_name='ms_markets__bondassetdetails__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__bondassetdetails__mainsequence_examp_21045e0336'), table_name='ms_markets__bondassetdetails__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__bondassetdetails__mainsequence_examp_07099ef1be'), table_name='ms_markets__bondassetdetails__mainsequence_examples')
    op.drop_table('ms_markets__bondassetdetails__mainsequence_examples')
    op.drop_index('uix__ms_markets__assetsnapshotsts__mainsequence_exam_21493f481e', table_name='ms_markets__assetsnapshotsts__mainsequence_examples')
    op.drop_table('ms_markets__assetsnapshotsts__mainsequence_examples')
    op.drop_index('uix__ms_markets__assetpricingdetailsts__mainsequence_3f465e3beb', table_name='ms_markets__assetpricingdetailsts__mainsequence_examples')
    op.drop_table('ms_markets__assetpricingdetailsts__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__assetcurrentpricingdetails__mainsequ_a2d063f2aa'), table_name='ms_markets__assetcurrentpricingdetails__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__assetcurrentpricingdetails__mainsequ_2a92d6c31f'), table_name='ms_markets__assetcurrentpricingdetails__mainsequence_examples')
    op.drop_table('ms_markets__assetcurrentpricingdetails__mainsequence_examples')
    op.drop_index(op.f('uix__ms_markets__assetcategorymembership__mainsequen_9d5443b2cc'), table_name='ms_markets__assetcategorymembership__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__assetcategorymembership__mainsequenc_b8154287aa'), table_name='ms_markets__assetcategorymembership__mainsequence_examples')
    op.drop_table('ms_markets__assetcategorymembership__mainsequence_examples')
    op.drop_index(op.f('uix__ms_markets__account__mainsequence_examples__uni_a15bc62da9'), table_name='ms_markets__account__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__account__mainsequence_examples__account_name'), table_name='ms_markets__account__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__account__mainsequence_examples__acco_94d0c32b9b'), table_name='ms_markets__account__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__account__mainsequence_examples__acco_78c7641f5d'), table_name='ms_markets__account__mainsequence_examples')
    op.drop_table('ms_markets__account__mainsequence_examples')
    op.drop_index('uix__ms_markets__tradests__mainsequence_examples__tr_7ad1af6c1a', table_name='ms_markets__tradests__mainsequence_examples')
    op.drop_table('ms_markets__tradests__mainsequence_examples')
    op.drop_index('uix__ms_markets__signalweightsts__mainsequence_examp_486fb6308a', table_name='ms_markets__signalweightsts__mainsequence_examples')
    op.drop_table('ms_markets__signalweightsts__mainsequence_examples')
    op.drop_index(op.f('uix__ms_markets__signalmetadata__mainsequence_exampl_3074904c43'), table_name='ms_markets__signalmetadata__mainsequence_examples')
    op.drop_table('ms_markets__signalmetadata__mainsequence_examples')
    op.drop_index(op.f('uix__ms_markets__rebalancestrategymetadata__mainsequ_6b6ca232fc'), table_name='ms_markets__rebalancestrategymetadata__mainsequence_examples')
    op.drop_table('ms_markets__rebalancestrategymetadata__mainsequence_examples')
    op.drop_index(op.f('uix__ms_markets__pricingmarketdataset__mainsequence_1a99e61cba'), table_name='ms_markets__pricingmarketdataset__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__pricingmarketdataset__mainsequence_e_4960208f20'), table_name='ms_markets__pricingmarketdataset__mainsequence_examples')
    op.drop_table('ms_markets__pricingmarketdataset__mainsequence_examples')
    op.drop_index('uix__ms_markets__portfolioweightsts__mainsequence_ex_c1365e7560', table_name='ms_markets__portfolioweightsts__mainsequence_examples')
    op.drop_table('ms_markets__portfolioweightsts__mainsequence_examples')
    op.drop_index('uix__ms_markets__portfoliosts__mainsequence_examples_18eda21ee1', table_name='ms_markets__portfoliosts__mainsequence_examples')
    op.drop_table('ms_markets__portfoliosts__mainsequence_examples')
    op.drop_index(op.f('uix__ms_markets__portfoliometadata__mainsequence_exa_a8c57177f8'), table_name='ms_markets__portfoliometadata__mainsequence_examples')
    op.drop_table('ms_markets__portfoliometadata__mainsequence_examples')
    op.drop_index('uix__ms_markets__ordersts__mainsequence_examples__or_175e488d61', table_name='ms_markets__ordersts__mainsequence_examples')
    op.drop_table('ms_markets__ordersts__mainsequence_examples')
    op.drop_index('uix__ms_markets__ordereventsts__mainsequence_example_e5d5b7267c', table_name='ms_markets__ordereventsts__mainsequence_examples')
    op.drop_table('ms_markets__ordereventsts__mainsequence_examples')
    op.drop_index(op.f('uix__ms_markets__issuer__mainsequence_examples__uniq_5f112eb7b5'), table_name='ms_markets__issuer__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__issuer__mainsequence_examples__display_name'), table_name='ms_markets__issuer__mainsequence_examples')
    op.drop_table('ms_markets__issuer__mainsequence_examples')
    op.drop_index('uix__ms_markets__interpolatedpricests__mainsequence_34f03829ba', table_name='ms_markets__interpolatedpricests__mainsequence_examples')
    op.drop_table('ms_markets__interpolatedpricests__mainsequence_examples')
    op.drop_index(op.f('uix__ms_markets__indextype__mainsequence_examples__index_type'), table_name='ms_markets__indextype__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__indextype__mainsequence_examples__display_name'), table_name='ms_markets__indextype__mainsequence_examples')
    op.drop_table('ms_markets__indextype__mainsequence_examples')
    op.drop_index(op.f('uix__ms_markets__index__mainsequence_examples__uniqu_ba58bcb4d0'), table_name='ms_markets__index__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__index__mainsequence_examples__provider'), table_name='ms_markets__index__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__index__mainsequence_examples__index_type'), table_name='ms_markets__index__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__index__mainsequence_examples__display_name'), table_name='ms_markets__index__mainsequence_examples')
    op.drop_table('ms_markets__index__mainsequence_examples')
    op.drop_index('uix__ms_markets__externalpricests__mainsequence_exam_bdce163d05', table_name='ms_markets__externalpricests__mainsequence_examples')
    op.drop_table('ms_markets__externalpricests__mainsequence_examples')
    op.drop_index(op.f('uix__ms_markets__calendar__mainsequence_examples__un_b900d44ed4'), table_name='ms_markets__calendar__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__calendar__mainsequence_examples__sou_2ddf7c50e9'), table_name='ms_markets__calendar__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__calendar__mainsequence_examples__calendar_type'), table_name='ms_markets__calendar__mainsequence_examples')
    op.drop_table('ms_markets__calendar__mainsequence_examples')
    op.drop_index(op.f('uix__ms_markets__assettype__mainsequence_examples__asset_type'), table_name='ms_markets__assettype__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__assettype__mainsequence_examples__display_name'), table_name='ms_markets__assettype__mainsequence_examples')
    op.drop_table('ms_markets__assettype__mainsequence_examples')
    op.drop_index(op.f('uix__ms_markets__assetcategory__mainsequence_example_657fa45c6f'), table_name='ms_markets__assetcategory__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__assetcategory__mainsequence_examples_8cef4665e2'), table_name='ms_markets__assetcategory__mainsequence_examples')
    op.drop_table('ms_markets__assetcategory__mainsequence_examples')
    op.drop_index(op.f('uix__ms_markets__asset__mainsequence_examples__uniqu_b17b6bd854'), table_name='ms_markets__asset__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__asset__mainsequence_examples__asset_type'), table_name='ms_markets__asset__mainsequence_examples')
    op.drop_table('ms_markets__asset__mainsequence_examples')
    op.drop_index(op.f('uix__ms_markets__accountgroup__mainsequence_examples_a47462aee6'), table_name='ms_markets__accountgroup__mainsequence_examples')
    op.drop_table('ms_markets__accountgroup__mainsequence_examples')
    op.drop_index(op.f('uix__ms_markets__accountallocationmodel__mainsequenc_d5d6816908'), table_name='ms_markets__accountallocationmodel__mainsequence_examples')
    op.drop_table('ms_markets__accountallocationmodel__mainsequence_examples')
    # ### end Alembic commands ###
