"""migration

Revision ID: 0002
Revises: 0001
Create Date: 2026-06-04 13:31:41.454345

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: Union[str, Sequence[str], None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ms_markets__marketsmetatablecatalog__mainsequence_examples', 'contract_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ms_markets__marketsmetatablecatalog__mainsequence_examples', sa.Column('contract_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
