"""account_portfolio_virtual_fund_full_workflow_dynamic_schema

Revision ID: 0004
Revises: 0003
Create Date: 2026-06-09 11:33:14.088554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mt_mainsequence_examples_9c6c99a2f6a5a74e1f1fb25ed9d0aa53',
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.Column('asset_identifier', sa.String(), nullable=False),
    sa.Column('open_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('trade_count', sa.Float(), nullable=True),
    sa.Column('vwap', sa.Float(), nullable=True),
    sa.Column('interpolated', sa.Boolean(), nullable=True),
    info={'markets_storage_app': 'ms_markets'}
    )
    op.create_index('uix__mt_mainsequence_examples_9c6c99a2f6a5a74e1f1fb2_6f0388fc53', 'mt_mainsequence_examples_9c6c99a2f6a5a74e1f1fb25ed9d0aa53', ['time_index', 'asset_identifier'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uix__mt_mainsequence_examples_9c6c99a2f6a5a74e1f1fb2_6f0388fc53', table_name='mt_mainsequence_examples_9c6c99a2f6a5a74e1f1fb25ed9d0aa53')
    op.drop_table('mt_mainsequence_examples_9c6c99a2f6a5a74e1f1fb25ed9d0aa53')
    # ### end Alembic commands ###
