"""migration

Revision ID: 0004
Revises: 0003
Create Date: 2026-06-04 17:16:46.480710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uix__ms_markets__accountholdingsts__mainsequence_exa_336f239b52', 'ms_markets__accountholdingsts__mainsequence_examples', ['time_index', 'account_uid', 'asset_identifier'], unique=True)
    op.create_index('uix__ms_markets__assetpricingdetailsts__mainsequence_3f465e3beb', 'ms_markets__assetpricingdetailsts__mainsequence_examples', ['time_index', 'asset_identifier'], unique=True)
    op.create_index('uix__ms_markets__assetsnapshotsts__mainsequence_exam_21493f481e', 'ms_markets__assetsnapshotsts__mainsequence_examples', ['time_index', 'asset_identifier'], unique=True)
    op.create_index('uix__ms_markets__discountcurvests__mainsequence_exam_51b8d86135', 'ms_markets__discountcurvests__mainsequence_examples', ['time_index', 'curve_identifier'], unique=True)
    op.create_index('uix__ms_markets__indexfixingsts__mainsequence_exampl_47c1458038', 'ms_markets__indexfixingsts__mainsequence_examples', ['time_index', 'index_identifier'], unique=True)
    op.create_index('uix__ms_markets__interpolatedpricests__mainsequence_34f03829ba', 'ms_markets__interpolatedpricests__mainsequence_examples', ['time_index', 'asset_identifier'], unique=True)
    op.create_index('uix__ms_markets__ordereventsts__mainsequence_example_e5d5b7267c', 'ms_markets__ordereventsts__mainsequence_examples', ['event_time', 'order_identifier'], unique=True)
    op.create_index('uix__ms_markets__ordersts__mainsequence_examples__or_175e488d61', 'ms_markets__ordersts__mainsequence_examples', ['order_time', 'order_identifier', 'account_identifier', 'asset_identifier'], unique=True)
    op.create_index('uix__ms_markets__portfoliosts__mainsequence_examples_18eda21ee1', 'ms_markets__portfoliosts__mainsequence_examples', ['time_index', 'portfolio_identifier'], unique=True)
    op.create_index('uix__ms_markets__portfolioweightsts__mainsequence_ex_c1365e7560', 'ms_markets__portfolioweightsts__mainsequence_examples', ['time_index', 'portfolio_index_identifier', 'asset_identifier'], unique=True)
    op.create_index('uix__ms_markets__signalweightsts__mainsequence_examp_486fb6308a', 'ms_markets__signalweightsts__mainsequence_examples', ['time_index', 'signal_uid', 'asset_identifier'], unique=True)
    op.create_index('uix__ms_markets__targetpositionsts__mainsequence_exa_c53adaf81e', 'ms_markets__targetpositionsts__mainsequence_examples', ['time_index', 'position_set_uid', 'asset_identifier'], unique=True)
    op.create_index('uix__ms_markets__tradests__mainsequence_examples__tr_7ad1af6c1a', 'ms_markets__tradests__mainsequence_examples', ['trade_time', 'trade_identifier', 'account_identifier', 'asset_identifier'], unique=True)
    op.create_index('uix__ms_markets__virtualfundholdingsts__mainsequence_49c5da1a85', 'ms_markets__virtualfundholdingsts__mainsequence_examples', ['time_index', 'virtual_fund_uid', 'asset_identifier'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uix__ms_markets__virtualfundholdingsts__mainsequence_49c5da1a85', table_name='ms_markets__virtualfundholdingsts__mainsequence_examples')
    op.drop_index('uix__ms_markets__tradests__mainsequence_examples__tr_7ad1af6c1a', table_name='ms_markets__tradests__mainsequence_examples')
    op.drop_index('uix__ms_markets__targetpositionsts__mainsequence_exa_c53adaf81e', table_name='ms_markets__targetpositionsts__mainsequence_examples')
    op.drop_index('uix__ms_markets__signalweightsts__mainsequence_examp_486fb6308a', table_name='ms_markets__signalweightsts__mainsequence_examples')
    op.drop_index('uix__ms_markets__portfolioweightsts__mainsequence_ex_c1365e7560', table_name='ms_markets__portfolioweightsts__mainsequence_examples')
    op.drop_index('uix__ms_markets__portfoliosts__mainsequence_examples_18eda21ee1', table_name='ms_markets__portfoliosts__mainsequence_examples')
    op.drop_index('uix__ms_markets__ordersts__mainsequence_examples__or_175e488d61', table_name='ms_markets__ordersts__mainsequence_examples')
    op.drop_index('uix__ms_markets__ordereventsts__mainsequence_example_e5d5b7267c', table_name='ms_markets__ordereventsts__mainsequence_examples')
    op.drop_index('uix__ms_markets__interpolatedpricests__mainsequence_34f03829ba', table_name='ms_markets__interpolatedpricests__mainsequence_examples')
    op.drop_index('uix__ms_markets__indexfixingsts__mainsequence_exampl_47c1458038', table_name='ms_markets__indexfixingsts__mainsequence_examples')
    op.drop_index('uix__ms_markets__discountcurvests__mainsequence_exam_51b8d86135', table_name='ms_markets__discountcurvests__mainsequence_examples')
    op.drop_index('uix__ms_markets__assetsnapshotsts__mainsequence_exam_21493f481e', table_name='ms_markets__assetsnapshotsts__mainsequence_examples')
    op.drop_index('uix__ms_markets__assetpricingdetailsts__mainsequence_3f465e3beb', table_name='ms_markets__assetpricingdetailsts__mainsequence_examples')
    op.drop_index('uix__ms_markets__accountholdingsts__mainsequence_exa_336f239b52', table_name='ms_markets__accountholdingsts__mainsequence_examples')
    # ### end Alembic commands ###
