"""migration

Revision ID: 0006
Revises: 0005
Create Date: 2026-06-05 11:32:02.696782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0006'
down_revision: Union[str, Sequence[str], None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ms_markets__calendardate__mainsequence_examples',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('calendar_uid', sa.Uuid(), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('is_business_day', sa.Boolean(), nullable=False),
    sa.Column('is_holiday', sa.Boolean(), nullable=False),
    sa.Column('is_weekend', sa.Boolean(), nullable=False),
    sa.Column('is_early_close', sa.Boolean(), nullable=False),
    sa.Column('holiday_name', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['calendar_uid'], ['ms_markets__calendar__mainsequence_examples.uid'], name=op.f('fk__ms_markets__calendardate__mainsequence_examples_139944a94b'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__calendardate__mainsequence_examples')),
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.CalendarDate'}
    )
    op.create_index(op.f('ix__ms_markets__calendardate__mainsequence_examples_655c235a4b'), 'ms_markets__calendardate__mainsequence_examples', ['calendar_uid', 'is_business_day'], unique=False)
    op.create_index(op.f('ix__ms_markets__calendardate__mainsequence_examples__local_date'), 'ms_markets__calendardate__mainsequence_examples', ['local_date'], unique=False)
    op.create_index(op.f('uix__ms_markets__calendardate__mainsequence_examples_3928e12e5f'), 'ms_markets__calendardate__mainsequence_examples', ['calendar_uid', 'local_date'], unique=True)
    op.create_table('ms_markets__calendarevent__mainsequence_examples',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('calendar_uid', sa.Uuid(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('event_label', sa.String(length=255), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_uid', sa.Uuid(), nullable=True),
    sa.Column('target_identifier', sa.String(length=255), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['calendar_uid'], ['ms_markets__calendar__mainsequence_examples.uid'], name=op.f('fk__ms_markets__calendarevent__mainsequence_examples_ed8bfdf31a'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__calendarevent__mainsequence_examples')),
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.CalendarEvent'}
    )
    op.create_index(op.f('ix__ms_markets__calendarevent__mainsequence_examples_11efc7e898'), 'ms_markets__calendarevent__mainsequence_examples', ['event_type'], unique=False)
    op.create_index(op.f('ix__ms_markets__calendarevent__mainsequence_examples_63b477ee1a'), 'ms_markets__calendarevent__mainsequence_examples', ['target_type', 'target_uid'], unique=False)
    op.create_index(op.f('ix__ms_markets__calendarevent__mainsequence_examples_d7d0a27b17'), 'ms_markets__calendarevent__mainsequence_examples', ['calendar_uid', 'event_date'], unique=False)
    op.create_index(op.f('uix__ms_markets__calendarevent__mainsequence_example_92503b5092'), 'ms_markets__calendarevent__mainsequence_examples', ['calendar_uid', 'event_date', 'event_type', 'event_label', 'target_type', 'target_identifier'], unique=True)
    op.create_table('ms_markets__calendarsession__mainsequence_examples',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('calendar_uid', sa.Uuid(), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('session_label', sa.String(length=64), nullable=False),
    sa.Column('opens_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closes_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['calendar_uid'], ['ms_markets__calendar__mainsequence_examples.uid'], name=op.f('fk__ms_markets__calendarsession__mainsequence_exampl_d917b767d7'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk__ms_markets__calendarsession__mainsequence_examples')),
    info={'namespace': 'mainsequence.examples', 'identifier': 'mainsequence.examples.CalendarSession'}
    )
    op.create_index(op.f('ix__ms_markets__calendarsession__mainsequence_exampl_270873e502'), 'ms_markets__calendarsession__mainsequence_examples', ['local_date'], unique=False)
    op.create_index(op.f('ix__ms_markets__calendarsession__mainsequence_exampl_2790a5ca68'), 'ms_markets__calendarsession__mainsequence_examples', ['calendar_uid', 'is_primary'], unique=False)
    op.create_index(op.f('uix__ms_markets__calendarsession__mainsequence_examp_320afea704'), 'ms_markets__calendarsession__mainsequence_examples', ['calendar_uid', 'local_date', 'session_label'], unique=True)
    op.add_column('ms_markets__calendar__mainsequence_examples', sa.Column('unique_identifier', sa.String(length=255), nullable=False))
    op.add_column('ms_markets__calendar__mainsequence_examples', sa.Column('display_name', sa.String(length=255), nullable=False))
    op.add_column('ms_markets__calendar__mainsequence_examples', sa.Column('calendar_type', sa.String(length=64), nullable=False))
    op.add_column('ms_markets__calendar__mainsequence_examples', sa.Column('timezone', sa.String(length=64), nullable=False))
    op.add_column('ms_markets__calendar__mainsequence_examples', sa.Column('source', sa.String(length=128), nullable=True))
    op.add_column('ms_markets__calendar__mainsequence_examples', sa.Column('source_identifier', sa.String(length=255), nullable=True))
    op.add_column('ms_markets__calendar__mainsequence_examples', sa.Column('valid_from', sa.Date(), nullable=False))
    op.add_column('ms_markets__calendar__mainsequence_examples', sa.Column('valid_to', sa.Date(), nullable=False))
    op.drop_index(op.f('uix__ms_markets__calendar__mainsequence_examples__name'), table_name='ms_markets__calendar__mainsequence_examples')
    op.create_index(op.f('ix__ms_markets__calendar__mainsequence_examples__calendar_type'), 'ms_markets__calendar__mainsequence_examples', ['calendar_type'], unique=False)
    op.create_index(op.f('ix__ms_markets__calendar__mainsequence_examples__sou_2ddf7c50e9'), 'ms_markets__calendar__mainsequence_examples', ['source', 'source_identifier'], unique=False)
    op.create_index(op.f('uix__ms_markets__calendar__mainsequence_examples__un_b900d44ed4'), 'ms_markets__calendar__mainsequence_examples', ['unique_identifier'], unique=True)
    op.drop_column('ms_markets__calendar__mainsequence_examples', 'name')
    op.drop_column('ms_markets__calendar__mainsequence_examples', 'calendar_dates')
    op.add_column('ms_markets__portfolio__mainsequence_examples', sa.Column('calendar_uid', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix__ms_markets__portfolio__mainsequence_examples__calendar_uid'), 'ms_markets__portfolio__mainsequence_examples', ['calendar_uid'], unique=False)
    op.create_foreign_key(op.f('fk__ms_markets__portfolio__mainsequence_examples__ca_e64c32eae0'), 'ms_markets__portfolio__mainsequence_examples', 'ms_markets__calendar__mainsequence_examples', ['calendar_uid'], ['uid'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk__ms_markets__portfolio__mainsequence_examples__ca_e64c32eae0'), 'ms_markets__portfolio__mainsequence_examples', type_='foreignkey')
    op.drop_index(op.f('ix__ms_markets__portfolio__mainsequence_examples__calendar_uid'), table_name='ms_markets__portfolio__mainsequence_examples')
    op.drop_column('ms_markets__portfolio__mainsequence_examples', 'calendar_uid')
    op.add_column('ms_markets__calendar__mainsequence_examples', sa.Column('calendar_dates', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('ms_markets__calendar__mainsequence_examples', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('uix__ms_markets__calendar__mainsequence_examples__un_b900d44ed4'), table_name='ms_markets__calendar__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__calendar__mainsequence_examples__sou_2ddf7c50e9'), table_name='ms_markets__calendar__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__calendar__mainsequence_examples__calendar_type'), table_name='ms_markets__calendar__mainsequence_examples')
    op.create_index(op.f('uix__ms_markets__calendar__mainsequence_examples__name'), 'ms_markets__calendar__mainsequence_examples', ['name'], unique=True)
    op.drop_column('ms_markets__calendar__mainsequence_examples', 'valid_to')
    op.drop_column('ms_markets__calendar__mainsequence_examples', 'valid_from')
    op.drop_column('ms_markets__calendar__mainsequence_examples', 'source_identifier')
    op.drop_column('ms_markets__calendar__mainsequence_examples', 'source')
    op.drop_column('ms_markets__calendar__mainsequence_examples', 'timezone')
    op.drop_column('ms_markets__calendar__mainsequence_examples', 'calendar_type')
    op.drop_column('ms_markets__calendar__mainsequence_examples', 'display_name')
    op.drop_column('ms_markets__calendar__mainsequence_examples', 'unique_identifier')
    op.drop_index(op.f('uix__ms_markets__calendarsession__mainsequence_examp_320afea704'), table_name='ms_markets__calendarsession__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__calendarsession__mainsequence_exampl_2790a5ca68'), table_name='ms_markets__calendarsession__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__calendarsession__mainsequence_exampl_270873e502'), table_name='ms_markets__calendarsession__mainsequence_examples')
    op.drop_table('ms_markets__calendarsession__mainsequence_examples')
    op.drop_index(op.f('uix__ms_markets__calendarevent__mainsequence_example_92503b5092'), table_name='ms_markets__calendarevent__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__calendarevent__mainsequence_examples_d7d0a27b17'), table_name='ms_markets__calendarevent__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__calendarevent__mainsequence_examples_63b477ee1a'), table_name='ms_markets__calendarevent__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__calendarevent__mainsequence_examples_11efc7e898'), table_name='ms_markets__calendarevent__mainsequence_examples')
    op.drop_table('ms_markets__calendarevent__mainsequence_examples')
    op.drop_index(op.f('uix__ms_markets__calendardate__mainsequence_examples_3928e12e5f'), table_name='ms_markets__calendardate__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__calendardate__mainsequence_examples__local_date'), table_name='ms_markets__calendardate__mainsequence_examples')
    op.drop_index(op.f('ix__ms_markets__calendardate__mainsequence_examples_655c235a4b'), table_name='ms_markets__calendardate__mainsequence_examples')
    op.drop_table('ms_markets__calendardate__mainsequence_examples')
    # ### end Alembic commands ###
