"""portfolio_equal_weights_dynamic_interpolated_prices_2418c22d8df4a6ff3c7cf0778f11ed49

Revision ID: 0009
Revises: 0008
Create Date: 2026-06-07 11:17:38.618993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0009'
down_revision: Union[str, Sequence[str], None] = '0008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mt_mainsequence_examples_2418c22d8df4a6ff3c7cf0778f11ed49',
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.Column('asset_identifier', sa.String(), nullable=False),
    sa.Column('open_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('trade_count', sa.Float(), nullable=True),
    sa.Column('vwap', sa.Float(), nullable=True),
    sa.Column('interpolated', sa.Boolean(), nullable=True),
    info={'markets_storage_app': 'ms_markets'}
    )
    op.create_index('uix__mt_mainsequence_examples_2418c22d8df4a6ff3c7cf0_027031cf08', 'mt_mainsequence_examples_2418c22d8df4a6ff3c7cf0778f11ed49', ['time_index', 'asset_identifier'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uix__mt_mainsequence_examples_2418c22d8df4a6ff3c7cf0_027031cf08', table_name='mt_mainsequence_examples_2418c22d8df4a6ff3c7cf0778f11ed49')
    op.drop_table('mt_mainsequence_examples_2418c22d8df4a6ff3c7cf0778f11ed49')
    # ### end Alembic commands ###
